# ********RoostGPT********

# Test generated by RoostGPT for test testing-project-path-error using AI Type Azure Open AI and AI Model gpt-4o
# 
# Feature file generated for /appointment/{appointmentId}_get for http method type GET 
# RoostTestHash=972c444da4
# 
# 

# ********RoostGPT********
Feature: Karate Tests for Retrieve Appointment API

  Background:
    * def baseURL = karate.properties['APPOINTMENT_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * header Accept = 'application/json'

  Scenario Outline: Successfully retrieve an appointment with valid appointmentId
    Given path '/appointment', '<appointmentId>'
    When method GET
    Then status 200
    And match response.appointments.id == '#string'
    And match response.appointments.id.length <= 15
    And match response.appointments.lifeCycleStatus == '#string'
    And match response.appointments.lifeCycleStatus.length <= 64
    And match response.appointments.occurrences == '#[0]'
    And match each response.appointments.occurrences[*].creationDateTime == '#string'
    And match each response.appointments.occurrences[*].creationDateTime.length <= 25
    And match each response.appointments.occurrences[*].finishDate == '#string'
    And match each response.appointments.occurrences[*].finishDate.length <= 25
    And match each response.appointments.occurrences[*].reason == '#string'
    And match each response.appointments.occurrences[*].reason.length <= 250
    And match each response.appointments.occurrences[*].reasonDetail == '#string'
    And match each response.appointments.occurrences[*].reasonDetail.length <= 250
    And match each response.appointments.occurrences[*].startDate == '#string'
    And match each response.appointments.occurrences[*].startDate.length <= 25
    And match response.control.code == '#string'
    And match response.control.code.length <= 3
    And match response.control.message == '#string'
    And match response.control.message.length <= 250
    And match response.control.type == '#string'
    And match response.control.type.length <= 1

    Examples:
      | appointmentId  |
      | SA-100123      |
      | SA-100456      |

  Scenario: Bad Request response when passing an invalid appointmentId
    Given path '/appointment', 'INVALID-APPOINTMENT-ID'
    When method GET
    Then status 400
    And match response.control.code == '#string'
    And match response.control.code == '400'
    And match response.control.message == '#string'
    And match response.control.message.length <= 250
    And match response.control.type == '#string'
    And match response.control.type.length == 1

  Scenario: Unauthorized access when API key is not valid
    Given path '/appointment', 'SA-100123'
    * header Authorization = 'Bearer INVALID_TOKEN'
    When method GET
    Then status 401
    And match response.control.code == '#string'
    And match response.control.code == '401'
    And match response.control.message == '#string'
    And match (response.control.message == 'Unauthorized' || response.control.message == 'PriorizaÃ§Ã£o de agendamento nÃ£o autorizado')
    And match response.control.type == '#string'
    And match response.control.type.length == 1

  Scenario Outline: Forbidden for unsupported credentials
    Given path '/appointment', 'SA-100123'
    * header Authorization = 'Bearer <token>'
    When method GET
    Then status 403
    And match response.control.code == '#string'
    And match response.control.code == '403'
    And match response.control.message == '#string'
    And match response.control.message == '<message>'
    And match response.control.type == '#string'
    And match response.control.type.length == 1

    Examples:
      | token              | message                        |
      | TOKEN_SCOPE_INVALID | Forbidden - Scope Not Permitted |

  Scenario: Not Found when requesting appointmentId does not exist
    Given path '/appointment', 'SA-999999'
    When method GET
    Then status 404
    And match response.control.code == '#string'
    And match response.control.code == '404'
    And match response.control.message == '#string'
    And match response.control.message == 'Not Found'
    And match response.control.type == '#string'
    And match response.control.type.length == 1

  Scenario: Too Many Requests
    Given path '/appointment', 'SA-100123'
    * header Rate-Limit-Test = 'TRUE'
    When method GET
    Then status 429
    And match response.control.code == '#string'
    And match response.control.code == '429'
    And match response.control.message == 'Too Many Requests - Exceeded Quota'
    And match response.control.type == '#string'
    And match response.control.type.length == 1

  Scenario: Server Error
    Given path '/appointment', 'SA-100123'
    * header Simulate-Server-Error = 'TRUE'
    When method GET
    Then status 500
    And match response.control.code == '#string'
    And match response.control.code == '500'
    And match response.control.message == '#string'
    And match response.control.message == 'Internal Server Error'
    And match response.control.type == '#string'
    And match response.control.type == 'T'
