# ********RoostGPT********

# Test generated by RoostGPT for test testing-project-path-error using AI Type Azure Open AI and AI Model gpt-4o
# 
# Feature file generated for /appointment_post for http method type POST 
# RoostTestHash=f737d5caf2
# 
# 

# ********RoostGPT********
Feature: API Test for Create Appointment Endpoint

  Background:
    * def baseURL = karate.properties['APPOINTMENT_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * header Accept = 'application/json'

  Scenario Outline: Validate successful appointment creation (201 Created)
    Given path '/appointment'
    And request 
      """
      {
        "appointment": {
          "reason": "<reason>",
          "slot": {
            "id": "<slot_id>"
          }
        }
      }
      """
    When method POST
    Then status 201
    And match response.address.id == '#number'
    And match response.appointment.finishDate == '#string'
    And match response.appointment.id == '#string'
    And match response.appointment.priority.flag == '#boolean'
    And match response.appointment.priority.reason == '#string'
    And match response.appointment.startDate == '#string'
    And match response.control.code == '#string'
    And match response.control.message == '#string'
    And match response.control.type == '#string'
    And match response.customer.subscriberId == '#string'
    And match response.order.addressChange.flag == '#boolean'
    And match response.order.associatedDocument == '#string'
    And match response.order.type == 'Instalacao'
    And match response.products.product[*].type == '#array' 
    Examples:
      | reason                             | slot_id                                  |
      | 'Agendamento para Instalação de Fibra' | 'bff13821-73c3-42cc-9327-b05c7df5a67f' |

  Scenario Outline: Validate bad request response (400 Bad Request)
    Given path '/appointment'
    And request 
      """
      {
        "appointment": {
          "reason": "<reason>",
          "slot": {
            "id": "<slot_id>"
          }
        }
      }
      """
    When method POST
    Then status 400
    And match response.control.code == '#string'
    And match response.control.message == '#string'
    And match response.control.type == 'E'
    Examples:
      | reason      | slot_id |
      | ''          | 'null'  |
      | 'Invalid'   | '###'   |

  Scenario: Validate unauthorized access response (401 Unauthorized)
    Given path '/appointment'
    And header Authorization = 'Bearer <invalid_token>'
    And request 
      """
      {
        "appointment": {
          "reason": "Agendamento inválido",
          "slot": {
            "id": "dummy-id"
          }
        }
      }
      """
    When method POST
    Then status 401
    And match response.control.code == '#string'
    And match response.control.message == '#string'
    And match response.control.type == 'E'

  Scenario: Validate slot not found response (404 Not Found)
    Given path '/appointment'
    And request 
      """
      {
        "appointment": {
          "reason": "Slot inexistente",
          "slot": {
            "id": "non-existing-slot-id"
          }
        }
      }
      """
    When method POST
    Then status 404
    And match response.control.code == '#string'
    And match response.control.message == '#string'
    And match response.control.type == 'E'

  Scenario: Validate too many requests response (429 Too Many Requests)
    Given path '/appointment'
    And request 
      """
      {
        "appointment": {
          "reason": "Request quota exceeded",
          "slot": {
            "id": "bff13821-73c3-42cc-9327-b05c7df5a67f"
          }
        }
      }
      """
    When method POST
    Then status 429
    And match response.control.code == '#string'
    And match response.control.message == '#string'
    And match response.control.type == 'E'

  Scenario: Validate internal server error response (500 Internal Server Error)
    Given path '/appointment'
    And request 
      """
      {
        "appointment": {
          "reason": "Internal error test",
          "slot": {
            "id": "non-valid-slot-id"
          }
        }
      }
      """
    When method POST
    Then status 500
    And match response.control.code == '#string'
    And match response.control.message == '#string'
    And match response.control.type == 'T'
