# ********RoostGPT********

# Test generated by RoostGPT for test xcally-karate using AI Type Claude AI and AI Model claude-sonnet-4-20250514
# 
# Feature file generated for /auth/local/forgot_post for http method type POST 
# RoostTestHash=57df9e5c0a
# 
# 

# ********RoostGPT********
Feature: Authentication - Local Forgot Password

  Background:
    * def baseURL = karate.properties['XCALLY_MOTION_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure headers = { Accept: 'application/json', 'Content-Type': 'application/json' }

  Scenario Outline: Create password reset token with valid email - Bearer Token Auth
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json', 'Content-Type': 'application/json' }
    Given path '/auth/local/forgot'
    And request
      """
      {
        "email": "<email>"
      }
      """
    When method POST
    Then status 201

    Examples:
      | read('auth_local_forgot_post.csv') |

  Scenario Outline: Create password reset token with valid email - Basic Auth
    * def username = karate.properties['BASIC_USERNAME']
    * def password = karate.properties['BASIC_PASSWORD']
    * def credentials = username + ':' + password
    * def encoded = Java.type('java.util.Base64').getEncoder().encodeToString(credentials.getBytes())
    * def authHeader = 'Basic ' + encoded
    * configure headers = { Authorization: '#(authHeader)', Accept: 'application/json', 'Content-Type': 'application/json' }
    Given path '/auth/local/forgot'
    And request
      """
      {
        "email": "<email>"
      }
      """
    When method POST
    Then status 201

    Examples:
      | read('auth_local_forgot_post.csv') |

  Scenario Outline: Create password reset token with valid email - API Key Auth
    * def authToken = karate.properties['apikey']
    Given path '/auth/local/forgot'
    And param apikey = authToken
    And request
      """
      {
        "email": "<email>"
      }
      """
    When method POST
    Then status 201

    Examples:
      | read('auth_local_forgot_post.csv') |

  Scenario: Create password reset token with missing email - Bearer Token Auth
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json', 'Content-Type': 'application/json' }
    Given path '/auth/local/forgot'
    And request
      """
      {
      }
      """
    When method POST
    Then assert responseStatus != 201

  Scenario: Create password reset token with empty email - Bearer Token Auth
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json', 'Content-Type': 'application/json' }
    Given path '/auth/local/forgot'
    And request
      """
      {
        "email": ""
      }
      """
    When method POST
    Then assert responseStatus != 201

  Scenario: Create password reset token with invalid email format - Bearer Token Auth
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json', 'Content-Type': 'application/json' }
    Given path '/auth/local/forgot'
    And request
      """
      {
        "email": "invalid-email"
      }
      """
    When method POST
    Then assert responseStatus != 201

  Scenario: Handle internal server error - Bearer Token Auth
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json', 'Content-Type': 'application/json' }
    Given path '/auth/local/forgot'
    And request
      """
      {
        "email": "test@example.com"
      }
      """
    When method POST
    And match responseStatus == 500
    Then match response.code == 500
    And match response.message == '#string'
    And match response.stack == '##string'
    And match response.details == '##object'

  Scenario: Handle internal server error - Basic Auth
    * def username = karate.properties['BASIC_USERNAME']
    * def password = karate.properties['BASIC_PASSWORD']
    * def credentials = username + ':' + password
    * def encoded = Java.type('java.util.Base64').getEncoder().encodeToString(credentials.getBytes())
    * def authHeader = 'Basic ' + encoded
    * configure headers = { Authorization: '#(authHeader)', Accept: 'application/json', 'Content-Type': 'application/json' }
    Given path '/auth/local/forgot'
    And request
      """
      {
        "email": "test@example.com"
      }
      """
    When method POST
    And match responseStatus == 500
    Then match response.code == 500
    And match response.message == '#string'
    And match response.stack == '##string'
    And match response.details == '##object'

  Scenario: Handle internal server error - API Key Auth
    * def authToken = karate.properties['apikey']
    Given path '/auth/local/forgot'
    And param apikey = authToken
    And request
      """
      {
        "email": "test@example.com"
      }
      """
    When method POST
    And match responseStatus == 500
    Then match response.code == 500
    And match response.message == '#string'
    And match response.stack == '##string'
    And match response.details == '##object'

  Scenario: Create password reset token with null email - Bearer Token Auth
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json', 'Content-Type': 'application/json' }
    Given path '/auth/local/forgot'
    And request
      """
      {
        "email": null
      }
      """
    When method POST
    Then assert responseStatus != 201

  Scenario: Create password reset token with additional properties - Bearer Token Auth
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json', 'Content-Type': 'application/json' }
    Given path '/auth/local/forgot'
    And request
      """
      {
        "email": "user@example.com",
        "extraField": "extraValue"
      }
      """
    When method POST
    Then status 201
