# ********RoostGPT********

# Test generated by RoostGPT for test testing-project-path-error using AI Type Azure Open AI and AI Model gpt-4o
# 
# Feature file generated for /searchTimeSlot_get for http method type GET 
# RoostTestHash=3ba2ac6502
# 
# 

# ********RoostGPT********
Feature: Search Time Slot API Tests

  Background:
    * def baseURL = karate.properties['APPOINTMENT_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure headers = { Accept: 'application/json' }

  Scenario Outline: Validate successful response for searchTimeSlot API
    Given path '/searchTimeSlot'
    And param addressId = <addressId>
    And param subscriberId = <subscriberId>
    And param associatedDocument = <associatedDocument>
    And param startDate = <startDate>
    And param finishDate = <finishDate>
    And param orderType = <orderType>
    And param addressChangeFlag = <addressChangeFlag>
    And param productType = <productType>
    And param priorityFlag = <priorityFlag>
    And param priorityReason = <priorityReason>
    When method GET
    Then status 200
    And match response.control.code == '#string'
    And match response.control.message == '#string'
    And match response.control.type == '#string'
    And match response.slots == '#array'
    And match each response.slots[*].expireIn == '#number'
    And match each response.slots[*].finishDate == '#string'
    And match each response.slots[*].id == '#string'
    And match each response.slots[*].startDate == '#string'

    Examples:
      | addressId | subscriberId | associatedDocument | startDate                 | finishDate               | orderType   | addressChangeFlag | productType                 | priorityFlag | priorityReason     |
      | 17713     | 'VTAL001'    | 'VTT001'           | '2021-05-21T13:00:00'     | '2021-06-04T13:00:00'    | 'Instalacao' | true              | ['Banda Larga']            | true         | 'Cliente Diamond'  |
      | 17713     | null         | 'VTT001'           | '2021-05-21T13:00:00'     | '2021-06-04T13:00:00'    | 'Retirada'  | null              | ['Banda Larga']            | false        | null               |

  Scenario: Validate 400 Bad Request response
    Given path '/searchTimeSlot'
    And param addressId = null
    And param associatedDocument = 'VTT001'
    And param startDate = '2021-05-21T13:00:00'
    And param finishDate = '2021-06-04T13:00:00'
    And param orderType = 'RemanejamentoPonto'
    And param productType = ['Banda Larga']
    When method GET
    Then status 400
    And match response.control.code == '#string'
    And match response.control.message == '#string'
    And match response.control.type == '#string'

  Scenario: Validate 401 Unauthorized response
    Given path '/searchTimeSlot'
    And param addressId = 17713
    And param associatedDocument = 'VTT001'
    And param startDate = '2021-05-21T13:00:00'
    And param finishDate = '2021-06-04T13:00:00'
    And param orderType = 'ChamadoTecnico'
    And param productType = ['Banda Larga']
    And param priorityFlag = true
    And param priorityReason = 'Higher Priority'
    When method GET
    Then status 401
    And match response.control.code == '#string'
    And match response.control.message == '#string'
    And match response.control.type == '#string'

  Scenario: Validate 404 Not Found response
    Given path '/searchTimeSlot'
    And param addressId = 99999
    And param associatedDocument = 'RandomDoc'
    And param startDate = '2022-05-21T13:00:00'
    And param finishDate = '2022-06-04T13:00:00'
    And param orderType = 'InvalidType'
    And param productType = ['Unknown']
    When method GET
    Then status 404
    And match response.control.code == '#string'
    And match response.control.message == '#string'
    And match response.control.type == '#string'

  Scenario: Validate response for too many requests
    Given path '/searchTimeSlot'
    And param addressId = 17713
    And param associatedDocument = 'VTT001'
    And param startDate = '2021-05-21T13:00:00'
    And param finishDate = '2021-06-04T13:00:00'
    And param orderType = 'Instalacao'
    And param productType = ['Banda Larga']
    When method GET
    Then status 429
    And match response.control.code == '#string'
    And match response.control.message == '#string'
    And match response.control.type == '#string'
