# ********RoostGPT********

# Test generated by RoostGPT for test swagger-xcally using AI Type Claude AI and AI Model claude-3-5-sonnet-20240620
# 
# Feature file generated for /auth/local/forgot_post for http method type POST 
# RoostTestHash=57df9e5c0a
# 
# 

# ********RoostGPT********
Feature: Local Forgot Password API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario Outline: Create a new password reset token
    Given path '/auth/local/forgot'
    And request
      """
      {
        "email": "<email>"
      }
      """
    When method POST
    Then status 201
    And match response == ''

    Examples:
      | read('auth_local_forgot_post.csv') |

  Scenario: Attempt to create a password reset token with missing email
    Given path '/auth/local/forgot'
    And request {}
    When method POST
    Then status 400

  Scenario: Internal server error when creating a password reset token
    Given path '/auth/local/forgot'
    And request
      """
      {
        "email": "error@example.com"
      }
      """
    When method POST
    Then status 500
    And match response contains { code: 500, message: '#string' }
    And match response.code == 500
    And match response.message == 'Internal Server Error'
    And match response contains { stack: '#string' }
    And match response contains { details: '#object' }
