# ********RoostGPT********

# Test generated by RoostGPT for test vtal-api using AI Type Open AI and AI Model gpt-4o-2024-05-13
# 
# Feature file generated for /appointment/{appointmentId}_delete for http method type DELETE 
# RoostTestHash=8ae4a840f9
# 
# 

# ********RoostGPT********
Feature: Delete Appointment API Tests

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def AUTH_TOKEN = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: 'Bearer ' + AUTH_TOKEN }

  Scenario Outline: Delete Appointment with valid parameters
    Given path 'appointment', '<appointmentId>'
    And param appointmentReason = '<appointmentReason>'
    And param appointmentComments = '<appointmentComments>'
    When method DELETE
    Then status 200
    And match response.control.type == 'S'
    And match response.control.code == 200
    And match response.control.message == 'OK'

    Examples:
      | read('appointment_appointmentId_delete.csv') |

  Scenario Outline: Delete Appointment with missing required parameters
    Given path 'appointment', '<appointmentId>'
    And param appointmentReason = '<appointmentReason>'
    When method DELETE
    Then status 400
    And match response.control.type == 'E'
    And match response.control.code == 400
    And match response.control.message == 'Bad Request'

    Examples:
      | appointmentId | appointmentReason |
      | SA-562403     |                   |
      | SA-562404     |                   |

  Scenario Outline: Delete Appointment with invalid authorization
    Given path 'appointment', '<appointmentId>'
    And param appointmentReason = 'Cancelamento Checkout'
    And param appointmentComments = 'Cancelamento Checkout'
    * configure headers = { Authorization: 'Bearer INVALID_TOKEN' }
    When method DELETE
    Then status 401
    And match response.control.type == 'E'
    And match response.control.code == 401
    And match response.control.message == 'Unauthorized'

    Examples:
      | appointmentId |
      | SA-562403     |
      | SA-562404     |

  Scenario Outline: Delete Appointment not found
    Given path 'appointment', '<appointmentId>'
    And param appointmentReason = 'Cancelamento Checkout'
    And param appointmentComments = 'Cancelamento Checkout'
    When method DELETE
    Then status 404
    And match response.control.type == 'E'
    And match response.control.code == 404
    And match response.control.message == 'Not Found'

    Examples:
      | appointmentId |
      | SA-999999     |
      | SA-888888     |

  Scenario Outline: Delete Appointment service unavailable
    Given path 'appointment', '<appointmentId>'
    And param appointmentReason = 'Cancelamento Checkout'
    And param appointmentComments = 'Cancelamento Checkout'
    When method DELETE
    Then status 503
    And match response.control.type == 'T'
    And match response.control.code == 503
    And match response.control.message == 'Service Unavailable'

    Examples:
      | appointmentId |
      | SA-562403     |
      | SA-562404     |
