# ********RoostGPT********

# Test generated by RoostGPT for test vtal-api using AI Type Open AI and AI Model gpt-4o-2024-05-13
# 
# Feature file generated for /appointment/{appointmentId}_get for http method type GET 
# RoostTestHash=b69bb60b36
# 
# 

# ********RoostGPT********
Feature: Retrieve Appointment API Tests

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']

  Scenario Outline: Retrieve Appointment - Successful Operation
    Given path '/appointment/<appointmentId>'
    And header Authorization = 'Bearer ' + authToken
    When method GET
    Then status 200
    And match response.control.type == 'S'
    And match response.control.code == '200'
    And match response.control.message == 'Ok'
    And match response.appointments.id == '<appointmentId>'
    And match response.appointments.lifeCycleStatus == 'Não atribuído'
    And match response.appointments.occurrences[0].creationDateTime == '2021-12-07T12:17:20'
    And match response.appointments.occurrences[0].startDate == '2021-10-09T13:00:00'
    And match response.appointments.occurrences[0].finishDate == '2021-10-09T18:00:00'
    And match response.appointments.occurrences[0].reason == 'Teste Vtal CW'
    And match response.appointments.occurrences[0].reasonDetail == 'Teste Vtal CW'

    Examples:
      | read('appointment_appointmentId_get.csv') |

  Scenario Outline: Retrieve Appointment - Bad Request
    Given path '/appointment/<appointmentId>'
    And header Authorization = 'Bearer ' + authToken
    When method GET
    Then status 400
    And match response.control.type == 'E'
    And match response.control.code == '400'
    And match response.control.message == 'Bad Request'

    Examples:
      | appointmentId |
      | invalid-id    |

  Scenario Outline: Retrieve Appointment - Unauthorized
    Given path '/appointment/<appointmentId>'
    When method GET
    Then status 401
    And match response.control.type == 'E'
    And match response.control.code == '401'
    And match response.control.message == 'Unauthorized'

    Examples:
      | appointmentId |
      | SA-562403     |

  Scenario Outline: Retrieve Appointment - Forbidden
    Given path '/appointment/<appointmentId>'
    And header Authorization = 'Bearer ' + authToken
    When method GET
    Then status 403
    And match response.control.type == 'E'
    And match response.control.code == '403'
    And match response.control.message == 'Forbidden - Scope Not Permitted'

    Examples:
      | appointmentId |
      | SA-562403     |

  Scenario Outline: Retrieve Appointment - Not Found
    Given path '/appointment/<appointmentId>'
    And header Authorization = 'Bearer ' + authToken
    When method GET
    Then status 404
    And match response.control.type == 'E'
    And match response.control.code == '404'
    And match response.control.message == 'Not Found'

    Examples:
      | appointmentId |
      | SA-999999     |

  Scenario Outline: Retrieve Appointment - Internal Server Error
    Given path '/appointment/<appointmentId>'
    And header Authorization = 'Bearer ' + authToken
    When method GET
    Then status 500
    And match response.control.type == 'T'
    And match response.control.code == '500'
    And match response.control.message == 'Internal Server Error'

    Examples:
      | appointmentId |
      | SA-562403     |

  Scenario Outline: Retrieve Appointment - Service Unavailable
    Given path '/appointment/<appointmentId>'
    And header Authorization = 'Bearer ' + authToken
    When method GET
    Then status 503
    And match response.control.type == 'T'
    And match response.control.code == '503'
    And match response.control.message == 'Service Unavailable'

    Examples:
      | appointmentId |
      | SA-562403     |

  Scenario Outline: Retrieve Appointment - Gateway Timeout
    Given path '/appointment/<appointmentId>'
    And header Authorization = 'Bearer ' + authToken
    When method GET
    Then status 504
    And match response.control.type == 'T'
    And match response.control.code == '504'
    And match response.control.message == 'Gateway Timeout'

    Examples:
      | appointmentId |
      | SA-562403     |
