# ********RoostGPT********

# Test generated by RoostGPT for test APIs-Fulfillment using AI Type Open AI and AI Model gpt-4-turbo
# 
# Feature file generated for /cancelProductOrder/{order.Id}_post for http method type POST 
# RoostTestHash=284cdcff34
# 
# 

# ********RoostGPT********
Feature: Cancel Product Order By Id

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * header Authorization = 'Bearer ' + authToken

  Scenario Outline: Cancel order with valid ID and request body
    Given path 'cancelProductOrder', '<order_id>'
    And request 
    """
    <body>
    """
    When method POST
    Then status 200
    And match response == 
    """
    <expected_response>
    """

    Examples:
      | order_id         | body                                                                                                    | expected_response                                                     |
      | '20230315000001' | { "order": { "associatedDocument": "VTT001", "customer": { "subscriberId": "SVTAL001" } } }             | { "control": { "type": "S", "code": "200", "message": "OK" } }        |

  Scenario Outline: Cancel order with invalid ID
    Given path 'cancelProductOrder', '<order_id>'
    And request 
    """
    <body>
    """
    When method POST
    Then status 400
    And match response == 
    """
    <expected_response>
    """

    Examples:
      | order_id     | body                                                                                                    | expected_response                                                     |
      | 'invalid_id' | { "order": { "associatedDocument": "VTT002", "customer": { "subscriberId": "SVTAL002" } } }             | { "control": { "type": "E", "code": "400", "message": "Bad Request" } } |

  Scenario Outline: Cancel order unauthorized access
    Given path 'cancelProductOrder', '<order_id>'
    And request 
    """
    <body>
    """
    When method POST
    Then status 401
    And match response == 
    """
    <expected_response>
    """

    Examples:
      | order_id         | body                                                                                                    | expected_response                                                     |
      | '20230315000001' | { "order": { "associatedDocument": "VTT001", "customer": { "subscriberId": "SVTAL001" } } }             | { "control": { "type": "E", "code": "401", "message": "Unauthorized" } } |

  Scenario Outline: Cancel order with not found ID
    Given path 'cancelProductOrder', '<order_id>'
    And request 
    """
    <body>
    """
    When method POST
    Then status 404
    And match response == 
    """
    <expected_response>
    """

    Examples:
      | order_id         | body                                                                                                    | expected_response                                                     |
      | '20230315000002' | { "order": { "associatedDocument": "VTT003", "customer": { "subscriberId": "SVTAL003" } } }             | { "control": { "type": "E", "code": "404", "message": "Not Found" } } |
