# ********RoostGPT********

# Test generated by RoostGPT for test fflive using AI Type Open AI and AI Model gpt-4-turbo
# 
# Feature file generated for /listener/cancelProductOrderCreateEvent_post for http method type POST 
# RoostTestHash=410c81a448
# 
# 

# ********RoostGPT********
Feature: Cancel Product Order Create Event By Client

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * header Authorization = 'Bearer ' + authToken

  Scenario: Valid request to cancel product order create event
    Given path '/listener/cancelProductOrderCreateEvent'
    And request
      """
      { 
        "notification": { 
          "date": "2023-09-12T08:00:00Z", 
          "customer": { 
            "subscriberId": "1234567890" 
          }, 
          "order": { 
            "id": "ORD001", 
            "correlationOrder": "CORR001", 
            "associatedDocument": "DOC001", 
            "issue": { 
              "code": { 
                "code": 7001 
              }, 
              "description": { 
                "description": "Pendência Cancelamento por Duplicidade" 
              }, 
              "type": "CLIENTE", 
              "observation": "Cliente solicita cancelamento", 
              "updateDate": "2023-09-12T09:00:00Z", 
              "action": "fechar", 
              "task": "task001", 
              "fieldActivity": "True", 
              "reason": "Duplicity" 
            } 
          }, 
          "type": "Tipo1", 
          "code": "1", 
          "description": "Ordem cancelada", 
          "lostEquipment": "False", 
          "resource": { 
            "gponAccess": "GPON001", 
            "devices": { 
              "device": [
                { 
                  "category": "CAT1", 
                  "type": "Type1", 
                  "description": "Desc1", 
                  "state": "Active", 
                  "usageState": "InUse", 
                  "startOperatingDate": "2023-09-12T10:00:00Z" 
                }
              ] 
            }, 
            "fiberPath": { 
              "items": { 
                "item": [
                  { 
                    "name": "Fiber1", 
                    "value": "Val1" 
                  }
                ] 
              } 
            } 
          } 
        } 
      }
      """
    When method POST
    Then status 204

  Scenario Outline: Test various invalid scenarios for cancel product order create event
    Given path '/listener/cancelProductOrderCreateEvent'
    And request <body>
    When method POST
    Then status <expectedStatus>

    Examples:
      | read('listener_cancelProductOrderCreateEvent_post.csv') |

  Scenario: Unauthorized request to cancel product order create event
    * header Authorization = 'Bearer invalid_token'
    Given path '/listener/cancelProductOrderCreateEvent'
    And request
      """
      { 
        "notification": { 
          "date": "2023-09-12T08:00:00Z", 
          "customer": { 
            "subscriberId": "1234567890" 
          }, 
          "order": { 
            "id": "ORD001" 
          } 
        } 
      }
      """
    When method POST
    Then status 401
