# ********RoostGPT********

# Test generated by RoostGPT for test fflive using AI Type Open AI and AI Model gpt-4-turbo
# 
# Feature file generated for /listener/productOrderStateChangeEvent_post for http method type POST 
# RoostTestHash=6f5fd9fdba
# 
# 

# ********RoostGPT********
Feature: State Change Event By Client API Tests

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario Outline: Valid State Change Event Notification
    Given path '/listener/productOrderStateChangeEvent'
    And request <payload>
    And header Authorization = 'Bearer ' + karate.properties['AUTH_TOKEN']
    When method post
    Then status 204
    And match response == '#null'

    Examples:
      | read('listener_productOrderStateChangeEvent_post.csv') |

  Scenario: Unauthorized State Change Event Notification
    Given path '/listener/productOrderStateChangeEvent'
    And request read('examples/closing-notification.json')
    When method post
    Then status 401

  Scenario: Bad Request State Change Event Notification
    Given path '/listener/productOrderStateChangeEvent'
    And request {}
    And header Authorization = 'Bearer ' + karate.properties['AUTH_TOKEN']
    When method post
    Then status 400

  Scenario: Server Error During State Change Event Notification
    Given path '/listener/productOrderStateChangeEvent'
    And request read('examples/closing-notification.json')
    And header Authorization = 'Bearer ' + karate.properties['AUTH_TOKEN']
    When method post
    Then status 500
