# ********RoostGPT********

# Test generated by RoostGPT for test vtal-karate using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /listener/productOrderCreateEvent_post for http method type POST 
# RoostTestHash=9b45f7ab6a
# 
# 

# ********RoostGPT********
Feature: Product Order Create Event By Client

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authHeader = { Authorization: '#(karate.properties['AUTH_TOKEN'])' }
    * configure headers = authHeader

  Scenario Outline: Test Product Order Create Event API for different HTTP methods and valid input payloads
    Given path '/listener/productOrderCreateEvent'
    And request '''<requestBody>'''
    When method <method>
    Then status <status>

    Examples:
      | read('listener_productOrderCreateEvent_post.csv') |

  Scenario Outline: Verifying the correctness of response codes and response bodies returned by the Product Order Create Event API
    Given path '/listener/productOrderCreateEvent'
    And request '''<requestBody>'''
    When method 'post'
    Then status <status>
    And match responseHeaders contains { 'Content-Type': '#string' }
    And match response == <responseBody>

    Examples:
      | read('listener_productOrderCreateEvent_post.csv') |
