# ********RoostGPT********

# Test generated by RoostGPT for test APIs-Fulfillment using AI Type Open AI and AI Model gpt-4-turbo
# 
# Feature file generated for /listener/cancelProductOrderCreateEvent_post for http method type POST 
# RoostTestHash=410c81a448
# 
# 

# ********RoostGPT********
Feature: Cancel Product Order Create Event By Client

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * header Authorization = 'Bearer ' + authToken

  Scenario: Successfully cancel a product order create event with valid request
    Given path '/listener/cancelProductOrderCreateEvent'
    And request
      """
      {
        "notification": {
          "date": "2023-03-15T14:30:00Z",
          "customer": {
            "subscriberId": "1234567890"
          },
          "order": {
            "id": "20230315000001",
            "correlationOrder": "CORR123456",
            "associatedDocument": "VTT001",
            "issue": {
              "code": 7001,
              "description": "Pendência Cancelamento por Duplicidade",
              "type": "CLIENTE",
              "observation": "Duplicate entry",
              "updateDate": "2023-03-15T15:00:00Z",
              "action": "fechar",
              "task": "Task123",
              "fieldActivity": "True",
              "reason": "Client requested cancellation"
            }
          },
          "type": "1",
          "code": "0",
          "description": "Ordem encerrada com sucesso",
          "lostEquipment": "False"
        }
      """
    When method post
    Then status 204

  Scenario Outline: Verify response codes for different scenarios
    Given path '/listener/cancelProductOrderCreateEvent'
    And request
      """
      {
        "notification": {
          "date": "2023-03-15T14:30:00Z",
          "customer": {
            "subscriberId": "<subscriberId>"
          },
          "order": {
            "id": "<orderId>",
            "correlationOrder": "CORR123456",
            "associatedDocument": "VTT001",
            "issue": {
              "code": <issueCode>,
              "description": "<issueDescription>",
              "type": "<issueType>",
              "observation": "<observation>",
              "updateDate": "2023-03-15T15:00:00Z",
              "action": "<action>",
              "task": "Task123",
              "fieldActivity": "<fieldActivity>",
              "reason": "<reason>"
            }
          },
          "type": "1",
          "code": "0",
          "description": "Ordem encerrada com sucesso",
          "lostEquipment": "False"
        }
      """
    When method post
    Then status <responseCode>

    Examples:
      | subscriberId | orderId        | issueCode | issueDescription                         | issueType | observation        | action | fieldActivity | reason                        | responseCode |
      |   1234567890 | 20230315000001 |      7001 | Pendência Cancelamento por Duplicidade   | CLIENTE   | Duplicate entry    | fechar | True          | Client requested cancellation |          204 |
      |   1234567890 | 20230315000002 |      7002 | Pendência Agendamento Futuro Obra 7 dias | TECNICA   | Future schedule    | abrir  | False         | Scheduled for future          |          400 |
      |   1234567890 | 20230315000003 |      7035 | Pendência área de Risco Momentânea       | CLIENTE   | Risk area detected | fechar | True          | Risk area momentary           |          500 |
      |   1234567890 | invalid        |      7001 | Pendência Cancelamento por Duplicidade   | CLIENTE   | Duplicate entry    | fechar | True          | Client requested cancellation |          400 |
