# ********RoostGPT********

# Test generated by RoostGPT for test vtal-karate using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /listener/productOrderStateChangeEvent_post for http method type POST 
# RoostTestHash=6f5fd9fdba
# 
# 

# ********RoostGPT********
Feature: Test APIs

  Background:
    Given def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    And url urlBase
    And configure headers = {Authorization: '#(karate.properties['AUTH_TOKEN'])'}

  Scenario Outline: Test "<name>" scenario
    Given path '/listener/productOrderStateChangeEvent'
    And request <requestBody>
    When method post
    Then status <expectedStatusCode>
    And match responseStatus == <expectedStatusCode>

    Examples:
      | read('listener_productOrderStateChangeEvent_post.csv') |
