# ********RoostGPT********

# Test generated by RoostGPT for test vtal-product-order using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /listener/productOrderCreateEvent_post for http method type POST 
# RoostTestHash=9b45f7ab6a
# 
# 

# ********RoostGPT********
Feature: Product Order Create Event By Client

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { 'Authorization': #(karate.properties['AUTH_TOKEN']), 'Content-Type': 'application/json' }

  Scenario Outline: Product Order Create Event By Client - <code> response
    Given path '/listener/productOrderCreateEvent'
    And request
      """
      {
        "notification": {
          "date": "<date>",
          "customer": {
            "subscriberId": "<subscriberId>"
          },
          "order": {
            "id": "<id>",
            "correlationOrder": "<correlationOrder>",
            "associatedDocument": "<associatedDocument>",
            "issue": {
              "code": "<issueCode>",
              "description": "<issueDescription>",
              "type": "<issueType>",
              "observation": "<issueObservation>",
              "updateDate": "<issueUpdateDate>",
              "action": "<issueAction>",
              "task": "<issueTask>",
              "fieldActivity": "<issueFieldActivity>",
              "reason": "<issueReason>"
            }
          },
          "type": "<type>",
          "code": "<code>",
          "description": "<description>",
          "lostEquipment": "<lostEquipment>",
          "resource": {
            "gponAccess": "<gponAccess>",
            "devices": {
              "device": [
                {
                  "category": "<deviceCategory>",
                  "type": "<deviceType>",
                  "description": "<deviceDescription>",
                  "state": "<deviceState>",
                  "usageState": "<deviceUsageState>",
                  "startOperatingDate": "<deviceStartOperatingDate>",
                  "resourceCharacteristic": [
                    {
                      "name": "<deviceCharName>",
                      "value": "<deviceCharValue>"
                    }
                  ]
                }
              ]
            },
            "fiberPath": {
              "items": {
                "item": [
                  {
                    "name": "<fiberPathItemName>",
                    "value": "<fiberPathItemValue>"
                  }
                ]
              }
            }
          }
        }
      }
      """
    When method POST
    Then status <responseStatus>
    And match response == <responseBody>

    Examples:
      | read('listener_productOrderCreateEvent_post.csv') |

  Scenario Outline: Product Order Create Event By Client - Error responses
    Given path '/listener/productOrderCreateEvent'
    And request
      """
      {
        "notification": {
          "date": "<date>",
          "customer": {
            "subscriberId": "<subscriberId>"
          },
          "order": {
            "id": "<id>",
            "correlationOrder": "<correlationOrder>",
            "associatedDocument": "<associatedDocument>",
            "issue": {
              "code": "<issueCode>",
              "description": "<issueDescription>",
              "type": "<issueType>",
              "observation": "<issueObservation>",
              "updateDate": "<issueUpdateDate>",
              "action": "<issueAction>",
              "task": "<issueTask>",
              "fieldActivity": "<issueFieldActivity>",
              "reason": "<issueReason>"
            }
          },
          "type": "<type>",
          "code": "<code>",
          "description": "<description>",
          "lostEquipment": "<lostEquipment>",
          "resource": {
            "gponAccess": "<gponAccess>",
            "devices": {
              "device": [
                {
                  "category": "<deviceCategory>",
                  "type": "<deviceType>",
                  "description": "<deviceDescription>",
                  "state": "<deviceState>",
                  "usageState": "<deviceUsageState>",
                  "startOperatingDate": "<deviceStartOperatingDate>",
                  "resourceCharacteristic": [
                    {
                      "name": "<deviceCharName>",
                      "value": "<deviceCharValue>"
                    }
                  ]
                }
              ]
            },
            "fiberPath": {
              "items": {
                "item": [
                  {
                    "name": "<fiberPathItemName>",
                    "value": "<fiberPathItemValue>"
                  }
                ]
              }
            }
          }
        }
      }
      """
    When method POST
    Then status <responseStatus>
    And match response == <responseBody>

    Examples:
      | read('listener_productOrderCreateEvent_post.csv') |
