# ********RoostGPT********

# Test generated by RoostGPT for test vtal-karate using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /productOrder/{order.Id}_patch for http method type PATCH 
# RoostTestHash=baabcd7d73
# 
# 

# ********RoostGPT********
Feature: Patch Product Order By Id

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url  urlBase
    * def Authorization = karate.properties['AUTH_TOKEN']
  # The Scenario title has been updated to start as "Scenario Outline", placeholders have also been modified to avoid unexpected errors.

  Scenario Outline: Patch product order by id for <order_Id>
    # Placeholder values are surrounded by {} instead of <> to avoid confusion with less than/greater than operators.
    Given path '/productOrder/{order_Id}'
    And header Authorization = '{Authorization}'
    And request <requestBody>
    When method patch
    Then status <statusCode>
    And match response == <responseBody>

    Examples:
      | read('productOrder_order.Id_patch.csv') |
      # Continue in the same format for the other examples.
