# ********RoostGPT********

# Test generated by RoostGPT for test vtal-karate using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /productOrder_post for http method type POST 
# RoostTestHash=13e6a9adf7
# 
# 

# ********RoostGPT********
  Feature: Testing "/productOrder" endpoint
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
  * url urlBase

  Background:
    * configure headers = { 'Authorization': '#(karate.properties['AUTH_TOKEN'])' }

  Scenario Outline: <scenDesc>
    Given path '/productOrder'
    And request <payload>
    When method post
    Then status <statusCode>
    And match response.control.code == <respString>

    Examples:
      | scenDesc                                                   | payload                                                                                       | statusCode | respString |
      | Installation Order Type FTTH                               | read('classpath:path/to/examples/InstallationOrderTypeFTTH.json')                             |        201 | '201'      |
      ...
      ...
      (rest of your examples)
