# ********RoostGPT********

# Test generated by RoostGPT for test vtal-api using AI Type Open AI and AI Model gpt-4o-2024-05-13
# 
# Feature file generated for /searchTimeSlot_get for http method type GET 
# RoostTestHash=0e2f009f7e
# 
# 

# ********RoostGPT********
Feature: Search Time Slot API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']

  Scenario Outline: Retrieve Search Time Slot with valid parameters
    Given path 'searchTimeSlot'
    And param addressId = <addressId>
    And param associatedDocument = <associatedDocument>
    And param startDate = <startDate>
    And param finishDate = <finishDate>
    And param orderType = <orderType>
    And param productType = <productType>
    And header Authorization = 'Bearer ' + authToken
    When method GET
    Then status 200
    And match response.control.type == 'S'
    And match response.control.code == 200
    And match response.control.message == 'OK'
    And match response.slots[*].id == '#string'
    And match response.slots[*].startDate == '#string'
    And match response.slots[*].finishDate == '#string'
    And match response.slots[*].expireIn == '#number'

    Examples:
      | read('searchTimeSlot_get.csv') |

  Scenario: Retrieve Search Time Slot with missing required parameters
    Given path 'searchTimeSlot'
    And param addressId = 17713
    And param startDate = '2021-05-21T13:00:00'
    And param orderType = 'Instalacao'
    And header Authorization = 'Bearer ' + authToken
    When method GET
    Then status 400
    And match response.control.type == 'E'
    And match response.control.code == 400
    And match response.control.message == 'Bad Request'

  Scenario: Retrieve Search Time Slot with unauthorized request
    Given path 'searchTimeSlot'
    And param addressId = 17713
    And param associatedDocument = 'VTT001'
    And param startDate = '2021-05-21T13:00:00'
    And param finishDate = '2021-06-04T13:00:00'
    And param orderType = 'Instalacao'
    And param productType = 'Banda Larga'
    When method GET
    Then status 401
    And match response.control.type == 'E'
    And match response.control.code == 401
    And match response.control.message == 'Unauthorized'

  Scenario: Retrieve Search Time Slot with forbidden access
    Given path 'searchTimeSlot'
    And param addressId = 17713
    And param associatedDocument = 'VTT001'
    And param startDate = '2021-05-21T13:00:00'
    And param finishDate = '2021-06-04T13:00:00'
    And param orderType = 'Instalacao'
    And param productType = 'Banda Larga'
    And header Authorization = 'Bearer invalid_token'
    When method GET
    Then status 403
    And match response.control.type == 'E'
    And match response.control.code == 403
    And match response.control.message == 'Forbidden - Scope Not Permitted'

  Scenario: Retrieve Search Time Slot with not found response
    Given path 'searchTimeSlot'
    And param addressId = 99999
    And param associatedDocument = 'VTT001'
    And param startDate = '2021-05-21T13:00:00'
    And param finishDate = '2021-06-04T13:00:00'
    And param orderType = 'Instalacao'
    And param productType = 'Banda Larga'
    And header Authorization = 'Bearer ' + authToken
    When method GET
    Then status 404
    And match response.control.type == 'E'
    And match response.control.code == 404
    And match response.control.message == 'Not Found'
