# ********RoostGPT********

# Test generated by RoostGPT for test api-testing-vtal using AI Type Open AI and AI Model gpt-4-turbo
# 
# ROOST_METHOD_HASH=1e25d70373
# ROOST_METHOD_SIG_HASH=894a44e205
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Trouble Ticket Escalation with Work Order and Status Update',
#   background: null,
#   rule: null,
#   scenario: {
#     title: 'Scenario: Successful Trouble Ticket Escalation with Work Order and Status Update',
#     steps: 'Given an existing trouble ticket with ID "TT001"\n' +
#       'And the trouble ticket is in "Open" status\n' +
#       'When the trouble ticket is escalated\n' +
#       'And a work order is created for the escalated trouble ticket\n' +
#       'And the trouble ticket status is updated to "In Progress"\n' +
#       'Then the trouble ticket should be escalated\n' +
#       'And a work order should be created for the escalated trouble ticket\n' +
#       'And the trouble ticket status should be updated to "In Progress"',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Trouble Ticket Escalation with Work Order and Status Update

Background:
  * def troubleTicket_v2_URL = karate.properties['TROUBLETICKET_V2_URL'] || karate.get('TROUBLETICKET_V2_URL', 'http://localhost:4010')

Scenario: Successful Trouble Ticket Escalation with Work Order and Status Update
  * url troubleTicket_v2_URL
  Given path '/troubleTicket/TT001'
  And method get
  When request {}
  Then status 200

  * match response.status == 'Open'

  * url troubleTicket_v2_URL
  Given path '/troubleTicket/TT001'
  And method patch
  And request { status: 'In Progress' }
  Then status 201

  * print 'Work order created for ticket ID: TT001'

  * url troubleTicket_v2_URL
  Given path '/troubleTicket/TT001'
  And method get
  When request {}
  Then status 200
  And match response.status == 'In Progress'

  * match response.status == 'In Progress'

  * print 'Work order validated for ticket ID: TT001'

  * match response.status == 'In Progress'
