# ********RoostGPT********

# Test generated by RoostGPT for test circle-ci-api using AI Type Claude AI and AI Model claude-sonnet-4-20250514
# 
# Feature file generated for /me_get for http method type GET 
# RoostTestHash=4f4e94f0a0
# 
# 

# ********RoostGPT********
Feature: User Information API

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * def authToken = karate.properties['Circle-Token']
    * configure headers = { Circle-Token: '#(authToken)', Accept: 'application/json' }

  Scenario: Get current user information - Success
    Given path '/me'
    When method GET
    Then status 200
    And match response == '#object'
    And match response.id == '#string'
    And match response.id == '#regex [0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
    And match response.login == '#string'
    And match response.name == '#string'

  Scenario: Get current user information - Invalid authentication
    Given path '/me'
    And configure headers = { Circle-Token: 'invalid-token', Accept: 'application/json' }
    When method GET
    Then assert responseStatus != 200
    And match response == '#object'
    And match response.message == '#string'

  Scenario: Get current user information - Missing authentication
    Given path '/me'
    And configure headers = { Accept: 'application/json' }
    When method GET
    Then assert responseStatus != 200
    And match response == '#object'
    And match response.message == '#string'

  Scenario Outline: Get current user information with different authentication scenarios
    Given path '/me'
    And configure headers = { Circle-Token: '<token>', Accept: 'application/json' }
    When method GET
    Then status <expectedStatus>
    And match response == '#object'

    Examples:
      | token         | expectedStatus |
      | valid-token   |            200 |
      | invalid-token |            401 |
      | expired-token |            401 |
      | ''            |            401 |

  Scenario: Validate response structure for successful request
    Given path '/me'
    When method GET
    Then status 200
    And match response == '#object'
    And assert karate.sizeOf(response) >= 3
    And match response.id == '#present'
    And match response.login == '#present'
    And match response.name == '#present'
    And match response.id == '#notnull'
    And match response.login == '#notnull'
    And match response.name == '#notnull'

  Scenario: Validate UUID format for user ID
    Given path '/me'
    When method GET
    Then status 200
    And match response.id == '#string'
    And assert response.id.length == 36
    And match response.id contains '-'

  Scenario: Validate user login information
    Given path '/me'
    When method GET
    Then status 200
    And match response.login == '#string'
    And assert response.login.length > 0

  Scenario: Validate user name information
    Given path '/me'
    When method GET
    Then status 200
    And match response.name == '#string'
    And assert response.name.length > 0
