# ********RoostGPT********

# Test generated by RoostGPT for test circle-ci-api using AI Type Claude AI and AI Model claude-sonnet-4-20250514
# 
# Feature file generated for /me_get for http method type GET 
# RoostTestHash=4f4e94f0a0
# 
# 

# ********RoostGPT********
Feature: User Information API

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * def authToken = karate.properties['Circle-Token']
    * configure headers = { 'Circle-Token': '#(authToken)' }

  Scenario: Get current user information - Success
    Given path '/me'
    When method GET
    Then status 200
    And match response == '#object'
    And match response.id == '#string'
    And match response.id == '#uuid'
    And match response.login == '#string'
    And match response.name == '#string'
    And match responseHeaders['content-type'][0] contains 'application/json'

  Scenario: Get current user information - Validate required fields
    Given path '/me'
    When method GET
    Then status 200
    And match response.id == '#present'
    And match response.login == '#present'
    And match response.name == '#present'

  Scenario: Get current user information - Validate field types
    Given path '/me'
    When method GET
    Then status 200
    And match response.id == '#string'
    And match response.login == '#string'
    And match response.name == '#string'

  Scenario: Get current user information - Error response
    Given path '/me'
    And configure headers = { 'Circle-Token': 'invalid-token' }
    When method GET
    Then status != 200
    And match response == '#object'
    And match response.message == '#string'
    And match responseHeaders['content-type'][0] contains 'application/json'

  Scenario: Get current user information - Missing authentication
    Given path '/me'
    And configure headers = {}
    When method GET
    Then status != 200
    And match response == '#object'
    And match response.message == '#string'
