# ********RoostGPT********

# Test generated by RoostGPT for test circle-ci-api using AI Type Claude AI and AI Model claude-sonnet-4-20250514
# 
# Feature file generated for /organization/{org-slug-or-id}/url-orb-allow-list_post for http method type POST 
# RoostTestHash=b75dae64e4
# 
# 

# ********RoostGPT********
Feature: Create URL Orb Allow-list Entry

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

  Scenario Outline: Create URL Orb allow-list entry with valid data
    Given path 'organization', '<orgSlugOrId>', 'url-orb-allow-list'
    And request
      """
      {
        "name": "<name>",
        "prefix": "<prefix>",
        "auth": "<auth>"
      }
      """
    When method POST
    Then status 200
    And match response == { id: '#string', message: '#string' }
    And match response.id == '#regex [0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
    And match response.message == '#string'
    And match response.message == '#notnull'

    Examples:
      | read('organization_org-slug-or-id_url-orb-allow-list_post.csv') |

  Scenario Outline: Create URL Orb allow-list entry with different auth types
    Given path 'organization', 'gh/CircleCI-Public', 'url-orb-allow-list'
    And request
      """
      {
        "name": "Test allow-list entry",
        "prefix": "https://example.com/orbs/",
        "auth": "<authType>"
      }
      """
    When method POST
    Then status 200
    And match response == { id: '#string', message: '#string' }
    And match response.id == '#regex [0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
    And match response.message == '#string'

    Examples:
      | read('organization_org-slug-or-id_url-orb-allow-list_post.csv') |

  Scenario: Create URL Orb allow-list entry with missing required fields
    Given path 'organization', 'gh/CircleCI-Public', 'url-orb-allow-list'
    And request
      """
      {
        "name": "Test entry"
      }
      """
    When method POST
    Then status != 200
    And match response == { message: '#string' }
    And match response.message == '#string'

  Scenario: Create URL Orb allow-list entry with empty name
    Given path 'organization', 'gh/CircleCI-Public', 'url-orb-allow-list'
    And request
      """
      {
        "name": "",
        "prefix": "https://example.com/orbs/",
        "auth": "none"
      }
      """
    When method POST
    Then status != 200
    And match response == { message: '#string' }
    And match response.message == '#string'

  Scenario: Create URL Orb allow-list entry with empty prefix
    Given path 'organization', 'gh/CircleCI-Public', 'url-orb-allow-list'
    And request
      """
      {
        "name": "Test entry",
        "prefix": "",
        "auth": "none"
      }
      """
    When method POST
    Then status != 200
    And match response == { message: '#string' }
    And match response.message == '#string'

  Scenario: Create URL Orb allow-list entry with invalid auth type
    Given path 'organization', 'gh/CircleCI-Public', 'url-orb-allow-list'
    And request
      """
      {
        "name": "Test entry",
        "prefix": "https://example.com/orbs/",
        "auth": "invalid-auth"
      }
      """
    When method POST
    Then status != 200
    And match response == { message: '#string' }
    And match response.message == '#string'

  Scenario: Create URL Orb allow-list entry with null values
    Given path 'organization', 'gh/CircleCI-Public', 'url-orb-allow-list'
    And request
      """
      {
        "name": null,
        "prefix": null,
        "auth": null
      }
      """
    When method POST
    Then status != 200
    And match response == { message: '#string' }
    And match response.message == '#string'

  Scenario: Create URL Orb allow-list entry with extra fields
    Given path 'organization', 'gh/CircleCI-Public', 'url-orb-allow-list'
    And request
      """
      {
        "name": "Test entry",
        "prefix": "https://example.com/orbs/",
        "auth": "none",
        "extraField": "should be ignored"
      }
      """
    When method POST
    Then status 200
    And match response == { id: '#string', message: '#string' }
    And match response.id == '#regex [0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
    And match response.message == '#string'

  Scenario: Create URL Orb allow-list entry with invalid organization slug
    Given path 'organization', 'invalid-org', 'url-orb-allow-list'
    And request
      """
      {
        "name": "Test entry",
        "prefix": "https://example.com/orbs/",
        "auth": "none"
      }
      """
    When method POST
    Then status != 200
    And match response == { message: '#string' }
    And match response.message == '#string'

  Scenario: Create URL Orb allow-list entry with empty request body
    Given path 'organization', 'gh/CircleCI-Public', 'url-orb-allow-list'
    And request {}
    When method POST
    Then status != 200
    And match response == { message: '#string' }
    And match response.message == '#string'

  Scenario: Create URL Orb allow-list entry with malformed JSON
    Given path 'organization', 'gh/CircleCI-Public', 'url-orb-allow-list'
    And request
      """
      {"name": "test", "prefix": "https://example.com", "auth": "none"
      """
    When method POST
    Then status != 200
    And match response == { message: '#string' }
    And match response.message == '#string'

  Scenario Outline: Create URL Orb allow-list entry with different prefix formats
    Given path 'organization', 'gh/CircleCI-Public', 'url-orb-allow-list'
    And request
      """
      {
        "name": "Test prefix format",
        "prefix": "<prefix>",
        "auth": "none"
      }
      """
    When method POST
    Then status 200
    And match response == { id: '#string', message: '#string' }
    And match response.id == '#regex [0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
    And match response.message == '#string'

    Examples:
      | read('organization_org-slug-or-id_url-orb-allow-list_post.csv') |
