# ********RoostGPT********

# Test generated by RoostGPT for test circle-ci-api using AI Type Claude AI and AI Model claude-sonnet-4-20250514
# 
# Feature file generated for /pipeline/continue_post for http method type POST 
# RoostTestHash=ebaca7e4ca
# 
# 

# ********RoostGPT********
Feature: Continue Pipeline API

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * header Content-Type = 'application/json'
    * header Authorization = 'Basic ' + karate.properties['BASIC_AUTH_TOKEN']

  Scenario: Successfully continue a pipeline with required fields only
    Given path '/pipeline/continue'
    And request
      """
      {
        "continuation-key": "test-continuation-key-123",
        "configuration": "version: 2.1\njobs:\n  build:\n    docker:\n      - image: circleci/node:10\n    steps:\n      - checkout\n      - run: echo 'Hello World'"
      }
      """
    When method POST
    Then status 200
    And match response == { message: '#string' }
    And match response.message == '#present'
    And match response.message == '#notnull'

  Scenario: Successfully continue a pipeline with all fields including parameters
    Given path '/pipeline/continue'
    And request
      """
      {
        "continuation-key": "test-continuation-key-456",
        "configuration": "version: 2.1\njobs:\n  deploy:\n    docker:\n      - image: circleci/node:12\n    steps:\n      - checkout\n      - run: echo 'Deploying'",
        "parameters": {
          "deploy_prod": true,
          "environment": "production",
          "timeout": 300
        }
      }
      """
    When method POST
    Then status 200
    And match response == { message: '#string' }
    And match response.message == '#present'
    And match response.message == '#notnull'

  Scenario Outline: Continue pipeline with different parameter types
    Given path '/pipeline/continue'
    And request
      """
      {
        "continuation-key": "<continuationKey>",
        "configuration": "<configuration>",
        "parameters": <parameters>
      }
      """
    When method POST
    Then status 200
    And match response == { message: '#string' }
    And match response.message == '#present'
    And match response.message == '#notnull'

    Examples:
      | read('pipeline_continue_post.csv') |

  Scenario: Fail to continue pipeline without continuation-key
    Given path '/pipeline/continue'
    And request
      """
      {
        "configuration": "version: 2.1\njobs:\n  build:\n    steps:\n      - run: echo test"
      }
      """
    When method POST
    Then status != 200
    And match response == { message: '#string' }
    And match response.message == '#present'

  Scenario: Fail to continue pipeline without configuration
    Given path '/pipeline/continue'
    And request
      """
      {
        "continuation-key": "test-key-789"
      }
      """
    When method POST
    Then status != 200
    And match response == { message: '#string' }
    And match response.message == '#present'

  Scenario: Fail to continue pipeline with empty continuation-key
    Given path '/pipeline/continue'
    And request
      """
      {
        "continuation-key": "",
        "configuration": "version: 2.1\njobs:\n  build:\n    steps:\n      - run: echo test"
      }
      """
    When method POST
    Then status != 200
    And match response == { message: '#string' }
    And match response.message == '#present'

  Scenario: Fail to continue pipeline with empty configuration
    Given path '/pipeline/continue'
    And request
      """
      {
        "continuation-key": "test-key-empty-config",
        "configuration": ""
      }
      """
    When method POST
    Then status != 200
    And match response == { message: '#string' }
    And match response.message == '#present'

  Scenario: Continue pipeline with empty parameters object
    Given path '/pipeline/continue'
    And request
      """
      {
        "continuation-key": "test-key-empty-params",
        "configuration": "version: 2.1\njobs:\n  build:\n    steps:\n      - run: echo test",
        "parameters": {}
      }
      """
    When method POST
    Then status 200
    And match response == { message: '#string' }
    And match response.message == '#present'
    And match response.message == '#notnull'

  Scenario: Fail to continue pipeline with invalid JSON
    Given path '/pipeline/continue'
    And request
      """
      {
        "continuation-key": "test-key",
        "configuration": "invalid json"
      }
      """
    When method POST
    Then status != 200
    And match response == { message: '#string' }
    And match response.message == '#present'

  Scenario: Continue pipeline with complex configuration
    Given path '/pipeline/continue'
    And request
      """
      {
        "continuation-key": "complex-config-key",
        "configuration": "version: 2.1\norbs:\n  node: circleci/node@4.7.0\njobs:\n  build:\n    executor: node/default\n    steps:\n      - checkout\n      - node/install-packages\n      - run: npm test\nworkflows:\n  build-and-test:\n    jobs:\n      - build",
        "parameters": {
          "node_version": "14.17.0",
          "run_tests": true,
          "cache_version": 1
        }
      }
      """
    When method POST
    Then status 200
    And match response == { message: '#string' }
    And match response.message == '#present'
    And match response.message == '#notnull'
