# ********RoostGPT********

# Test generated by RoostGPT for test circle-ci-api using AI Type Claude AI and AI Model claude-sonnet-4-20250514
# 
# Feature file generated for /project/{project-slug}/schedule_post for http method type POST 
# RoostTestHash=007057fd92
# 
# 

# ********RoostGPT********
Feature: Create Schedule API

Background:
  * def urlBase = karate.properties['URL_BASE']
  * url urlBase

Scenario Outline: Create schedule with days-of-week timetable - Success
  Given path 'project', '<project-slug>', 'schedule'
  And request
    """
    {
      "name": "<name>",
      "timetable": {
        "per-hour": <per-hour>,
        "hours-of-day": <hours-of-day>,
        "days-of-week": <days-of-week>
      },
      "attribution-actor": "<attribution-actor>",
      "parameters": <parameters>,
      "description": "<description>"
    }
    """
  When method POST
  Then status 201
  And match response.id == '#string'
  And match response.id == '#uuid'
  And match response.name == '<name>'
  And match response.description == '<description>'
  And match response.project-slug == '<project-slug>'
  And match response.created-at == '#string'
  And match response.created-at == '#? karate.match(_, "####-##-##T##:##:##.###Z").pass'
  And match response.updated-at == '#string'
  And match response.updated-at == '#? karate.match(_, "####-##-##T##:##:##.###Z").pass'
  And match response.timetable == '#object'
  And match response.timetable.per-hour == <per-hour>
  And match response.timetable.hours-of-day == <hours-of-day>
  And match response.timetable.days-of-week == <days-of-week>
  And match response.timetable.per-hour == '#number'
  And match response.timetable.per-hour == '#? _ >= 1 && _ <= 60'
  And match response.timetable.hours-of-day == '#array'
  And match each response.timetable.hours-of-day == '#number'
  And match each response.timetable.hours-of-day == '#? _ >= 0 && _ <= 24'
  And match response.timetable.days-of-week == '#array'
  And match each response.timetable.days-of-week == '#string'
  And match each response.timetable.days-of-week == '#regex (TUE|SAT|SUN|MON|THU|WED|FRI)'
  And match response.parameters == <parameters>
  And match response.parameters == '#object'
  And match response.actor == '#object'
  And match response.actor.id == '#string'
  And match response.actor.id == '#uuid'
  And match response.actor.login == '#string'
  And match response.actor.name == '#string'

Examples:
  | project-slug | name | per-hour | hours-of-day | days-of-week | attribution-actor | parameters | description |
  | gh/CircleCI-Public/api-preview-docs | Daily Build | 1 | [9, 17] | ["MON", "TUE", "WED", "THU", "FRI"] | current | {"branch": "main", "deploy_prod": false} | Daily build schedule |
  | gh/CircleCI-Public/api-preview-docs | Weekend Deploy | 2 | [10] | ["SAT", "SUN"] | system | {"branch": "release", "deploy_prod": true} | Weekend deployment |

Scenario Outline: Create schedule with days-of-month timetable - Success
  Given path 'project', '<project-slug>', 'schedule'
  And request
    """
    {
      "name": "<name>",
      "timetable": {
        "per-hour": <per-hour>,
        "hours-of-day": <hours-of-day>,
        "days-of-month": <days-of-month>,
        "months": <months>
      },
      "attribution-actor": "<attribution-actor>",
      "parameters": <parameters>,
      "description": "<description>"
    }
    """
  When method POST
  Then status 201
  And match response.id == '#string'
  And match response.id == '#uuid'
  And match response.name == '<name>'
  And match response.description == '<description>'
  And match response.project-slug == '<project-slug>'
  And match response.created-at == '#string'
  And match response.created-at == '#? karate.match(_, "####-##-##T##:##:##.###Z").pass'
  And match response.updated-at == '#string'
  And match response.updated-at == '#? karate.match(_, "####-##-##T##:##:##.###Z").pass'
  And match response.timetable == '#object'
  And match response.timetable.per-hour == <per-hour>
  And match response.timetable.hours-of-day == <hours-of-day>
  And match response.timetable.days-of-month == <days-of-month>
  And match response.timetable.months == <months>
  And match response.timetable.per-hour == '#number'
  And match response.timetable.per-hour == '#? _ >= 1 && _ <= 60'
  And match response.timetable.hours-of-day == '#array'
  And match each response.timetable.hours-of-day == '#number'
  And match each response.timetable.hours-of-day == '#? _ >= 0 && _ <= 24'
  And match response.timetable.days-of-month == '#array'
  And match each response.timetable.days-of-month == '#number'
  And match each response.timetable.days-of-month == '#? _ >= 1 && _ <= 31'
  And match response.timetable.months == '#array'
  And match each response.timetable.months == '#string'
  And match each response.timetable.months == '#regex (MAR|NOV|DEC|JUN|MAY|OCT|FEB|APR|SEP|AUG|JAN|JUL)'
  And match response.parameters == <parameters>
  And match response.parameters == '#object'
  And match response.actor == '#object'
  And match response.actor.id == '#string'
  And match response.actor.id == '#uuid'
  And match response.actor.login == '#string'
  And match response.actor.name == '#string'

Examples:
  | project-slug | name | per-hour | hours-of-day | days-of-month | months | attribution-actor | parameters | description |
  | gh/CircleCI-Public/api-preview-docs | Monthly Report | 1 | [8] | [1, 15] | ["JAN", "FEB", "MAR"] | current | {"branch": "main", "generate_report": true} | Monthly report generation |
  | gh/CircleCI-Public/api-preview-docs | Quarterly Release | 3 | [14, 16] | [31] | ["MAR", "JUN", "SEP", "DEC"] | system | {"tag": "v1.0.0", "deploy_prod": true} | Quarterly release schedule |

Scenario: Create schedule with null description - Success
  Given path 'project', 'gh/CircleCI-Public/api-preview-docs', 'schedule'
  And request
    """
    {
      "name": "Test Schedule",
      "timetable": {
        "per-hour": 1,
        "hours-of-day": [12],
        "days-of-week": ["MON"]
      },
      "attribution-actor": "current",
      "parameters": {"branch": "main"},
      "description": null
    }
    """
  When method POST
  Then status 201
  And match response.id == '#string'
  And match response.id == '#uuid'
  And match response.name == 'Test Schedule'
  And match response.description == null
  And match response.project-slug == 'gh/CircleCI-Public/api-preview-docs'
  And match response.created-at == '#string'
  And match response.updated-at == '#string'
  And match response.timetable == '#object'
  And match response.timetable.per-hour == 1
  And match response.timetable.hours-of-day == [12]
  And match response.timetable.days-of-week == ["MON"]
  And match response.parameters == {"branch": "main"}
  And match response.actor == '#object'
  And match response.actor.id == '#string'
  And match response.actor.login == '#string'
  And match response.actor.name == '#string'

Scenario Outline: Create schedule with various parameter types - Success
  Given path 'project', 'gh/CircleCI-Public/api-preview-docs', 'schedule'
  And request
    """
    {
      "name": "Parameter Test",
      "timetable": {
        "per-hour": 1,
        "hours-of-day": [10],
        "days-of-week": ["TUE"]
      },
      "attribution-actor": "current",
      "parameters": <parameters>,
      "description": "Testing different parameter types"
    }
    """
  When method POST
  Then status 201
  And match response.parameters == <parameters>
  And match response.parameters == '#object'

Examples:
  | parameters |
  | {"string_param": "test", "int_param": 42, "bool_param": true} |
  | {"branch": "feature/test", "count": 100, "enabled": false} |
  | {"tag": "v2.0.0", "timeout": 300, "debug": true} |

Scenario Outline: Create schedule with boundary values - Success
  Given path 'project', 'gh/CircleCI-Public/api-preview-docs', 'schedule'
  And request
    """
    {
      "name": "Boundary Test",
      "timetable": {
        "per-hour": <per-hour>,
        "hours-of-day": <hours-of-day>,
        "days-of-week": ["WED"]
      },
      "attribution-actor": "current",
      "parameters": {"branch": "main"},
      "description": "Testing boundary values"
    }
    """
  When method POST
  Then status 201
  And match response.timetable.per-hour == <per-hour>
  And match response.timetable.hours-of-day == <hours-of-day>

Examples:
  | per-hour | hours-of-day |
  | 1 | [0] |
  | 60 | [24] |
  | 30 | [0, 12, 24] |

Scenario: Create schedule with all months - Success
  Given path 'project', 'gh/CircleCI-Public/api-preview-docs', 'schedule'
  And request
    """
    {
      "name": "All Months Test",
      "timetable": {
        "per-hour": 1,
        "hours-of-day": [12],
        "days-of-month": [15],
        "months": ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"]
      },
      "attribution-actor": "system",
      "parameters": {"branch": "main"},
      "description": "Testing all months"
    }
    """
  When method POST
  Then status 201
  And match response.timetable.months == ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"]
  And match each response.timetable.months == '#regex (JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)'

Scenario: Create schedule with all days of week - Success
  Given path 'project', 'gh/CircleCI-Public/api-preview-docs', 'schedule'
  And request
    """
    {
      "name": "All Days Test",
      "timetable": {
        "per-hour": 2,
        "hours-of-day": [9, 17],
        "days-of-week": ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"]
      },
      "attribution-actor": "current",
      "parameters": {"branch": "develop"},
      "description": "Testing all days of week"
    }
    """
  When method POST
  Then status 201
  And match response.timetable.days-of-week == ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"]
  And match each response.timetable.days-of-week == '#regex (MON|TUE|WED|THU|FRI|SAT|SUN)'

Scenario Outline: Create schedule - Error scenarios
  Given path 'project', '<project-slug>', 'schedule'
  And request <request-body>
  When method POST
  Then status <status-code>
  And match response == '#object'
  And match response.message == '#string'

Examples:
  | project-slug | request-body | status-code |
  | invalid-project | {"name": "test", "timetable": {"per-hour": 1, "hours-of-day": [12], "days-of-week": ["MON"]}, "attribution-actor": "current", "parameters": {"branch": "main"}} | 400 |
  | gh/CircleCI-Public/api-preview-docs | {"timetable": {"per-hour": 1, "hours-of-day": [12], "days-of-week": ["MON"]}, "attribution-actor": "current", "parameters": {"branch": "main"}} | 400 |
  | gh/CircleCI-Public/api-preview-docs | {"name": "test", "attribution-actor": "current", "parameters": {"branch": "main"}} | 400 |
  | gh/CircleCI-Public/api-preview-docs | {"name": "test", "timetable": {"per-hour": 1, "hours-of-day": [12], "days-of-week": ["MON"]}, "parameters": {"branch": "main"}} | 400 |
  | gh/CircleCI-Public/api-preview-docs | {"name": "test", "timetable": {"per-hour": 1, "hours-of-day": [12], "days-of-week": ["MON"]}, "attribution-actor": "current"} | 400 |
