# ********RoostGPT********

# Test generated by RoostGPT for test circle-ci-api using AI Type Claude AI and AI Model claude-sonnet-4-20250514
# 
# Feature file generated for /project/{project-slug}/checkout-key_post for http method type POST 
# RoostTestHash=ebb0d92604
# 
# 

# ********RoostGPT********
Feature: Create a new checkout key

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

  Scenario Outline: Create checkout key with valid request
    Given path 'project', '<project-slug>', 'checkout-key'
    And request { type: '<type>' }
    When method POST
    Then status 201
    And match response.public-key == '#string'
    And match response.public-key == '#notnull'
    And match response.type == '#string'
    And match response.type == '#regex (deploy-key|github-user-key)'
    And match response.fingerprint == '#string'
    And match response.fingerprint == '#notnull'
    And match response.preferred == '#boolean'
    And match response.created-at == '#string'
    And match response.created-at == '#regex \\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}Z'
    And match response == { public-key: '#string', type: '#string', fingerprint: '#string', preferred: '#boolean', created-at: '#string' }

    Examples:
      | read('project_project-slug_checkout-key_post.csv') |

  Scenario: Create checkout key with URL-encoded project slug
    Given path 'project', 'gh%2FCircleCI-Public%2Fapi-preview-docs', 'checkout-key'
    And request { type: 'deploy-key' }
    When method POST
    Then status 201
    And match response.public-key == '#string'
    And match response.type == '#string'
    And match response.type == '#regex (deploy-key|github-user-key)'
    And match response.fingerprint == '#string'
    And match response.preferred == '#boolean'
    And match response.created-at == '#string'

  Scenario Outline: Create checkout key with invalid request body
    Given path 'project', 'gh/CircleCI-Public/api-preview-docs', 'checkout-key'
    And request <request-body>
    When method POST
    Then status != 201
    And match response.message == '#string'

    Examples:
      | request-body              |
      | {}                        |
      | { type: 'invalid-key' }   |
      | { type: '' }              |
      | { type: null }            |
      | { invalid: 'deploy-key' } |

  Scenario: Create checkout key with missing request body
    Given path 'project', 'gh/CircleCI-Public/api-preview-docs', 'checkout-key'
    When method POST
    Then status != 201
    And match response.message == '#string'

  Scenario Outline: Create checkout key with invalid project slug
    Given path 'project', '<project-slug>', 'checkout-key'
    And request { type: 'deploy-key' }
    When method POST
    Then status != 201
    And match response.message == '#string'

    Examples:
      | project-slug     |
      | invalid-slug     |
      | ''               |
      | gh/invalid       |
      | invalid/org/repo |

  Scenario: Create checkout key with malformed JSON
    Given path 'project', 'gh/CircleCI-Public/api-preview-docs', 'checkout-key'
    And header Content-Type = 'application/json'
    And request '{ type: deploy-key }'
    When method POST
    Then status != 201
    And match response.message == '#string'

  Scenario: Verify response structure for deploy-key type
    Given path 'project', 'gh/CircleCI-Public/api-preview-docs', 'checkout-key'
    And request { type: 'deploy-key' }
    When method POST
    Then status 201
    And match response contains { public-key: '#string', type: '#string', fingerprint: '#string', preferred: '#boolean', created-at: '#string' }
    And match response.type == '#regex (deploy-key|github-user-key)'
    And match response.public-key contains 'ssh-'
    And match response.fingerprint contains ':'
    And match response.created-at != ''

  Scenario: Verify response structure for user-key type
    Given path 'project', 'gh/CircleCI-Public/api-preview-docs', 'checkout-key'
    And request { type: 'user-key' }
    When method POST
    Then status 201
    And match response contains { public-key: '#string', type: '#string', fingerprint: '#string', preferred: '#boolean', created-at: '#string' }
    And match response.type == '#regex (deploy-key|github-user-key)'
    And match response.public-key contains 'ssh-'
    And match response.fingerprint contains ':'
    And match response.created-at != ''

  Scenario: Create checkout key and validate all required fields are present
    Given path 'project', 'gh/CircleCI-Public/api-preview-docs', 'checkout-key'
    And request { type: 'deploy-key' }
    When method POST
    Then status 201
    And match response.public-key == '#present'
    And match response.type == '#present'
    And match response.fingerprint == '#present'
    And match response.preferred == '#present'
    And match response.created-at == '#present'
    And match response.public-key != null
    And match response.type != null
    And match response.fingerprint != null
    And match response.preferred != null
    And match response.created-at != null

  Scenario: Create checkout key with additional properties in request
    Given path 'project', 'gh/CircleCI-Public/api-preview-docs', 'checkout-key'
    And request { type: 'deploy-key', extra: 'property', another: 'field' }
    When method POST
    Then status 201
    And match response.public-key == '#string'
    And match response.type == '#string'
    And match response.fingerprint == '#string'
    And match response.preferred == '#boolean'
    And match response.created-at == '#string'
