# ********RoostGPT********

# Test generated by RoostGPT for test circle-ci-api using AI Type Claude AI and AI Model claude-sonnet-4-20250514
# 
# Feature file generated for /project/{project-slug}/envvar_post for http method type POST 
# RoostTestHash=9ce923d63b
# 
# 

# ********RoostGPT********
Feature: Create Environment Variable API

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * header Content-Type = 'application/json'
    * header Authorization = 'Basic ' + karate.properties['API_TOKEN']

  Scenario Outline: Create environment variable with valid data
    Given path 'project', '<project-slug>', 'envvar'
    And request
      """
      {
        "name": "<name>",
        "value": "<value>"
      }
      """
    When method POST
    Then status 201
    And match response ==
      """
      {
        "name": "#string",
        "value": "#string",
        "created-at": "#? _ == null || karate.typeOf(_) == 'string'"
      }
      """
    And match response.name == '<name>'
    And match response.value == '<value>'
    And match response.name == '#notnull'
    And match response.value == '#notnull'

    Examples:
      | read('project_project-slug_envvar_post.csv') |

  Scenario: Create environment variable with minimal required fields
    Given path 'project', 'gh/CircleCI-Public/api-preview-docs', 'envvar'
    And request
      """
      {
        "name": "MINIMAL_VAR",
        "value": "minimal_value"
      }
      """
    When method POST
    Then status 201
    And match response ==
      """
      {
        "name": "#string",
        "value": "#string",
        "created-at": "#? _ == null || karate.typeOf(_) == 'string'"
      }
      """
    And match response.name == 'MINIMAL_VAR'
    And match response.value == 'minimal_value'
    And assert response.name.length > 0
    And assert response.value.length > 0

  Scenario: Create environment variable with special characters in name and value
    Given path 'project', 'gh/CircleCI-Public/api-preview-docs', 'envvar'
    And request
      """
      {
        "name": "TEST_VAR_123",
        "value": "value!@#$%^&*()_+-={}[]|\\:\";'<>?,./"
      }
      """
    When method POST
    Then status 201
    And match response ==
      """
      {
        "name": "#string",
        "value": "#string",
        "created-at": "#? _ == null || karate.typeOf(_) == 'string'"
      }
      """
    And match response.name == 'TEST_VAR_123'
    And match response.value == 'value!@#$%^&*()_+-={}[]|\\:\";\'<>?,./'

  Scenario: Create environment variable with empty string value
    Given path 'project', 'gh/CircleCI-Public/api-preview-docs', 'envvar'
    And request
      """
      {
        "name": "EMPTY_VAR",
        "value": ""
      }
      """
    When method POST
    Then status 201
    And match response ==
      """
      {
        "name": "#string",
        "value": "#string",
        "created-at": "#? _ == null || karate.typeOf(_) == 'string'"
      }
      """
    And match response.name == 'EMPTY_VAR'
    And match response.value == ''

  Scenario: Create environment variable with long name and value
    Given path 'project', 'gh/CircleCI-Public/api-preview-docs', 'envvar'
    And request
      """
      {
        "name": "VERY_LONG_ENVIRONMENT_VARIABLE_NAME_FOR_TESTING_PURPOSES",
        "value": "very_long_environment_variable_value_for_testing_purposes_that_contains_multiple_words_and_characters"
      }
      """
    When method POST
    Then status 201
    And match response ==
      """
      {
        "name": "#string",
        "value": "#string",
        "created-at": "#? _ == null || karate.typeOf(_) == 'string'"
      }
      """
    And match response.name == 'VERY_LONG_ENVIRONMENT_VARIABLE_NAME_FOR_TESTING_PURPOSES'
    And match response.value == 'very_long_environment_variable_value_for_testing_purposes_that_contains_multiple_words_and_characters'

  Scenario Outline: Create environment variable with URL-encoded project slug
    Given path 'project', '<encoded-project-slug>', 'envvar'
    And request
      """
      {
        "name": "<name>",
        "value": "<value>"
      }
      """
    When method POST
    Then status 201
    And match response ==
      """
      {
        "name": "#string",
        "value": "#string",
        "created-at": "#? _ == null || karate.typeOf(_) == 'string'"
      }
      """
    And match response.name == '<name>'
    And match response.value == '<value>'

    Examples:
      | read('project_project-slug_envvar_post.csv') |

  Scenario Outline: Attempt to create environment variable with missing required fields
    Given path 'project', 'gh/CircleCI-Public/api-preview-docs', 'envvar'
    And request <request-body>
    When method POST
    Then status != 201
    And match response ==
      """
      {
        "message": "#string"
      }
      """
    And match response.message == '#notnull'
    And assert response.message.length > 0

    Examples:
      | request-body              |
      | { "name": "TEST_VAR" }    |
      | { "value": "test_value" } |
      | {}                        |

  Scenario: Attempt to create environment variable with null values
    Given path 'project', 'gh/CircleCI-Public/api-preview-docs', 'envvar'
    And request
      """
      {
        "name": null,
        "value": null
      }
      """
    When method POST
    Then status != 201
    And match response ==
      """
      {
        "message": "#string"
      }
      """
    And match response.message == '#notnull'

  Scenario: Attempt to create environment variable with invalid project slug
    Given path 'project', 'invalid-project-slug', 'envvar'
    And request
      """
      {
        "name": "TEST_VAR",
        "value": "test_value"
      }
      """
    When method POST
    Then status != 201
    And match response ==
      """
      {
        "message": "#string"
      }
      """
    And match response.message == '#notnull'

  Scenario: Create environment variable and verify response structure
    Given path 'project', 'gh/CircleCI-Public/api-preview-docs', 'envvar'
    And request
      """
      {
        "name": "STRUCTURE_TEST",
        "value": "structure_value"
      }
      """
    When method POST
    Then status 201
    And match response == '#object'
    And match response.name == '#string'
    And match response.value == '#string'
    And match response.created-at == '#? _ == null || karate.typeOf(_) == "string"'
    And assert karate.sizeOf(response) >= 2
    And assert karate.sizeOf(response) <= 3

  Scenario: Create environment variable with numeric-like string values
    Given path 'project', 'gh/CircleCI-Public/api-preview-docs', 'envvar'
    And request
      """
      {
        "name": "12345",
        "value": "67890"
      }
      """
    When method POST
    Then status 201
    And match response ==
      """
      {
        "name": "#string",
        "value": "#string",
        "created-at": "#? _ == null || karate.typeOf(_) == 'string'"
      }
      """
    And match response.name == '12345'
    And match response.value == '67890'
    And match karate.typeOf(response.name) == 'string'
    And match karate.typeOf(response.value) == 'string'
