# ********RoostGPT********

# Test generated by RoostGPT for test testing-project-path-error using AI Type Azure Open AI and AI Model gpt-4o
# 
# Feature file generated for /appointment/{appointmentId}_get for http method type GET 
# RoostTestHash=972c444da4
# 
# 

# ********RoostGPT********
Feature: Retrieve Appointment API Tests
  This feature file comprehensively tests the Retrieve Appointment API endpoint.

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * header Accept = 'application/json'
    * header Authorization = 'Bearer {{$processEnvironment.AUTH_TOKEN}}'

  Scenario Outline: Test successful retrieval of an appointment
    Given path 'appointment', <appointmentId>
    When method GET
    Then status 200
    And match response.appointments.id == '#string'
    And match response.appointments.location == """
    {
      "recursive_property": "some_value"
    }
    """

    Examples:
      | appointmentId  |
      | ['123']        |
      | ['456']        |
      | ['789']        |
