# ********RoostGPT********

# Test generated by RoostGPT for test testing-project-path-error using AI Type Azure Open AI and AI Model gpt-4o
# 
# Feature file generated for /appointmentConfirmation_post for http method type POST 
# RoostTestHash=1705b22338
# 
# 

# ********RoostGPT********
Feature: Appointment Confirmation API Tests

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * header Accept = 'application/json'
    * header Authorization = $processEnvironment.AUTH_TOKEN

  Scenario: Validate successful appointment confirmation
    Given path 'appointmentConfirmation'
    And request
      """
      {
        "appointment": {
          "confirmation": true,
          "id": "SA-562403"
        },
        "customer": {
          "subscriberId": "VTAL001"
        }
      }
      """
    When method POST
    Then status 200
    And match response.control.code == '200'
    And match response.control.message == '#string'
    And match response.control.type == '#string'

  Scenario Outline: Validate Bad Request with invalid inputs
    Given path 'appointmentConfirmation'
    And request
      """
      {
        "appointment": {
          "confirmation": <confirmation>,
          "id": <appointmentId>
        },
        "customer": {
          "subscriberId": <subscriberId>
        }
      }
      """
    When method POST
    Then status 400
    And match response.control.code == '400'
    And match response.control.message == '#string'
    And match response.control.type == '#string'

    Examples:
      | confirmation | appointmentId         | subscriberId |
      | null         | "SA-562403"           | 'VTAL001'    |
      | true         | ""                    | 'VTAL001'    |
      | true         | "SA-1234567890123456" | 'VTAL001'    |

  Scenario Outline: Validate Unauthorized responses
    Given path 'appointmentConfirmation'
    And request
      """
      {
        "appointment": {
          "confirmation": true,
          "id": "SA-562403"
        },
        "customer": {
          "subscriberId": "VTAL001"
        }
      }
      """
    And header Authorization = <authHeader>
    When method POST
    Then status 401
    And match response.control.code == '401'
    And match response.control.message == '#string'
    And match response.control.type == '#string'

    Examples:
      | authHeader            |
      | null                  |
      | 'Bearer invalidToken' |

  Scenario: Validate Forbidden response for invalid scope
    Given path 'appointmentConfirmation'
    And request
      """
      {
        "appointment": {
          "confirmation": true,
          "id": "SA-562403"
        },
        "customer": {
          "subscriberId": "VTAL001"
        }
      }
      """
    When method POST
    Then status 403
    And match response.control.code == '403'
    And match response.control.message == '#string'
    And match response.control.type == '#string'

  Scenario: Validate Not Found response
    Given path 'nonexistentEndpoint'
    When method POST
    Then status 404
    And match response.control.code == '404'
    And match response.control.message == '#string'
    And match response.control.type == '#string'

  Scenario: Validate response for Too Many Requests
    Given path 'appointmentConfirmation'
    And request
      """
      {
        "appointment": {
          "confirmation": true,
          "id": "SA-562403"
        },
        "customer": {
          "subscriberId": "VTAL001"
        }
      }
      """
    When method POST
    Then status 429
    And match response.control.code == '429'
    And match response.control.message == '#string'
    And match response.control.type == '#string'

  Scenario: Validate Internal Server Error response
    Given path 'appointmentConfirmation'
    And request
      """
      {
        "appointment": {
          "confirmation": true,
          "id": "SA-562403"
        },
        "customer": {
          "subscriberId": null
        }
      }
      """
    When method POST
    Then status 500
    And match response.control.code == '500'
    And match response.control.message == '#string'
    And match response.control.type == '#string'

  Scenario: Validate Service Unavailable response
    Given path 'appointmentConfirmation'
    And request
      """
      {
        "appointment": {
          "confirmation": true,
          "id": "SA-562403"
        },
        "customer": {
          "subscriberId": "VTAL001"
        }
      }
      """
    When method POST
    Then status 503
    And match response.control.code == '503'
    And match response.control.message == '#string'
    And match response.control.type == '#string'
