# ********RoostGPT********

# Test generated by RoostGPT for test testing-project-path-error using AI Type Azure Open AI and AI Model gpt-4o
# 
# Feature file generated for /searchTimeSlot_get for http method type GET 
# RoostTestHash=3ba2ac6502
# 
# 

# ********RoostGPT********
Feature: Retrieve Search Time Slot API

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * header Accept = 'application/json'
    * header Authorization = 'Bearer {{$processEnvironment.AUTH_TOKEN}}'

  @Regression
  Scenario Outline: Validate successful response when retrieving search time slots
    Given path 'searchTimeSlot'
    And param addressId = <addressId>
    And param associatedDocument = <associatedDocument>
    And param startDate = <startDate>
    And param finishDate = <finishDate>
    And param orderType = <orderType>
    And param subscriberId = <subscriberId>
    And param productType = <productType>
    And param addressChangeFlag = <addressChangeFlag>
    And param priorityFlag = <priorityFlag>
    And param priorityReason = <priorityReason>
    When method GET
    Then status 200
    And match response.control.code == '#string'
    And match response.control.message == '#string'
    And match response.control.type == '#string'
    And match response.slots == '#? _ == null || typeof _ == "array"'
    And match each response.slots[*].expireIn == '#number'
    And match each response.slots[*].finishDate == '#string'
    And match each response.slots[*].id == '#string'
    And match each response.slots[*].startDate == '#string'

    Examples:
      | read('searchTimeSlot_get.csv') |

  @Regression
  Scenario: Validate response for missing mandatory parameters
    Given path 'searchTimeSlot'
    And param subscriberId = 'VTAL001'
    When method GET
    Then status 400
    And match response.control.code == '#string'
    And match response.control.message == '#string'
    And match response.control.type == '#string'

  @Regression
  Scenario Outline: Validate unauthorized access - Priority scheduling
    Given path 'searchTimeSlot'
    And param addressId = <addressId>
    And param associatedDocument = <associatedDocument>
    And param startDate = <startDate>
    And param finishDate = <finishDate>
    And param orderType = <orderType>
    And param priorityFlag = true
    When method GET
    Then status 401
    And match response.control.code == '#string'
    And match response.control.message == '#string'
    And match response.control.type == '#string'

    Examples:
      | addressId | associatedDocument | startDate             | finishDate            | orderType    |
      |     17713 | 'VTT001'           | '2021-05-21T13:00:00' | '2021-06-04T13:00:00' | 'Instalação' |

  @Regression
  Scenario Outline: Validate forbidden access due to invalid credentials
    Given path 'searchTimeSlot'
    And param addressId = <addressId>
    And param associatedDocument = <associatedDocument>
    And param startDate = <startDate>
    And param finishDate = <finishDate>
    And param orderType = <orderType>
    When method GET
    Then status 403
    And match response.control.code == '#string'
    And match response.control.message == '#string'
    And match response.control.type == '#string'

    Examples:
      | addressId | associatedDocument | startDate             | finishDate            | orderType        |
      |     17713 | 'VTT001'           | '2021-05-21T13:00:00' | '2021-06-04T13:00:00' | 'ChamadoTecnico' |

  @Regression
  Scenario: Validate response for invalid endpoint path
    Given path 'invalidEndpoint'
    When method GET
    Then status 404
    And match response.control.code == '#string'
    And match response.control.message == '#string'
    And match response.control.type == '#string'

  @Regression
  Scenario: Validate response for too many requests
    Given path 'searchTimeSlot'
    And param addressId = 17713
    And param associatedDocument = 'VTT001'
    And param startDate = '2021-05-21T13:00:00'
    And param finishDate = '2021-06-04T13:00:00'
    And param orderType = 'Instalação'
    When method GET
    Then status 429
    And match response.control.code == '#string'
    And match response.control.message == '#string'
    And match response.control.type == '#string'
