# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /actions/actions/{actionId}/versions/{id}/deploy_post for http method type POST 
# RoostTestHash=820674f904
# 
# 

# ********RoostGPT********
Feature: Deploy Action Version

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Roll back to a previous action version
    Given path 'actions', 'actions', '<actionId>', 'versions', '<id>', 'deploy'
    And request
      """
      { "update_draft": <updateDraft> }
      """
    When method POST
    Then status 202
    And match response == '#object'
    And match response.id == '#string'
    And match response.action_id == '#string'
    And match response.code == '#string'
    And match response.dependencies == '#array'
    And match response.deployed == '#boolean'
    And match response.runtime == '#string'
    And match response.secrets == '#array'
    And match response.status == '#string'
    And match response.number == '#number'
    And match response.errors == '#array'
    And match response.action == '#object'
    And match response.all_changes_deployed == '#boolean'
    And match response.created_at == '#string'
    And match response.updated_at == '#string'
    And match response.built_at == '#string'
    And match response.supported_triggers == '#array'

    Examples:
      | read('actions_actions_actionId_versions_id_deploy_post.csv') |

  Scenario: Invalid Request Body
    Given path 'actions', 'actions', 'invalidActionId', 'versions', 'invalidId', 'deploy'
    And request
      """
      { "update_draft": true }
      """
    When method POST
    Then status 400

  Scenario: Invalid token
    * configure headers = { Authorization: 'Bearer invalidToken' }
    Given path 'actions', 'actions', '910b1053-577f-4d81-a8c8-020e7319a38a', 'versions', '12a3b9e6-06e6-4a29-96bf-90c82fe79a0d', 'deploy'
    And request
      """
      { "update_draft": false }
      """
    When method POST
    Then status 401

  Scenario: Insufficient scope
    * configure headers = { Authorization: 'Bearer insufficientScopeToken' }
    Given path 'actions', 'actions', '910b1053-577f-4d81-a8c8-020e7319a38a', 'versions', '12a3b9e6-06e6-4a29-96bf-90c82fe79a0d', 'deploy'
    And request
      """
      { "update_draft": false }
      """
    When method POST
    Then status 403

  Scenario: Too many requests
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    Given path 'actions', 'actions', '910b1053-577f-4d81-a8c8-020e7319a38a', 'versions', '12a3b9e6-06e6-4a29-96bf-90c82fe79a0d', 'deploy'
    And request
      """
      { "update_draft": false }
      """
    When method POST
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'
