# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /actions/actions/{actionId}/versions_get for http method type GET 
# RoostTestHash=6b94d36429
# 
# 

# ********RoostGPT********
Feature: Retrieve Action Versions
  Retrieve all versions of a specific action using the provided action ID.

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Get Action Versions with Valid Parameters
    Given path 'actions', '<actionId>', 'versions'
    And param page = <page>
    And param per_page = <per_page>
    When method GET
    Then status 200
    And match response.total == '#number'
    And match response.page == '#number'
    And match response.per_page == '#number'
    And match response.versions == '#[]'
    And match response.versions[*].id == '#string'
    And match response.versions[*].action_id == '#string'
    And match response.versions[*].code == '#string'
    And match response.versions[*].dependencies == '#[]'
    And match response.versions[*].dependencies[*].name == '#string'
    And match response.versions[*].dependencies[*].version == '#string'
    And match response.versions[*].dependencies[*].registry_url == '#string?'
    And match response.versions[*].deployed == '#boolean'
    And match response.versions[*].runtime == '#string'
    And match response.versions[*].secrets == '#[]'
    And match response.versions[*].secrets[*].name == '#string'
    And match response.versions[*].secrets[*].updated_at == '#string'
    And match response.versions[*].status == '#string'
    And match response.versions[*].number == '#number'
    And match response.versions[*].errors == '#[]'
    And match response.versions[*].errors[*].id == '#string'
    And match response.versions[*].errors[*].msg == '#string'
    And match response.versions[*].errors[*].url == '#string'
    And match response.versions[*].action.id == '#string'
    And match response.versions[*].action.name == '#string'
    And match response.versions[*].action.supported_triggers == '#[]'
    And match response.versions[*].action.supported_triggers[*].id == '#string'
    And match response.versions[*].action.supported_triggers[*].version == '#string'
    And match response.versions[*].action.supported_triggers[*].status == '#string'
    And match response.versions[*].action.supported_triggers[*].runtimes == '#[]'
    And match response.versions[*].action.supported_triggers[*].default_runtime == '#string'
    And match response.versions[*].action.supported_triggers[*].compatible_triggers == '#[]'
    And match response.versions[*].action.supported_triggers[*].compatible_triggers[*].id == '#string'
    And match response.versions[*].action.supported_triggers[*].compatible_triggers[*].version == '#string'
    And match response.versions[*].action.supported_triggers[*].binding_policy == '#string'
    And match response.versions[*].all_changes_deployed == '#boolean'
    And match response.versions[*].created_at == '#string'
    And match response.versions[*].updated_at == '#string'
    And match response.versions[*].built_at == '#string'
    And match response.versions[*].supported_triggers == '#[]'
    And match response.versions[*].supported_triggers[*].id == '#string'
    And match response.versions[*].supported_triggers[*].version == '#string'
    And match response.versions[*].supported_triggers[*].status == '#string'
    And match response.versions[*].supported_triggers[*].runtimes == '#[]'
    And match response.versions[*].supported_triggers[*].default_runtime == '#string'
    And match response.versions[*].supported_triggers[*].compatible_triggers == '#[]'
    And match response.versions[*].supported_triggers[*].compatible_triggers[*].id == '#string'
    And match response.versions[*].supported_triggers[*].compatible_triggers[*].version == '#string'
    And match response.versions[*].supported_triggers[*].binding_policy == '#string'

    Examples:
      | read('actions_actions_actionId_versions_get.csv') |

  Scenario: Invalid Request URI
    Given path 'actions', 'invalid-action-id', 'versions'
    When method GET
    Then status 400

  Scenario: Invalid Token
    * configure headers = { Authorization: 'Bearer invalid_token' }
    Given path 'actions', '910b1053-577f-4d81-a8c8-020e7319a38a', 'versions'
    When method GET
    Then status 401

  Scenario: Insufficient Scope
    * configure headers = { Authorization: 'Bearer insufficient_scope_token' }
    Given path 'actions', '910b1053-577f-4d81-a8c8-020e7319a38a', 'versions'
    When method GET
    Then status 403

  Scenario: Too Many Requests
    Given path 'actions', '910b1053-577f-4d81-a8c8-020e7319a38a', 'versions'
    When method GET
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'
