# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /actions/actions/{id}_get for http method type GET 
# RoostTestHash=bf0721b497
# 
# 

# ********RoostGPT********
Feature: Actions API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Retrieve an action by ID
    Given path 'actions/actions/<id>'
    When method GET
    Then status <status>
    And match response == '#object'
    And match response.id == '#string'
    And match response.name == '#string'
    And match response.supported_triggers == '#array'
    And match response.all_changes_deployed == '#boolean'
    And match response.created_at == '#string'
    And match response.updated_at == '#string'
    And match response.code == '#string'
    And match response.dependencies == '#array'
    And match response.runtime == '#string'
    And match response.secrets == '#array'
    And match response.deployed_version == '#object'
    And match response.installed_integration_id == '#string'
    And match response.integration == '#object'
    And match response.status == '#string'
    And match response.built_at == '#string'
    And match response.deploy == '#boolean'

    Examples:
      | id                                   | status |
      | 910b1053-577f-4d81-a8c8-020e7319a38a |    200 |
      | invalid-id                           |    404 |

  Scenario: Invalid request URI
    Given path 'actions/actions/invalid-id'
    When method GET
    Then status 400

  Scenario: Invalid token
    * configure headers = { Authorization: 'Bearer invalid-token' }
    Given path 'actions/actions/910b1053-577f-4d81-a8c8-020e7319a38a'
    When method GET
    Then status 401

  Scenario: Insufficient scope
    * configure headers = { Authorization: 'Bearer insufficient-scope-token' }
    Given path 'actions/actions/910b1053-577f-4d81-a8c8-020e7319a38a'
    When method GET
    Then status 403

  Scenario: Too many requests
    Given path 'actions/actions/910b1053-577f-4d81-a8c8-020e7319a38a'
    When method GET
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'
