# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /actions/actions/{id}_patch for http method type PATCH 
# RoostTestHash=d7e6cfb787
# 
# 

# ********RoostGPT********
Feature: Update an Action API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Update an action with valid payload
    Given path 'actions/actions/<id>'
    And request
      """
      { 
        "name": "<name>", 
        "supported_triggers": [ 
          { 
            "id": "<trigger_id>", 
            "version": "<trigger_version>", 
            "status": "<trigger_status>", 
            "runtimes": <trigger_runtimes>, 
            "default_runtime": "<default_runtime>", 
            "compatible_triggers": [ 
              { 
                "id": "<compatible_id>", 
                "version": "<compatible_version>" 
              } 
            ], 
            "binding_policy": "<binding_policy>" 
          } 
        ], 
        "code": "<code>", 
        "dependencies": [ 
          { 
            "name": "<dependency_name>", 
            "version": "<dependency_version>", 
            "registry_url": "<registry_url>" 
          } 
        ], 
        "runtime": "<runtime>", 
        "secrets": [ 
          { 
            "name": "<secret_name>", 
            "value": "<secret_value>" 
          } 
        ] 
      }
      """
    When method PATCH
    Then status 200
    And match response.id == '<id>'
    And match response.name == '<name>'
    And match response.supported_triggers == '#[] object'
    And match response.all_changes_deployed == '#boolean'
    And match response.created_at == '#string'
    And match response.updated_at == '#string'
    And match response.code == '<code>'
    And match response.dependencies == '#[] object'
    And match response.runtime == '<runtime>'
    And match response.secrets == '#[] object'
    And match response.deployed_version == '#object'
    And match response.installed_integration_id == '#string'
    And match response.integration == '#object'
    And match response.status == '#string'
    And match response.built_at == '#string'
    And match response.deploy == '#boolean'

    Examples:
      | read('actions_actions_id_patch.csv') |

  Scenario: Invalid Request Body
    Given path 'actions/actions/invalid-id'
    And request
      """
      { "invalid": "data" }
      """
    When method PATCH
    Then status 400

  Scenario: Invalid token
    * configure headers = { Authorization: 'Bearer invalid_token' }
    Given path 'actions/actions/910b1053-577f-4d81-a8c8-020e7319a38a'
    And request
      """
      { "name": "my-action" }
      """
    When method PATCH
    Then status 401

  Scenario: Insufficient scope
    * configure headers = { Authorization: 'Bearer insufficient_scope_token' }
    Given path 'actions/actions/910b1053-577f-4d81-a8c8-020e7319a38a'
    And request
      """
      { "name": "my-action" }
      """
    When method PATCH
    Then status 403

  Scenario: Action not found
    Given path 'actions/actions/nonexistent-id'
    And request
      """
      { "name": "my-action" }
      """
    When method PATCH
    Then status 404

  Scenario: Too many requests
    * configure headers = { Authorization: 'Bearer rate_limit_token' }
    Given path 'actions/actions/910b1053-577f-4d81-a8c8-020e7319a38a'
    And request
      """
      { "name": "my-action" }
      """
    When method PATCH
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'
