# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /actions/actions_get for http method type GET 
# RoostTestHash=be67be9211
# 
# 

# ********RoostGPT********
Feature: Actions API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Retrieve all actions with valid parameters
    Given path 'actions/actions'
    And param triggerId = '<triggerId>'
    And param actionName = '<actionName>'
    And param deployed = <deployed>
    And param page = <page>
    And param per_page = <per_page>
    And param installed = <installed>
    When method GET
    Then status 200
    And match response == '#object'
    And match response.total == '#number'
    And match response.page == '#number'
    And match response.per_page == '#number'
    And match response.actions == '#array'
    And match response.actions[*].id == '#string'
    And match response.actions[*].name == '#string'
    And match response.actions[*].supported_triggers == '#array'
    And match response.actions[*].supported_triggers[*].id == '#string'
    And match response.actions[*].supported_triggers[*].version == '#string?'
    And match response.actions[*].supported_triggers[*].status == '#string?'
    And match response.actions[*].supported_triggers[*].runtimes == '#array?'
    And match response.actions[*].supported_triggers[*].default_runtime == '#string?'
    And match response.actions[*].supported_triggers[*].compatible_triggers == '#array?'
    And match response.actions[*].supported_triggers[*].binding_policy == '#string?'
    And match response.actions[*].all_changes_deployed == '#boolean'
    And match response.actions[*].created_at == '#string'
    And match response.actions[*].updated_at == '#string'
    And match response.actions[*].code == '#string'
    And match response.actions[*].dependencies == '#array'
    And match response.actions[*].dependencies[*].name == '#string'
    And match response.actions[*].dependencies[*].version == '#string'
    And match response.actions[*].dependencies[*].registry_url == '#string?'
    And match response.actions[*].runtime == '#string'
    And match response.actions[*].secrets == '#array'
    And match response.actions[*].secrets[*].name == '#string'
    And match response.actions[*].secrets[*].updated_at == '#string'
    And match response.actions[*].deployed_version == '#object?'
    And match response.actions[*].installed_integration_id == '#string'
    And match response.actions[*].integration == '#object'
    And match response.actions[*].integration.id == '#string'
    And match response.actions[*].integration.catalog_id == '#string'
    And match response.actions[*].integration.url_slug == '#string'
    And match response.actions[*].integration.partner_id == '#string'
    And match response.actions[*].integration.name == '#string'
    And match response.actions[*].integration.description == '#string'
    And match response.actions[*].integration.short_description == '#string'
    And match response.actions[*].integration.logo == '#string?'
    And match response.actions[*].integration.feature_type == '#string'
    And match response.actions[*].integration.terms_of_use_url == '#string?'
    And match response.actions[*].integration.privacy_policy_url == '#string?'
    And match response.actions[*].integration.public_support_link == '#string?'
    And match response.actions[*].integration.current_release == '#object?'
    And match response.actions[*].integration.semver == '#object?'
    And match response.actions[*].integration.required_secrets == '#array?'
    And match response.actions[*].integration.required_configuration == '#array?'
    And match response.actions[*].integration.created_at == '#string'
    And match response.actions[*].integration.updated_at == '#string'
    And match response.actions[*].status == '#string'
    And match response.actions[*].built_at == '#string'
    And match response.actions[*].deploy == '#boolean'

    Examples:
      | read('actions_actions_get.csv') |

  Scenario: Invalid request URI
    Given path 'actions/actions'
    And param actionName = 'invalid-action'
    When method GET
    Then status 400

  Scenario: Invalid token
    * configure headers = { Authorization: 'Bearer invalid_token' }
    Given path 'actions/actions'
    When method GET
    Then status 401

  Scenario: Insufficient scope
    * configure headers = { Authorization: 'Bearer insufficient_scope_token' }
    Given path 'actions/actions'
    When method GET
    Then status 403

  Scenario: Too many requests
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    Given path 'actions/actions'
    When method GET
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'
