# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /actions/actions/{actionId}/versions/{id}_get for http method type GET 
# RoostTestHash=45a4aac603
# 
# 

# ********RoostGPT********
Feature: Retrieve a specific version of an action

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Retrieve action version with valid actionId and versionId
    Given path 'actions', '<actionId>', 'versions', '<id>'
    When method GET
    Then status 200
    And match response == '#object'
    And match response.id == '#string'
    And match response.action_id == '#string'
    And match response.code == '#string'
    And match response.dependencies == '#array'
    And match response.dependencies[*].name == '#string'
    And match response.dependencies[*].version == '#string'
    And match response.dependencies[*].registry_url == '#string?'
    And match response.deployed == '#boolean'
    And match response.runtime == '#string'
    And match response.secrets == '#array'
    And match response.secrets[*].name == '#string'
    And match response.secrets[*].updated_at == '#string'
    And match response.status == '#string'
    And match response.number == '#number'
    And match response.errors == '#array'
    And match response.errors[*].id == '#string'
    And match response.errors[*].msg == '#string'
    And match response.errors[*].url == '#string'
    And match response.action == '#object'
    And match response.action.id == '#string'
    And match response.action.name == '#string'
    And match response.action.supported_triggers == '#array'
    And match response.action.supported_triggers[*].id == '#string'
    And match response.action.supported_triggers[*].version == '#string'
    And match response.action.supported_triggers[*].status == '#string'
    And match response.action.supported_triggers[*].runtimes == '#array'
    And match response.action.supported_triggers[*].default_runtime == '#string'
    And match response.action.supported_triggers[*].compatible_triggers == '#array'
    And match response.action.supported_triggers[*].binding_policy == '#string'
    And match response.all_changes_deployed == '#boolean'
    And match response.created_at == '#string'
    And match response.updated_at == '#string'
    And match response.built_at == '#string'
    And match response.supported_triggers == '#array'
    And match response.supported_triggers[*].id == '#string'
    And match response.supported_triggers[*].version == '#string'
    And match response.supported_triggers[*].status == '#string'
    And match response.supported_triggers[*].runtimes == '#array'
    And match response.supported_triggers[*].default_runtime == '#string'
    And match response.supported_triggers[*].compatible_triggers == '#array'
    And match response.supported_triggers[*].binding_policy == '#string'

    Examples:
      | read('actions_actions_actionId_versions_id_get.csv') |

  Scenario: Invalid request URI
    Given path 'actions', 'invalidActionId', 'versions', 'invalidId'
    When method GET
    Then status 400

  Scenario: Invalid token
    * configure headers = { Authorization: 'Bearer invalidToken' }
    Given path 'actions', '910b1053-577f-4d81-a8c8-020e7319a38a', 'versions', '12a3b9e6-06e6-4a29-96bf-90c82fe79a0d'
    When method GET
    Then status 401

  Scenario: Insufficient scope
    * configure headers = { Authorization: 'Bearer insufficientScopeToken' }
    Given path 'actions', '910b1053-577f-4d81-a8c8-020e7319a38a', 'versions', '12a3b9e6-06e6-4a29-96bf-90c82fe79a0d'
    When method GET
    Then status 403

  Scenario: Action version does not exist
    Given path 'actions', '910b1053-577f-4d81-a8c8-020e7319a38a', 'versions', 'nonExistentVersionId'
    When method GET
    Then status 404

  Scenario: Too many requests
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    Given path 'actions', '910b1053-577f-4d81-a8c8-020e7319a38a', 'versions', '12a3b9e6-06e6-4a29-96bf-90c82fe79a0d'
    When method GET
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'
