# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /actions/triggers/{triggerId}/bindings_patch for http method type PATCH 
# RoostTestHash=3af9419855
# 
# 

# ********RoostGPT********
Feature: Update Trigger Bindings

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Update Trigger Bindings with Valid Data
    Given path '/actions/triggers/<triggerId>/bindings'
    And request
      """
      { 
        "bindings": [ 
          { 
            "ref": { "type": "<refType>", "value": "<refValue>" }, 
            "display_name": "<displayName>", 
            "secrets": [ { "name": "<secretName>", "value": "<secretValue>" } ] 
          } 
        ] 
      }
      """
    When method PATCH
    Then status 200
    And match response.bindings == '#array'
    And match response.bindings[0].id == '#string'
    And match response.bindings[0].trigger_id == '<triggerId>'
    And match response.bindings[0].display_name == '#string'
    And match response.bindings[0].action.id == '#string'
    And match response.bindings[0].action.name == '#string'
    And match response.bindings[0].action.supported_triggers == '#array'
    And match response.bindings[0].action.all_changes_deployed == '#boolean'
    And match response.bindings[0].action.created_at == '#string'
    And match response.bindings[0].action.updated_at == '#string'
    And match response.bindings[0].action.code == '#string'
    And match response.bindings[0].action.dependencies == '#array'
    And match response.bindings[0].action.runtime == '#string'
    And match response.bindings[0].action.secrets == '#array'
    And match response.bindings[0].action.deployed_version == '#object'
    And match response.bindings[0].action.installed_integration_id == '#string'
    And match response.bindings[0].action.integration == '#object'
    And match response.bindings[0].action.status == '#string'
    And match response.bindings[0].action.built_at == '#string'
    And match response.bindings[0].action.deploy == '#boolean'
    And match response.bindings[0].created_at == '#string'
    And match response.bindings[0].updated_at == '#string'

    Examples:
      | read('actions_triggers_triggerId_bindings_patch.csv') |

  Scenario: Invalid Request Body
    Given path '/actions/triggers/invalidTriggerId/bindings'
    And request
      """
      { "invalid": "data" }
      """
    When method PATCH
    Then status 400

  Scenario: Invalid Token
    * configure headers = { Authorization: 'Bearer invalidToken' }
    Given path '/actions/triggers/abc123/bindings'
    And request
      """
      { 
        "bindings": [ 
          { 
            "ref": { "type": "action_id", "value": "my-action" }, 
            "display_name": "my-action-1", 
            "secrets": [ { "name": "mySecret", "value": "secret123" } ] 
          } 
        ] 
      }
      """
    When method PATCH
    Then status 401

  Scenario: Insufficient Scope
    * configure headers = { Authorization: 'Bearer insufficientScopeToken' }
    Given path '/actions/triggers/abc123/bindings'
    And request
      """
      { 
        "bindings": [ 
          { 
            "ref": { "type": "action_id", "value": "my-action" }, 
            "display_name": "my-action-1", 
            "secrets": [ { "name": "mySecret", "value": "secret123" } ] 
          } 
        ] 
      }
      """
    When method PATCH
    Then status 403

  Scenario: Too Many Requests
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    Given path '/actions/triggers/abc123/bindings'
    And request
      """
      { 
        "bindings": [ 
          { 
            "ref": { "type": "action_id", "value": "my-action" }, 
            "display_name": "my-action-1", 
            "secrets": [ { "name": "mySecret", "value": "secret123" } ] 
          } 
        ] 
      }
      """
    When method PATCH
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'
