# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /actions/executions/{id}_get for http method type GET 
# RoostTestHash=0a5d20f77f
# 
# 

# ********RoostGPT********
Feature: Actions Executions API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Retrieve Execution by ID
    Given path 'actions', 'executions', '<id>'
    When method GET
    Then status <status>
    And match response == '#object'
    And match response.id == '#string'
    And match response.trigger_id == '#string'
    And match response.status == '#string'
    And response.status in ['unspecified', 'pending', 'final', 'partial', 'canceled', 'suspended']
    And match response.results == '#array'
    And match response.results[*].action_name == '#string'
    And match response.results[*].error == '#object'
    And match response.results[*].error.id == '#string'
    And match response.results[*].error.msg == '#string'
    And match response.results[*].error.url == '#string'
    And match response.results[*].started_at == '#string'
    And match response.results[*].started_at == '#date'
    And match response.results[*].ended_at == '#string'
    And match response.results[*].ended_at == '#date'
    And match response.created_at == '#string'
    And match response.created_at == '#date'
    And match response.updated_at == '#string'
    And match response.updated_at == '#date'

    Examples:
      | id                                   | status |
      | c5b35bb1-c67d-40bb-9b0d-700b6fe33dd9 |    200 |

  Scenario: Invalid Execution ID
    Given path 'actions', 'executions', 'invalid-id'
    When method GET
    Then status 404

  Scenario: Invalid Authorization
    * configure headers = { Authorization: 'Bearer invalid_token' }
    Given path 'actions', 'executions', 'c5b35bb1-c67d-40bb-9b0d-700b6fe33dd9'
    When method GET
    Then status 401

  Scenario: Insufficient Scope
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    Given path 'actions', 'executions', 'c5b35bb1-c67d-40bb-9b0d-700b6fe33dd9'
    When method GET
    Then status 403

  Scenario: Rate Limit Exceeded
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    Given path 'actions', 'executions', 'c5b35bb1-c67d-40bb-9b0d-700b6fe33dd9'
    When method GET
    Then status 429
