# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /actions/actions/{id}_delete for http method type DELETE 
# RoostTestHash=664904329a
# 
# 

# ********RoostGPT********
Feature: Delete Action API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Delete an action with valid ID
    Given path 'actions', '<id>'
    And param force = <force>
    When method DELETE
    Then status 204

    Examples:
      | read('actions_actions_id_delete.csv') |

  Scenario Outline: Delete an action with invalid ID
    Given path 'actions', '<id>'
    When method DELETE
    Then status 404

    Examples:
      | id          |
      | 'invalidId' |

  Scenario: Delete an action with invalid token
    * configure headers = { Authorization: 'Bearer invalid_token' }
    Given path 'actions', 'action123'
    When method DELETE
    Then status 401

  Scenario: Delete an action with insufficient scope
    * configure headers = { Authorization: 'Bearer insufficient_scope_token' }
    Given path 'actions', 'action123'
    When method DELETE
    Then status 403

  Scenario: Delete an action with too many requests
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    Given path 'actions', 'action123'
    When method DELETE
    Then status 429
    And match responseHeaders contains { 'X-RateLimit-Limit': '#number', 'X-RateLimit-Remaining': '#number', 'X-RateLimit-Reset': '#number' }

  Scenario: Delete an action with invalid request URI
    Given path 'actions', ''
    When method DELETE
    Then status 400
