# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /actions/triggers_get for http method type GET 
# RoostTestHash=428d842114
# 
# 

# ********RoostGPT********
Feature: Actions Triggers API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario: Retrieve the set of triggers currently available within actions
    Given path 'actions/triggers'
    When method GET
    Then status 200
    And match response == '#object'
    And match response.triggers == '#array'
    And match response.triggers[*].id == '#string'
    And match response.triggers[*].version == '#string'
    And match response.triggers[*].status == '#string'
    And match response.triggers[*].runtimes == '#array'
    And match response.triggers[*].runtimes[*] == '#string'
    And match response.triggers[*].default_runtime == '#string'
    And match response.triggers[*].compatible_triggers == '#array'
    And match response.triggers[*].compatible_triggers[*].id == '#string'
    And match response.triggers[*].compatible_triggers[*].version == '#string'
    And match response.triggers[*].binding_policy == '#string'

  Scenario: Invalid request URI
    Given path 'actions/invalid'
    When method GET
    Then status 400

  Scenario: Invalid token
    Given path 'actions/triggers'
    * configure headers = { Authorization: 'Bearer invalid_token' }
    When method GET
    Then status 401

  Scenario: Insufficient scope
    Given path 'actions/triggers'
    * configure headers = { Authorization: 'Bearer insufficient_scope_token' }
    When method GET
    Then status 403

  Scenario: Too many requests
    Given path 'actions/triggers'
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    When method GET
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'
