# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /actions/actions/{id}/test_post for http method type POST 
# RoostTestHash=d5fd205583
# 
# 

# ********RoostGPT********
Feature: Test Action API

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Test Action with Valid Payload
    Given path 'actions', 'actions', '<id>', 'test'
    And request
      """
      { payload: <payload> }
      """
    When method POST
    Then status 200
    And match response == { payload: '#object' }
    And match response.payload == '#object'

    Examples:
      | read('actions_actions_id_test_post.csv') |

  Scenario Outline: Test Action with Invalid Request Body
    Given path 'actions', 'actions', '<id>', 'test'
    And request
      """
      <invalidPayload>
      """
    When method POST
    Then status 400

    Examples:
      | id  | invalidPayload               |
      | 123 | { "invalidKey": "value" }    |
      | 456 | { "anotherInvalidKey": 123 } |

  Scenario: Test Action with Invalid Token
    * configure headers = { Authorization: 'Bearer invalid_token' }
    Given path 'actions', 'actions', '123', 'test'
    And request
      """
      { payload: { "key": "value" } }
      """
    When method POST
    Then status 401

  Scenario: Test Action with Insufficient Scope
    * configure headers = { Authorization: 'Bearer insufficient_scope_token' }
    Given path 'actions', 'actions', '123', 'test'
    And request
      """
      { payload: { "key": "value" } }
      """
    When method POST
    Then status 403

  Scenario: Test Action with Rate Limit Exceeded
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    Given path 'actions', 'actions', '123', 'test'
    And request
      """
      { payload: { "key": "value" } }
      """
    When method POST
    Then status 429
    And match responseHeaders contains
      """
      { 'X-RateLimit-Limit': '#number', 'X-RateLimit-Remaining': '#number', 'X-RateLimit-Reset': '#number' }
      """
