# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /anomaly/blocks/ips/{id}_delete for http method type DELETE 
# RoostTestHash=a4cd5cb39d
# 
# 

# ********RoostGPT********
Feature: Anomaly Blocks IPs API

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Remove Blocked IP Address
    Given path 'anomaly', 'blocks', 'ips', '<id>'
    When method DELETE
    Then status <status>
    And match response == <responseSchema>

    Examples:
      | id                | status | responseSchema         |
      | '192.168.1.1'     |    204 | {}                     |
      | 'invalid-ip'      |    400 | { message: '#string' } |
      | 'unauthorized-ip' |    401 | { message: '#string' } |
      | 'forbidden-ip'    |    403 | { message: '#string' } |
      | 'rate-limit-ip'   |    429 | { message: '#string' } |

  Scenario: Validate Response Headers for Rate Limit
    Given path 'anomaly', 'blocks', 'ips', 'rate-limit-ip'
    When method DELETE
    Then status 429
    And match responseHeaders contains
      """
      {
        'X-RateLimit-Limit': '#number',
        'X-RateLimit-Remaining': '#number',
        'X-RateLimit-Reset': '#number'
      }
      """
