# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /attack-protection/breached-password-detection_patch for http method type PATCH 
# RoostTestHash=9dddca45b9
# 
# 

# ********RoostGPT********
Feature: Update Breached Password Detection Settings

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Update Breached Password Detection with valid inputs
    Given path 'attack-protection/breached-password-detection'
    And request
      """
      {
        "enabled": <enabled>,
        "shields": <shields>,
        "admin_notification_frequency": <admin_notification_frequency>,
        "method": "<method>",
        "stage": {
          "pre-user-registration": {
            "shields": <pre_user_registration_shields>
          },
          "pre-change-password": {
            "shields": <pre_change_password_shields>
          }
        }
      }
      """
    When method PATCH
    Then status 200
    And match response == '#object'
    And match response.enabled == '#boolean'
    And match response.shields == '#[] string'
    And match response.admin_notification_frequency == '#[] string'
    And match response.method == '#string'
    And match response.stage == '#object'
    And match response.stage.pre-user-registration == '#object'
    And match response.stage.pre-user-registration.shields == '#[] string'
    And match response.stage.pre-change-password == '#object'
    And match response.stage.pre-change-password.shields == '#[] string'

    Examples:
      | read('attack-protection_breached-password-detection_patch.csv') |

  Scenario: Invalid request body
    Given path 'attack-protection/breached-password-detection'
    And request
      """
      { "enabled": "not-a-boolean" }
      """
    When method PATCH
    Then status 400

  Scenario: Invalid token
    * configure headers = { Authorization: 'Bearer invalid_token' }
    Given path 'attack-protection/breached-password-detection'
    And request
      """
      { "enabled": true }
      """
    When method PATCH
    Then status 401

  Scenario: Insufficient scope
    * configure headers = { Authorization: 'Bearer insufficient_scope_token' }
    Given path 'attack-protection/breached-password-detection'
    And request
      """
      { "enabled": true }
      """
    When method PATCH
    Then status 403

  Scenario: Too many requests
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    Given path 'attack-protection/breached-password-detection'
    And request
      """
      { "enabled": true }
      """
    When method PATCH
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'
