# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /attack-protection/brute-force-protection_patch for http method type PATCH 
# RoostTestHash=bc90ee90b6
# 
# 

# ********RoostGPT********
Feature: Brute-force Protection Configuration

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Update Brute-force Protection Configuration with Valid Inputs
    Given path 'attack-protection/brute-force-protection'
    And request
      """
      { 
        "enabled": <enabled>, 
        "shields": <shields>, 
        "allowlist": <allowlist>, 
        "mode": <mode>, 
        "max_attempts": <max_attempts> 
      }
      """
    When method PATCH
    Then status 200
    And match response == '#object'
    And match response.enabled == '#boolean'
    And match response.shields == '#[] string'
    And match response.allowlist == '#[] string'
    And match response.mode == '#string'
    And match response.max_attempts == '#number'

    Examples:
      | read('attack-protection_brute-force-protection_patch.csv') |

  Scenario: Invalid Request Body
    Given path 'attack-protection/brute-force-protection'
    And request
      """
      { 
        "enabled": "not_a_boolean" 
      }
      """
    When method PATCH
    Then status 400

  Scenario: Unauthorized Access
    * configure headers = { Authorization: 'Bearer invalid_token' }
    Given path 'attack-protection/brute-force-protection'
    And request
      """
      { 
        "enabled": true 
      }
      """
    When method PATCH
    Then status 401

  Scenario: Insufficient Scope
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN_WITHOUT_SCOPE'] }
    Given path 'attack-protection/brute-force-protection'
    And request
      """
      { 
        "enabled": true 
      }
      """
    When method PATCH
    Then status 403

  Scenario: Rate Limit Exceeded
    Given path 'attack-protection/brute-force-protection'
    And request
      """
      { 
        "enabled": true 
      }
      """
    When method PATCH
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'
