# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /attack-protection/breached-password-detection_get for http method type GET 
# RoostTestHash=cb28c1f94a
# 
# 

# ********RoostGPT********
Feature: Breached Password Detection API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario: Retrieve Breached Password Detection Settings with Valid Token
    Given path 'attack-protection/breached-password-detection'
    When method GET
    Then status 200
    And match response == '#object'
    And match response.enabled == '#boolean'
    And match response.shields == '#[] string'
    And match response.admin_notification_frequency == '#[] string'
    And match response.method == '#string'
    And match response.stage == '#object'
    And match response.stage.pre-user-registration == '#object'
    And match response.stage.pre-user-registration.shields == '#[] string'
    And match response.stage.pre-change-password == '#object'
    And match response.stage.pre-change-password.shields == '#[] string'

  Scenario: Retrieve Breached Password Detection Settings with Invalid Token
    Given path 'attack-protection/breached-password-detection'
    And configure headers = { Authorization: 'Bearer invalid_token' }
    When method GET
    Then status 401

  Scenario: Retrieve Breached Password Detection Settings with Insufficient Scope
    Given path 'attack-protection/breached-password-detection'
    And configure headers = { Authorization: 'Bearer insufficient_scope_token' }
    When method GET
    Then status 403

  Scenario: Retrieve Breached Password Detection Settings with Rate Limit Exceeded
    Given path 'attack-protection/breached-password-detection'
    And configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    When method GET
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'
