# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /branding/phone/templates/{id}_delete for http method type DELETE 
# RoostTestHash=c7cd36cd1f
# 
# 

# ********RoostGPT********
Feature: Delete Phone Notification Template API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Delete phone notification template with valid ID
    Given path 'branding', 'phone', 'templates', '<id>'
    When method DELETE
    Then status 204

    Examples:
      | id        |
      | template1 |
      | template2 |

  Scenario Outline: Delete phone notification template with invalid ID
    Given path 'branding', 'phone', 'templates', '<id>'
    When method DELETE
    Then status 404
    And match response == ''

    Examples:
      | id       |
      | invalid1 |
      | invalid2 |

  Scenario: Delete phone notification template with missing authorization
    * configure headers = {}
    Given path 'branding', 'phone', 'templates', 'template1'
    When method DELETE
    Then status 401
    And match response == ''

  Scenario: Delete phone notification template with insufficient scope
    * configure headers = { Authorization: 'Bearer ' + karate.properties['INSUFFICIENT_SCOPE_TOKEN'] }
    Given path 'branding', 'phone', 'templates', 'template1'
    When method DELETE
    Then status 403
    And match response == ''

  Scenario: Delete phone notification template with too many requests
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    Given path 'branding', 'phone', 'templates', 'template1'
    When method DELETE
    Then status 429
    And match response == ''
    And match responseHeaders contains { 
      'X-RateLimit-Limit': '#number', 
      'X-RateLimit-Remaining': '#number', 
      'X-RateLimit-Reset': '#number' 
    }

  Scenario: Delete phone notification template with invalid request URI
    Given path 'branding', 'phone', 'templates'
    When method DELETE
    Then status 400
    And match response == ''
