# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /branding/themes/default_get for http method type GET 
# RoostTestHash=910f2b8114
# 
# 

# ********RoostGPT********
Feature: Default Branding Theme API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario: Retrieve default branding theme with valid token
    Given path 'branding/themes/default'
    When method GET
    Then status 200
    And match response == '#object'
    And match response.borders == '#object'
    And match response.borders.button_border_radius == '#number'
    And match response.borders.button_border_weight == '#number'
    And match response.borders.buttons_style == '#string'
    And match response.borders.input_border_radius == '#number'
    And match response.borders.input_border_weight == '#number'
    And match response.borders.inputs_style == '#string'
    And match response.borders.show_widget_shadow == '#boolean'
    And match response.borders.widget_border_weight == '#number'
    And match response.borders.widget_corner_radius == '#number'
    And match response.colors == '#object'
    And match response.colors.body_text == '#string'
    And match response.colors.error == '#string'
    And match response.colors.header == '#string'
    And match response.colors.icons == '#string'
    And match response.colors.input_background == '#string'
    And match response.colors.input_border == '#string'
    And match response.colors.input_filled_text == '#string'
    And match response.colors.input_labels_placeholders == '#string'
    And match response.colors.links_focused_components == '#string'
    And match response.colors.primary_button == '#string'
    And match response.colors.primary_button_label == '#string'
    And match response.colors.secondary_button_border == '#string'
    And match response.colors.secondary_button_label == '#string'
    And match response.colors.success == '#string'
    And match response.colors.widget_background == '#string'
    And match response.colors.widget_border == '#string'
    And match response.displayName == '#string'
    And match response.fonts == '#object'
    And match response.fonts.body_text == '#object'
    And match response.fonts.body_text.bold == '#boolean'
    And match response.fonts.body_text.size == '#number'
    And match response.fonts.buttons_text == '#object'
    And match response.fonts.buttons_text.bold == '#boolean'
    And match response.fonts.buttons_text.size == '#number'
    And match response.fonts.font_url == '#string'
    And match response.fonts.input_labels == '#object'
    And match response.fonts.input_labels.bold == '#boolean'
    And match response.fonts.input_labels.size == '#number'
    And match response.fonts.links == '#object'
    And match response.fonts.links.bold == '#boolean'
    And match response.fonts.links.size == '#number'
    And match response.fonts.links_style == '#string'
    And match response.fonts.reference_text_size == '#number'
    And match response.fonts.subtitle == '#object'
    And match response.fonts.subtitle.bold == '#boolean'
    And match response.fonts.subtitle.size == '#number'
    And match response.fonts.title == '#object'
    And match response.fonts.title.bold == '#boolean'
    And match response.fonts.title.size == '#number'
    And match response.page_background == '#object'
    And match response.page_background.background_color == '#string'
    And match response.page_background.background_image_url == '#string'
    And match response.page_background.page_layout == '#string'
    And match response.themeId == '#string'
    And match response.widget == '#object'
    And match response.widget.header_text_alignment == '#string'
    And match response.widget.logo_height == '#number'
    And match response.widget.logo_position == '#string'
    And match response.widget.logo_url == '#string'
    And match response.widget.social_buttons_layout == '#string'

  Scenario Outline: Retrieve default branding theme with invalid token
    Given path 'branding/themes/default'
    * configure headers = { Authorization: 'Bearer ' + <invalid_token> }
    When method GET
    Then status 401

    Examples:
      | invalid_token     |
      | 'invalidToken123' |

  Scenario: Retrieve default branding theme with insufficient scope
    Given path 'branding/themes/default'
    * configure headers = { Authorization: 'Bearer ' + karate.properties['INSUFFICIENT_SCOPE_TOKEN'] }
    When method GET
    Then status 403

  Scenario: Retrieve default branding theme with invalid theme ID
    Given path 'branding/themes/invalid'
    When method GET
    Then status 404

  Scenario: Too many requests
    Given path 'branding/themes/default'
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    When method GET
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'
