# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /branding/templates/universal-login_delete for http method type DELETE 
# RoostTestHash=1042327158
# 
# 

# ********RoostGPT********
Feature: Delete Template for New Universal Login Experience

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['BEARER_TOKEN'] }

  Scenario: Delete template with valid authorization
    Given path 'branding/templates/universal-login'
    When method DELETE
    Then status 204

  Scenario Outline: Delete template with invalid authorization
    Given path 'branding/templates/universal-login'
    And configure headers = { Authorization: 'Bearer ' + '<invalid_token>' }
    When method DELETE
    Then status <status_code>
    And match response ==
      """
      <response_body>
      """

    Examples:
      | invalid_token | status_code | response_body                                                                                                                                   |
      | invalid       |         401 | { "message": "#string", "description": "Invalid token.", "x-description-1": "Invalid signature received for JSON Web Token validation." }       |
      | expired       |         402 | { "message": "#string", "description": "A paid subscription is required for this feature." }                                                    |
      | no_scope      |         403 | { "message": "#string", "description": "Insufficient scope; expected: delete:branding." }                                                       |
      | rate_limit    |         429 | { "message": "#string", "description": "Too many requests. Check the X-RateLimit-Limit, X-RateLimit-Remaining and X-RateLimit-Reset headers." } |
