# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /branding/phone/providers_get for http method type GET 
# RoostTestHash=1401a46b57
# 
# 

# ********RoostGPT********
Feature: Phone Providers API

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Retrieve a list of phone providers
    Given path 'branding/phone/providers'
    And param disabled = <disabled>
    When method GET
    Then status 200
    And match response == '#object'
    And match response.providers == '#array'
    And match response.providers[*].id == '#string'
    And match response.providers[*].tenant == '#string'
    And match response.providers[*].name == '#string'
    And match response.providers[*].name contains ['twilio', 'custom']
    And match response.providers[*].channel == '#string'
    And match response.providers[*].channel contains ['phone']
    And match response.providers[*].disabled == '#boolean'
    And match response.providers[*].configuration == '#object'
    And match response.providers[*].configuration.sid == '#string?'
    And match response.providers[*].configuration.delivery_methods == '#array'
    And match response.providers[*].configuration.delivery_methods[*] contains ['text', 'voice']
    And match response.providers[*].created_at == '#string'
    And match response.providers[*].created_at == '#regex ^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d{1,3})?Z$'
    And match response.providers[*].updated_at == '#string'
    And match response.providers[*].updated_at == '#regex ^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d{1,3})?Z$'

    Examples:
      | read('branding_phone_providers_get.csv') |

  Scenario: Invalid request query string
    Given path 'branding/phone/providers'
    And param disabled = 'invalid'
    When method GET
    Then status 400

  Scenario: Invalid token
    * configure headers = { Authorization: 'Bearer invalid_token' }
    Given path 'branding/phone/providers'
    When method GET
    Then status 401

  Scenario: Insufficient scope
    * configure headers = { Authorization: 'Bearer insufficient_scope_token' }
    Given path 'branding/phone/providers'
    When method GET
    Then status 403

  Scenario: Too many requests
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    Given path 'branding/phone/providers'
    When method GET
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'
