# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /branding/phone/templates_post for http method type POST 
# RoostTestHash=53e6d20ed5
# 
# 

# ********RoostGPT********
Feature: Phone Notification Template API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Create a phone notification template with valid data
    Given path '/branding/phone/templates'
    And request """ 
    { 
      "type": "<type>",
      "disabled": <disabled>,
      "content": {
        "syntax": "<syntax>",
        "from": "<from>",
        "body": {
          "text": "<text>",
          "voice": "<voice>"
        }
      }
    }
    """
    When method POST
    Then status 201
    And match response == '#object'
    And match response.id == '#string'
    And match response.channel == '#string?'
    And match response.customizable == '#boolean?'
    And match response.tenant == '#string?'
    And match response.content == '#object'
    And match response.content.syntax == '#string'
    And match response.content.from == '#string'
    And match response.content.body == '#object'
    And match response.content.body.text == '#string'
    And match response.content.body.voice == '#string'
    And match response.type == '#string'
    And match response.disabled == '#boolean'

    Examples:
      | type           | disabled | syntax | from       | text       | voice      |
      | otp_verify     | false    | json   | 1234567890 | Hello text | Hello voice|
      | change_password| true     | xml    | 0987654321 | Change text| Change voice|

  Scenario: Invalid request body
    Given path '/branding/phone/templates'
    And request """ 
    { 
      "invalid": "data" 
    }
    """
    When method POST
    Then status 400

  Scenario: Invalid token
    * configure headers = { Authorization: 'Bearer invalid_token' }
    Given path '/branding/phone/templates'
    And request """ 
    { 
      "type": "otp_verify",
      "disabled": false,
      "content": {
        "syntax": "json",
        "from": "1234567890",
        "body": {
          "text": "Hello text",
          "voice": "Hello voice"
        }
      }
    }
    """
    When method POST
    Then status 401

  Scenario: Insufficient scope
    * configure headers = { Authorization: 'Bearer insufficient_scope_token' }
    Given path '/branding/phone/templates'
    And request """ 
    { 
      "type": "otp_verify",
      "disabled": false,
      "content": {
        "syntax": "json",
        "from": "1234567890",
        "body": {
          "text": "Hello text",
          "voice": "Hello voice"
        }
      }
    }
    """
    When method POST
    Then status 403

  Scenario: Phone template already configured for tenant
    Given path '/branding/phone/templates'
    And request """ 
    { 
      "type": "otp_verify",
      "disabled": false,
      "content": {
        "syntax": "json",
        "from": "1234567890",
        "body": {
          "text": "Hello text",
          "voice": "Hello voice"
        }
      }
    }
    """
    When method POST
    Then status 409

  Scenario: Too many requests
    * configure headers = { Authorization: 'Bearer rate_limit_token' }
    Given path '/branding/phone/templates'
    And request """ 
    { 
      "type": "otp_verify",
      "disabled": false,
      "content": {
        "syntax": "json",
        "from": "1234567890",
        "body": {
          "text": "Hello text",
          "voice": "Hello voice"
        }
      }
    }
    """
    When method POST
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'
