# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /branding/phone/providers/{id}/try_post for http method type POST 
# RoostTestHash=15065c57c4
# 
# 

# ********RoostGPT********
Feature: Test Phone Notification for Configured Provider

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Send Test Phone Notification with Valid Inputs
    Given path 'branding', 'phone', 'providers', '<id>', 'try'
    And request
      """
      { "to": "<to>", "delivery_method": "<delivery_method>" }
      """
    When method POST
    Then status 202
    And match response ==
      """
      { code: '#number', message: '#string' }
      """

    Examples:
      | read('branding_phone_providers_id_try_post.csv') |

  Scenario Outline: Send Test Phone Notification with Invalid ID
    Given path 'branding', 'phone', 'providers', '<id>', 'try'
    And request
      """
      { "to": "<to>", "delivery_method": "<delivery_method>" }
      """
    When method POST
    Then status 404

    Examples:
      | id   | to         | delivery_method |
      | 0000 | 1234567890 | text            |

  Scenario Outline: Send Test Phone Notification with Missing 'to' Field
    Given path 'branding', 'phone', 'providers', '<id>', 'try'
    And request
      """
      { "delivery_method": "<delivery_method>" }
      """
    When method POST
    Then status 400

    Examples:
      | id   | delivery_method |
      | 1234 | text            |

  Scenario Outline: Send Test Phone Notification with Invalid Token
    * configure headers = { Authorization: 'Bearer invalid_token' }
    Given path 'branding', 'phone', 'providers', '<id>', 'try'
    And request
      """
      { "to": "<to>", "delivery_method": "<delivery_method>" }
      """
    When method POST
    Then status 401

    Examples:
      | id   | to         | delivery_method |
      | 1234 | 1234567890 | text            |

  Scenario Outline: Send Test Phone Notification with Insufficient Scope
    * configure headers = { Authorization: 'Bearer insufficient_scope_token' }
    Given path 'branding', 'phone', 'providers', '<id>', 'try'
    And request
      """
      { "to": "<to>", "delivery_method": "<delivery_method>" }
      """
    When method POST
    Then status 403

    Examples:
      | id   | to         | delivery_method |
      | 1234 | 1234567890 | text            |

  Scenario Outline: Send Test Phone Notification with Rate Limit Exceeded
    Given path 'branding', 'phone', 'providers', '<id>', 'try'
    And request
      """
      { "to": "<to>", "delivery_method": "<delivery_method>" }
      """
    When method POST
    Then status 429
    And match responseHeaders contains
      """
      { 'X-RateLimit-Limit': '#number', 'X-RateLimit-Remaining': '#number', 'X-RateLimit-Reset': '#number' }
      """

    Examples:
      | id   | to         | delivery_method |
      | 1234 | 1234567890 | text            |
