# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /branding/phone/providers/{id}_get for http method type GET 
# RoostTestHash=2a4e62a8dc
# 
# 

# ********RoostGPT********
Feature: Phone Provider API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Retrieve Phone Provider Details
    Given path 'branding', 'phone', 'providers', '<id>'
    When method GET
    Then status <status>
    And match response == <responseSchema>
    And match response.id == '#string'
    And match response.tenant == '#string'
    And match response.name == '#string'
    And match response.channel == '#string'
    And match response.disabled == '#boolean'
    And match response.configuration == '#object'
    And match response.created_at == '#string'
    And match response.updated_at == '#string'

    Examples:
      | id  | status | responseSchema                                                                                                                                                                  |
      | 123 |    200 | """ { id: '#string', tenant: '#string', name: '#string', channel: '#string', disabled: '#boolean', configuration: '#object', created_at: '#string', updated_at: '#string' } """ |
      | 456 |    404 | """ { message: '#string' } """                                                                                                                                                  |
      | 789 |    400 | """ { message: '#string' } """                                                                                                                                                  |

  Scenario: Invalid Token
    Given path 'branding', 'phone', 'providers', '123'
    * configure headers = { Authorization: 'Bearer invalid_token' }
    When method GET
    Then status 401
    And match response.message == '#string'

  Scenario: Insufficient Scope
    Given path 'branding', 'phone', 'providers', '123'
    * configure headers = { Authorization: 'Bearer insufficient_scope_token' }
    When method GET
    Then status 403
    And match response.message == '#string'

  Scenario: Too Many Requests
    Given path 'branding', 'phone', 'providers', '123'
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    When method GET
    Then status 429
    And match response.message == '#string'
    And match response.headers['X-RateLimit-Limit'] == '#number'
    And match response.headers['X-RateLimit-Remaining'] == '#number'
    And match response.headers['X-RateLimit-Reset'] == '#number'
