# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /branding_patch for http method type PATCH 
# RoostTestHash=6456fea6bb
# 
# 

# ********RoostGPT********
Feature: Branding API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Update branding settings with valid payload
    Given path 'branding'
    And request
      """
      <requestBody>
      """
    When method PATCH
    Then status 200
    And match response == '#object'
    And match response.colors == '#object'
    And match response.colors.primary == '#string'
    And match response.colors.page_background == '#string'
    And match response.favicon_url == '#string'
    And match response.logo_url == '#string'
    And match response.font == '#object'
    And match response.font.url == '#string'

    Examples:
      | read('branding_patch.csv') |

  Scenario Outline: Update branding settings with invalid payload
    Given path 'branding'
    And request
      """
      <requestBody>
      """
    When method PATCH
    Then status 400

    Examples:
      | requestBody                                                                                                                                                                                                                      |
      | { "colors": { "primary": "invalid-color", "page_background": "#FFFFFF" }, "favicon_url": "https://example.com/favicon.ico", "logo_url": "https://example.com/logo.png", "font": { "url": "https://example.com/font.ttf" } }      |
      | { "colors": { "primary": "#123456", "page_background": "invalid-background" }, "favicon_url": "https://example.com/favicon.ico", "logo_url": "https://example.com/logo.png", "font": { "url": "https://example.com/font.ttf" } } |

  Scenario: Update branding settings with invalid token
    Given path 'branding'
    * configure headers = { Authorization: 'Bearer invalid_token' }
    And request
      """
      { "colors": { "primary": "#FF5733", "page_background": "#FFFFFF" }, "favicon_url": "https://example.com/favicon.ico", "logo_url": "https://example.com/logo.png", "font": { "url": "https://example.com/font.ttf" } }
      """
    When method PATCH
    Then status 401

  Scenario: Update branding settings with insufficient scope
    Given path 'branding'
    * configure headers = { Authorization: 'Bearer insufficient_scope_token' }
    And request
      """
      { "colors": { "primary": "#FF5733", "page_background": "#FFFFFF" }, "favicon_url": "https://example.com/favicon.ico", "logo_url": "https://example.com/logo.png", "font": { "url": "https://example.com/font.ttf" } }
      """
    When method PATCH
    Then status 403

  Scenario: Too many requests
    Given path 'branding'
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    And request
      """
      { "colors": { "primary": "#FF5733", "page_background": "#FFFFFF" }, "favicon_url": "https://example.com/favicon.ico", "logo_url": "https://example.com/logo.png", "font": { "url": "https://example.com/font.ttf" } }
      """
    When method PATCH
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'
