# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /branding/phone/templates/{id}/try_post for http method type POST 
# RoostTestHash=8c30b26401
# 
# 

# ********RoostGPT********
Feature: Test Phone Notification for Configured Template

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Send test phone notification with valid input
    Given path 'branding', 'phone', 'templates', '<id>', 'try'
    And request 
      """
      { 
        "to": '<to>', 
        "delivery_method": '<delivery_method>' 
      }
      """
    When method POST
    Then status 202
    And match response == { message: '#string' }

    Examples:
      | id  | to         | delivery_method |
      | 123 | 1234567890 | text            |
      | 456 | 0987654321 | voice           |

  Scenario Outline: Invalid request body
    Given path 'branding', 'phone', 'templates', '<id>', 'try'
    And request 
      """
      { 
        "to": '<to>' 
      }
      """
    When method POST
    Then status 400

    Examples:
      | id  | to                  |
      | 123 | ''                  |
      | 456 | '12345678901234567' |

  Scenario: Invalid token
    * configure headers = { Authorization: 'Bearer invalid_token' }
    Given path 'branding', 'phone', 'templates', '123', 'try'
    And request 
      """
      { 
        "to": '1234567890', 
        "delivery_method": 'text' 
      }
      """
    When method POST
    Then status 401

  Scenario: Insufficient scope
    * configure headers = { Authorization: 'Bearer insufficient_scope_token' }
    Given path 'branding', 'phone', 'templates', '123', 'try'
    And request 
      """
      { 
        "to": '1234567890', 
        "delivery_method": 'text' 
      }
      """
    When method POST
    Then status 403

  Scenario: Phone template does not exist
    Given path 'branding', 'phone', 'templates', 'nonexistent', 'try'
    And request 
      """
      { 
        "to": '1234567890', 
        "delivery_method": 'text' 
      }
      """
    When method POST
    Then status 404

  Scenario: Too many requests
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    Given path 'branding', 'phone', 'templates', '123', 'try'
    And request 
      """
      { 
        "to": '1234567890', 
        "delivery_method": 'text' 
      }
      """
    When method POST
    Then status 429
    And match responseHeaders contains 
      { 
        'X-RateLimit-Limit': '#number', 
        'X-RateLimit-Remaining': '#number', 
        'X-RateLimit-Reset': '#number' 
      }
