# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /branding/phone/templates/{id}_get for http method type GET 
# RoostTestHash=9f309710bd
# 
# 

# ********RoostGPT********
Feature: Phone Notification Template API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Get Phone Notification Template by ID
    Given path 'branding', 'phone', 'templates', '<id>'
    When method GET
    Then status <status>
    And match response == <responseSchema>
    And match response.id == '#string'
    And match response.content == '#object'
    And match response.content.syntax == '#string'
    And match response.content.from == '#string'
    And match response.content.body == '#object'
    And match response.content.body.text == '#string'
    And match response.content.body.voice == '#string'
    And match response.disabled == '#boolean'
    And match response.type == '#string'
    And match response.channel == '#string?'
    And match response.customizable == '#boolean?'
    And match response.tenant == '#string?'

    Examples:
      | id  | status | responseSchema                                                                                                                                                                                                                     |
      | 123 |    200 | """ { id: '#string', content: { syntax: '#string', from: '#string', body: { text: '#string', voice: '#string' } }, disabled: '#boolean', type: '#string', channel: '#string?', customizable: '#boolean?', tenant: '#string?' } """ |
      | abc |    400 | """ { message: '#string' } """                                                                                                                                                                                                     |
      | xyz |    401 | """ { message: '#string' } """                                                                                                                                                                                                     |
      | def |    403 | """ { message: '#string' } """                                                                                                                                                                                                     |
      | ghi |    404 | """ { message: '#string' } """                                                                                                                                                                                                     |
      | jkl |    429 | """ { message: '#string' } """                                                                                                                                                                                                     |
