# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /branding/phone/templates/{id}/reset_patch for http method type PATCH 
# RoostTestHash=a4f915fc01
# 
# 

# ********RoostGPT********
Feature: Reset Phone Notification Template

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Reset phone notification template with valid ID
    Given path 'branding', 'phone', 'templates', '<id>', 'reset'
    And request {}
    When method POST
    Then status 200
    And match response == '#object'
    And match response.id == '<id>'
    And match response.channel == '#string'
    And match response.customizable == '#boolean'
    And match response.tenant == '#string'
    And match response.content == '#object'
    And match response.content.syntax == '#string'
    And match response.content.from == '#string'
    And match response.content.body == '#object'
    And match response.content.body.text == '#string'
    And match response.content.body.voice == '#string'
    And match response.type == '#string'
    And match response.disabled == '#boolean'

    Examples:
      | read('branding_phone_templates_id_reset_patch.csv') |

  Scenario: Reset phone notification template with invalid ID
    Given path 'branding', 'phone', 'templates', 'invalid-id', 'reset'
    And request {}
    When method POST
    Then status 400

  Scenario: Reset phone notification template with missing authorization
    * configure headers = {}
    Given path 'branding', 'phone', 'templates', 'template1', 'reset'
    And request {}
    When method POST
    Then status 401

  Scenario: Reset phone notification template with insufficient scope
    * configure headers = { Authorization: 'Bearer ' + 'insufficient_scope_token' }
    Given path 'branding', 'phone', 'templates', 'template1', 'reset'
    And request {}
    When method POST
    Then status 403

  Scenario: Reset phone notification template with rate limit exceeded
    * configure headers = { Authorization: 'Bearer ' + 'rate_limit_exceeded_token' }
    Given path 'branding', 'phone', 'templates', 'template1', 'reset'
    And request {}
    When method POST
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'
