# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /branding/templates/universal-login_put for http method type PUT 
# RoostTestHash=a7ad583204
# 
# 

# ********RoostGPT********
Feature: Universal Login Branding Template Management

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Update Universal Login Template with JSON
    Given path 'branding/templates/universal-login'
    And request { "template": """<template>""" }
    When method PUT
    Then status <statusCode>
    And match response == <responseSchema>

    Examples:
      | template                                                                                       | statusCode | responseSchema |
      | '<!DOCTYPE html><html><head>{%- auth0:head -%}</head><body>{%- auth0:widget -%}</body></html>' |        201 | '#null'        |
      | '<!DOCTYPE html><html><head>{%- auth0:head -%}</head><body>{%- auth0:widget -%}</body></html>' |        204 | '#null'        |
      | ''                                                                                             |        400 | '#null'        |

  Scenario Outline: Update Universal Login Template with HTML
    Given path 'branding/templates/universal-login'
    And header Content-Type = 'text/html'
    And request """<template>"""
    When method PUT
    Then status <statusCode>
    And match response == <responseSchema>

    Examples:
      | template                                                                                       | statusCode | responseSchema |
      | '<!DOCTYPE html><html><head>{%- auth0:head -%}</head><body>{%- auth0:widget -%}</body></html>' |        201 | '#null'        |
      | '<!DOCTYPE html><html><head>{%- auth0:head -%}</head><body>{%- auth0:widget -%}</body></html>' |        204 | '#null'        |
      | ''                                                                                             |        400 | '#null'        |

  Scenario: Invalid Token
    Given path 'branding/templates/universal-login'
    And request { "template": """<!DOCTYPE html><html><head>{%- auth0:head -%}</head><body>{%- auth0:widget -%}</body></html>""" }
    And configure headers = { Authorization: 'Bearer invalid_token' }
    When method PUT
    Then status 401
    And match response == '#null'

  Scenario: Insufficient Scope
    Given path 'branding/templates/universal-login'
    And request { "template": """<!DOCTYPE html><html><head>{%- auth0:head -%}</head><body>{%- auth0:widget -%}</body></html>""" }
    And configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    When method PUT
    Then status 403
    And match response == '#null'

  Scenario: Template Update Conflict
    Given path 'branding/templates/universal-login'
    And request { "template": """<!DOCTYPE html><html><head>{%- auth0:head -%}</head><body>{%- auth0:widget -%}</body></html>""" }
    When method PUT
    Then status 409
    And match response == '#null'

  Scenario: Too Many Requests
    Given path 'branding/templates/universal-login'
    And request { "template": """<!DOCTYPE html><html><head>{%- auth0:head -%}</head><body>{%- auth0:widget -%}</body></html>""" }
    When method PUT
    Then status 429
    And match responseHeaders contains { 'X-RateLimit-Limit': '#number', 'X-RateLimit-Remaining': '#number', 'X-RateLimit-Reset': '#number' }
