# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /branding/templates/universal-login_get for http method type GET 
# RoostTestHash=6aa805fc6d
# 
# 

# ********RoostGPT********
Feature: Branding Templates Universal Login API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Test GET /branding/templates/universal-login
    Given path 'branding', 'templates', 'universal-login'
    When method GET
    Then status <statusCode>
    And match response == <responseSchema>
    And match responseHeaders contains { 'Content-Type': 'application/json' }

    Examples:
      | statusCode | responseSchema                                                                                                                                    |
      |        200 | { body: '#string' }                                                                                                                               |
      |        200 | '#string'                                                                                                                                         |
      |        401 | { description: '#string' }                                                                                                                        |
      |        402 | { description: '#string' }                                                                                                                        |
      |        403 | { description: '#string' }                                                                                                                        |
      |        404 | { description: '#string' }                                                                                                                        |
      |        429 | """{ description: '#string', headers: { 'X-RateLimit-Limit': '#number', 'X-RateLimit-Remaining': '#number', 'X-RateLimit-Reset': '#number' } }""" |
