# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /branding/phone/providers_post for http method type POST 
# RoostTestHash=cffe9e0960
# 
# 

# ********RoostGPT********
Feature: Phone Provider Configuration API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Test POST /branding/phone/providers with valid input
    Given path 'branding', 'phone', 'providers'
    And request
      """
      { 
        "name": "<name>", 
        "credentials": { "auth_token": "<auth_token>" }, 
        "configuration": { 
          "sid": "<sid>", 
          "delivery_methods": <delivery_methods> 
        } 
      }
      """
    When method POST
    Then status 201
    And match response == '#object'
    And match response.id == '#string'
    And match response.tenant == '#string'
    And match response.name == '<name>'
    And match response.channel == 'phone'
    And match response.disabled == '#boolean'
    And match response.configuration.sid == '<sid>'
    And match response.configuration.delivery_methods == <delivery_methods>
    And match response.created_at == '#string'
    And match response.updated_at == '#string'

    Examples:
      | read('branding_phone_providers_post.csv') |

  Scenario: Test POST /branding/phone/providers with invalid token
    Given path 'branding', 'phone', 'providers'
    And request
      """
      { 
        "name": "twilio", 
        "credentials": { "auth_token": "invalid" }, 
        "configuration": { 
          "sid": "sid01", 
          "delivery_methods": ["text", "voice"] 
        } 
      }
      """
    When method POST
    Then status 401

  Scenario: Test POST /branding/phone/providers with insufficient scope
    Given path 'branding', 'phone', 'providers'
    And request
      """
      { 
        "name": "twilio", 
        "credentials": { "auth_token": "token123" }, 
        "configuration": { 
          "sid": "sid01", 
          "delivery_methods": ["text", "voice"] 
        } 
      }
      """
    * configure headers = { Authorization: 'Bearer ' + 'insufficient_scope_token' }
    When method POST
    Then status 403

  Scenario: Test POST /branding/phone/providers with conflict
    Given path 'branding', 'phone', 'providers'
    And request
      """
      { 
        "name": "custom", 
        "credentials": { "auth_token": "token456" }, 
        "configuration": { 
          "sid": "sid02", 
          "delivery_methods": ["text"] 
        } 
      }
      """
    When method POST
    Then status 409

  Scenario: Test POST /branding/phone/providers with too many requests
    Given path 'branding', 'phone', 'providers'
    And request
      """
      { 
        "name": "twilio", 
        "credentials": { "auth_token": "token123" }, 
        "configuration": { 
          "sid": "sid01", 
          "delivery_methods": ["text", "voice"] 
        } 
      }
      """
    * configure headers = { Authorization: 'Bearer ' + 'rate_limit_exceeded_token' }
    When method POST
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'
