# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /clients/{client_id}/credentials/{credential_id}_get for http method type GET 
# RoostTestHash=c6d879d684
# 
# 

# ********RoostGPT********
Feature: Client Credential Details API

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Retrieve client credential details with valid credentials
    Given path 'clients', '<client_id>', 'credentials', '<credential_id>'
    When method GET
    Then status 200
    And match response == '#object'
    And match response.id == '#string'
    And match response.name == '#string'
    And match response.kid == '#string'
    And match response.alg == '#string'
    And match response.alg in ['RS256', 'RS384', 'PS256']
    And match response.credential_type == '#string'
    And match response.credential_type in ['public_key', 'cert_subject_dn', 'x509_cert']
    And match response.subject_dn == '#string'
    And match response.thumbprint_sha256 == '#string'
    And match response.created_at == '#string'
    And match response.created_at == '#date'
    And match response.updated_at == '#string'
    And match response.updated_at == '#date'
    And match response.expires_at == '#string'
    And match response.expires_at == '#date'

    Examples:
      | read('clients_client_id_credentials_credential_id_get.csv') |

  Scenario Outline: Invalid token
    Given path 'clients', '<client_id>', 'credentials', '<credential_id>'
    * configure headers = { Authorization: 'Bearer invalid_token' }
    When method GET
    Then status 401

    Examples:
      | client_id | credential_id |
      | client123 | cred456       |

  Scenario Outline: Insufficient scope
    Given path 'clients', '<client_id>', 'credentials', '<credential_id>'
    * configure headers = { Authorization: 'Bearer insufficient_scope_token' }
    When method GET
    Then status 403

    Examples:
      | client_id | credential_id |
      | client123 | cred456       |

  Scenario Outline: Client not found
    Given path 'clients', '<client_id>', 'credentials', '<credential_id>'
    When method GET
    Then status 404

    Examples:
      | client_id      | credential_id |
      | invalid_client | cred456       |

  Scenario Outline: Too many requests
    Given path 'clients', '<client_id>', 'credentials', '<credential_id>'
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    When method GET
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'

    Examples:
      | client_id | credential_id |
      | client123 | cred456       |
