# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /clients/{client_id}/credentials_get for http method type GET 
# RoostTestHash=ccc1077554
# 
# 

# ********RoostGPT********
Feature: Client Credentials API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Get client credentials with valid client_id
    Given path 'clients', <client_id>, 'credentials'
    When method GET
    Then status 200
    And match response == '#[]'
    And match each response == '#object'
    And match each response.id == '#string'
    And match each response.name == '#string'
    And match each response.kid == '#string'
    And match each response.alg == '#string'
    And match each response.alg in ['RS256', 'RS384', 'PS256']
    And match each response.credential_type in ['public_key', 'cert_subject_dn', 'x509_cert']
    And match each response.subject_dn == '#string'
    And match each response.thumbprint_sha256 == '#string'
    And match each response.created_at == '#string'
    And match each response.created_at == '#date'
    And match each response.updated_at == '#string'
    And match each response.updated_at == '#date'
    And match each response.expires_at == '#string'
    And match each response.expires_at == '#date'

    Examples:
      | read('clients_client_id_credentials_get.csv') |

  Scenario: Get client credentials with invalid token
    Given path 'clients', 'client123', 'credentials'
    * configure headers = { Authorization: 'Bearer invalid_token' }
    When method GET
    Then status 401

  Scenario: Get client credentials with insufficient scope
    Given path 'clients', 'client123', 'credentials'
    * configure headers = { Authorization: 'Bearer insufficient_scope_token' }
    When method GET
    Then status 403

  Scenario: Get client credentials for non-existent client
    Given path 'clients', 'non_existent_client', 'credentials'
    When method GET
    Then status 404

  Scenario: Get client credentials with too many requests
    Given path 'clients', 'client123', 'credentials'
    * configure headers = { Authorization: 'Bearer rate_limit_exceeded_token' }
    When method GET
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'
