# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /clients/{client_id}/credentials_post for http method type POST 
# RoostTestHash=e91c788ccc
# 
# 

# ********RoostGPT********
Feature: Client Credential Management API

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Create a client credential with valid data
    Given path 'clients', '<client_id>', 'credentials'
    And request
      """
      { 
        "credential_type": "<credential_type>", 
        "name": "<name>", 
        "pem": "<pem>", 
        "alg": "<alg>", 
        "parse_expiry_from_cert": <parse_expiry_from_cert>, 
        "expires_at": "<expires_at>" 
      }
      """
    When method POST
    Then status 201
    And match response.id == '#string'
    And match response.name == '<name>'
    And match response.kid == '#string'
    And match response.alg == '<alg>'
    And match response.credential_type == '<credential_type>'
    And match response.created_at == '#string'
    And match response.updated_at == '#string'
    And match response.expires_at == '<expires_at>'

    Examples:
      | read('clients_client_id_credentials_post.csv') |

  Scenario Outline: Create a client credential with invalid data
    Given path 'clients', '<client_id>', 'credentials'
    And request
      """
      { 
        "credential_type": "<credential_type>", 
        "name": "<name>", 
        "pem": "<pem>", 
        "alg": "<alg>", 
        "parse_expiry_from_cert": <parse_expiry_from_cert>, 
        "expires_at": "<expires_at>" 
      }
      """
    When method POST
    Then status 400

    Examples:
      | client_id | credential_type | name     | pem                  | alg   | parse_expiry_from_cert | expires_at           |
      |     12345 | invalid_type    | Test Key | -----BEGIN PUBLIC... | RS256 | false                  | 2023-12-31T23:59:59Z |
      |     67890 | public_key      |          | -----BEGIN CERTIF... | RS384 | false                  | 2024-01-01T00:00:00Z |

  Scenario: Create a client credential with missing authorization
    * configure headers = {}
    Given path 'clients', '12345', 'credentials'
    And request
      """
      { 
        "credential_type": "public_key", 
        "name": "Test Key", 
        "pem": "-----BEGIN PUBLIC KEY-----\r\nMIIBIjANBg...\r\n-----END PUBLIC KEY-----\r\n", 
        "alg": "RS256", 
        "parse_expiry_from_cert": false, 
        "expires_at": "2023-12-31T23:59:59Z" 
      }
      """
    When method POST
    Then status 401

  Scenario: Create a client credential with insufficient scope
    * configure headers = { Authorization: 'Bearer ' + 'invalid_scope_token' }
    Given path 'clients', '12345', 'credentials'
    And request
      """
      { 
        "credential_type": "public_key", 
        "name": "Test Key", 
        "pem": "-----BEGIN PUBLIC KEY-----\r\nMIIBIjANBg...\r\n-----END PUBLIC KEY-----\r\n", 
        "alg": "RS256", 
        "parse_expiry_from_cert": false, 
        "expires_at": "2023-12-31T23:59:59Z" 
      }
      """
    When method POST
    Then status 403

  Scenario: Create a client credential for a non-existent client
    Given path 'clients', 'non_existent_client', 'credentials'
    And request
      """
      { 
        "credential_type": "public_key", 
        "name": "Test Key", 
        "pem": "-----BEGIN PUBLIC KEY-----\r\nMIIBIjANBg...\r\n-----END PUBLIC KEY-----\r\n", 
        "alg": "RS256", 
        "parse_expiry_from_cert": false, 
        "expires_at": "2023-12-31T23:59:59Z" 
      }
      """
    When method POST
    Then status 404

  Scenario: Rate limit exceeded when creating a client credential
    Given path 'clients', '12345', 'credentials'
    And request
      """
      { 
        "credential_type": "public_key", 
        "name": "Test Key", 
        "pem": "-----BEGIN PUBLIC KEY-----\r\nMIIBIjANBg...\r\n-----END PUBLIC KEY-----\r\n", 
        "alg": "RS256", 
        "parse_expiry_from_cert": false, 
        "expires_at": "2023-12-31T23:59:59Z" 
      }
      """
    When method POST
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'
