# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /clients_post for http method type POST 
# RoostTestHash=453a0b9a29
# 
# 

# ********RoostGPT********
Feature: Create Client API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Create a new client with valid input
    Given path 'clients'
    And request
      """
      { 
        "name": "<name>", 
        "description": "<description>", 
        "app_type": "<app_type>" 
      }
      """
    When method POST
    Then status 201
    And match response.client_id == '#string'
    And match response.tenant == '#string'
    And match response.name == '<name>'
    And match response.description == '<description>'
    And match response.global == '#boolean'
    And match response.client_secret == '#string'
    And match response.app_type == '<app_type>'
    And match response.logo_uri == '#string?'
    And match response.is_first_party == '#boolean'
    And match response.oidc_conformant == '#boolean'
    And match response.callbacks == '#[] string'
    And match response.allowed_origins == '#[] string'
    And match response.web_origins == '#[] string'
    And match response.client_aliases == '#[] string'
    And match response.allowed_clients == '#[] string'
    And match response.allowed_logout_urls == '#[] string'
    And match response.session_transfer == '#object?'
    And match response.oidc_logout == '#object?'
    And match response.grant_types == '#[] string'
    And match response.jwt_configuration == '#object'
    And match response.signing_keys == '#[] object'
    And match response.encryption_key == '#object?'
    And match response.sso == '#boolean'
    And match response.sso_disabled == '#boolean'
    And match response.cross_origin_authentication == '#boolean'
    And match response.cross_origin_loc == '#string?'
    And match response.custom_login_page_on == '#boolean'
    And match response.custom_login_page == '#string?'
    And match response.custom_login_page_preview == '#string?'
    And match response.form_template == '#string?'
    And match response.addons == '#object'
    And match response.token_endpoint_auth_method == '#string'
    And match response.client_metadata == '#object'
    And match response.mobile == '#object'
    And match response.initiate_login_uri == '#string?'
    And match response.native_social_login == '#object'
    And match response.refresh_token == '#object'
    And match response.default_organization == '#object?'
    And match response.organization_usage == '#string'
    And match response.organization_require_behavior == '#string'
    And match response.client_authentication_methods == '#object?'
    And match response.require_pushed_authorization_requests == '#boolean'
    And match response.require_proof_of_possession == '#boolean'
    And match response.signed_request_object == '#object'
    And match response.compliance_level == '#string?'
    And match response.par_request_expiry == '#number?'
    And match response.token_quota == '#object'

    Examples:
      | read('clients_post.csv') |

  Scenario: Create a client with missing required fields
    Given path 'clients'
    And request
      """
      { 
        "description": "Missing name" 
      }
      """
    When method POST
    Then status 400

  Scenario: Create a client with invalid token
    * configure headers = { Authorization: 'Bearer invalid_token' }
    Given path 'clients'
    And request
      """
      { 
        "name": "Invalid Token Client" 
      }
      """
    When method POST
    Then status 401

  Scenario: Create a client with insufficient scope
    * configure headers = { Authorization: 'Bearer insufficient_scope_token' }
    Given path 'clients'
    And request
      """
      { 
        "name": "Insufficient Scope Client" 
      }
      """
    When method POST
    Then status 403

  Scenario: Create a client with duplicate alias
    Given path 'clients'
    And request
      """
      { 
        "name": "Duplicate Alias Client", 
        "client_aliases": ["existing_alias"] 
      }
      """
    When method POST
    Then status 409

  Scenario: Create a client with too many requests
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    Given path 'clients'
    And request
      """
      { 
        "name": "Rate Limit Client" 
      }
      """
    When method POST
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'
