# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /clients_get for http method type GET 
# RoostTestHash=6bba9d8c2d
# 
# 

# ********RoostGPT********
Feature: Clients API

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Retrieve clients with valid query parameters
    Given path 'clients'
    And param fields = '<fields>'
    And param include_fields = <include_fields>
    And param page = <page>
    And param per_page = <per_page>
    And param include_totals = <include_totals>
    And param from = '<from>'
    And param take = <take>
    And param is_global = <is_global>
    And param is_first_party = <is_first_party>
    And param app_type = '<app_type>'
    And param q = '<q>'
    When method GET
    Then status 200
    And match response == '#array'
    And match response[*].client_id == '#string'
    And match response[*].tenant == '#string'
    And match response[*].name == '#string'
    And match response[*].description == '#string'
    And match response[*].global == '#boolean'
    And match response[*].client_secret == '#string'
    And match response[*].app_type == '#string'
    And match response[*].logo_uri == '#string?'
    And match response[*].is_first_party == '#boolean'
    And match response[*].oidc_conformant == '#boolean'
    And match response[*].callbacks == '#array'
    And match response[*].allowed_origins == '#array'
    And match response[*].web_origins == '#array'
    And match response[*].client_aliases == '#array'
    And match response[*].allowed_clients == '#array'
    And match response[*].allowed_logout_urls == '#array'
    And match response[*].session_transfer == '#object?'
    And match response[*].oidc_logout == '#object?'
    And match response[*].grant_types == '#array'
    And match response[*].jwt_configuration == '#object'
    And match response[*].signing_keys == '#array'
    And match response[*].encryption_key == '#object?'
    And match response[*].sso == '#boolean'
    And match response[*].sso_disabled == '#boolean'
    And match response[*].cross_origin_authentication == '#boolean'
    And match response[*].cross_origin_loc == '#string?'
    And match response[*].custom_login_page_on == '#boolean'
    And match response[*].custom_login_page == '#string'
    And match response[*].custom_login_page_preview == '#string'
    And match response[*].form_template == '#string'
    And match response[*].addons == '#object'
    And match response[*].token_endpoint_auth_method == '#string'
    And match response[*].client_metadata == '#object'
    And match response[*].mobile == '#object'
    And match response[*].initiate_login_uri == '#string?'
    And match response[*].native_social_login == '#object'
    And match response[*].refresh_token == '#object?'
    And match response[*].default_organization == '#object?'
    And match response[*].organization_usage == '#string'
    And match response[*].organization_require_behavior == '#string'
    And match response[*].client_authentication_methods == '#object?'
    And match response[*].require_pushed_authorization_requests == '#boolean'
    And match response[*].require_proof_of_possession == '#boolean'
    And match response[*].signed_request_object == '#object'
    And match response[*].compliance_level == '#string?'
    And match response[*].par_request_expiry == '#number?'
    And match response[*].token_quota == '#object'

    Examples:
      | read('clients_get.csv') |

  Scenario: Retrieve clients with invalid token
    Given path 'clients'
    * configure headers = { Authorization: 'Bearer invalid_token' }
    When method GET
    Then status 401

  Scenario: Retrieve clients with insufficient scope
    Given path 'clients'
    * configure headers = { Authorization: 'Bearer insufficient_scope_token' }
    When method GET
    Then status 403

  Scenario: Retrieve clients with too many requests
    Given path 'clients'
    When method GET
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'
