# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /client-grants/{id}/organizations_get for http method type GET 
# RoostTestHash=024d76a62b
# 
# 

# ********RoostGPT********
Feature: Client Grant Organizations API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Get organizations associated with a client grant
    Given path '/client-grants/<id>/organizations'
    And param page = <page>
    And param per_page = <per_page>
    And param include_totals = <include_totals>
    And param from = <from>
    And param take = <take>
    When method GET
    Then status 200
    And match response == '#object'
    And match response.organizations == '#array'
    And match response.organizations[*].id == '#string'
    And match response.organizations[*].name == '#string'
    And match response.organizations[*].display_name == '#string'
    And match response.organizations[*].branding == '#object'
    And match response.organizations[*].branding.logo_url == '#string'
    And match response.organizations[*].branding.colors == '#object'
    And match response.organizations[*].branding.colors.primary == '#string'
    And match response.organizations[*].branding.colors.page_background == '#string'
    And match response.organizations[*].metadata == '#object'
    And match response.organizations[*].token_quota == '#object'
    And match response.organizations[*].token_quota.client_credentials == '#object'
    And match response.organizations[*].token_quota.client_credentials.enforce == '#boolean'
    And match response.organizations[*].token_quota.client_credentials.per_day == '#number'
    And match response.organizations[*].token_quota.client_credentials.per_hour == '#number'

    Examples:
      | read('client-grants_id_organizations_get.csv') |

  Scenario: Invalid request query string
    Given path '/client-grants/invalid-id/organizations'
    When method GET
    Then status 400

  Scenario: Invalid token
    * configure headers = { Authorization: 'Bearer invalid_token' }
    Given path '/client-grants/grant123/organizations'
    When method GET
    Then status 401

  Scenario: Insufficient scope
    * configure headers = { Authorization: 'Bearer insufficient_scope_token' }
    Given path '/client-grants/grant123/organizations'
    When method GET
    Then status 403

  Scenario: Too many requests
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    Given path '/client-grants/grant123/organizations'
    When method GET
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'
