# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /client-grants/{id}_delete for http method type DELETE 
# RoostTestHash=4aa7c5e1db
# 
# 

# ********RoostGPT********
Feature: Delete Client Grant

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Delete client grant with valid ID
    Given path 'client-grants', '<id>'
    When method DELETE
    Then status 204

    Examples:
      | read('client-grants_id_delete.csv') |

  Scenario Outline: Delete client grant with invalid ID
    Given path 'client-grants', '<id>'
    When method DELETE
    Then status 400
    And match response == null

    Examples:
      | id           |
      | invalid-id-1 |
      | invalid-id-2 |

  Scenario: Delete client grant with invalid token
    * configure headers = { Authorization: 'Bearer invalid_token' }
    Given path 'client-grants', 'valid-id-1'
    When method DELETE
    Then status 401
    And match response == null

  Scenario: Delete client grant with insufficient scope
    * configure headers = { Authorization: 'Bearer insufficient_scope_token' }
    Given path 'client-grants', 'valid-id-1'
    When method DELETE
    Then status 403
    And match response == null

  Scenario: Delete client grant with too many requests
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    Given path 'client-grants', 'valid-id-1'
    When method DELETE
    Then status 429
    And match response == null
    And match responseHeaders contains { 'X-RateLimit-Limit': '#number', 'X-RateLimit-Remaining': '#number', 'X-RateLimit-Reset': '#number' }
