# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /client-grants/{id}_patch for http method type PATCH 
# RoostTestHash=ea41e67b38
# 
# 

# ********RoostGPT********
Feature: Update Client Grant API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Update client grant with valid data
    Given path 'client-grants', <id>
    And request
      """
      { 
        "scope": <scope>, 
        "organization_usage": <organization_usage>, 
        "allow_any_organization": <allow_any_organization> 
      }
      """
    When method PATCH
    Then status 200
    And match response ==
      """
      { 
        id: '#string', 
        client_id: '#string', 
        audience: '#string', 
        scope: '#[] string', 
        organization_usage: '#string', 
        allow_any_organization: '#boolean' 
      }
      """

    Examples:
      | read('client-grants_id_patch.csv') |

  Scenario Outline: Update client grant with invalid token
    Given path 'client-grants', <id>
    And request
      """
      { 
        "scope": <scope>, 
        "organization_usage": <organization_usage>, 
        "allow_any_organization": <allow_any_organization> 
      }
      """
    * configure headers = { Authorization: 'Bearer invalid_token' }
    When method PATCH
    Then status 401

    Examples:
      | id  | scope             | organization_usage | allow_any_organization |
      | 123 | ['read', 'write'] | 'allow'            | true                   |

  Scenario Outline: Update client grant with insufficient scope
    Given path 'client-grants', <id>
    And request
      """
      { 
        "scope": <scope>, 
        "organization_usage": <organization_usage>, 
        "allow_any_organization": <allow_any_organization> 
      }
      """
    * configure headers = { Authorization: 'Bearer ' + karate.properties['INSUFFICIENT_SCOPE_TOKEN'] }
    When method PATCH
    Then status 403

    Examples:
      | id  | scope             | organization_usage | allow_any_organization |
      | 123 | ['read', 'write'] | 'allow'            | true                   |

  Scenario Outline: Update client grant with non-existing id
    Given path 'client-grants', <id>
    And request
      """
      { 
        "scope": <scope>, 
        "organization_usage": <organization_usage>, 
        "allow_any_organization": <allow_any_organization> 
      }
      """
    When method PATCH
    Then status 404

    Examples:
      | id  | scope             | organization_usage | allow_any_organization |
      | 999 | ['read', 'write'] | 'allow'            | true                   |

  Scenario Outline: Update client grant with invalid request body
    Given path 'client-grants', <id>
    And request
      """
      { 
        "scope": <invalid_scope>, 
        "organization_usage": <organization_usage>, 
        "allow_any_organization": <allow_any_organization> 
      }
      """
    When method PATCH
    Then status 400

    Examples:
      | id  | invalid_scope | organization_usage | allow_any_organization |
      | 123 | []            | 'allow'            | true                   |

  Scenario Outline: Rate limit exceeded
    Given path 'client-grants', <id>
    And request
      """
      { 
        "scope": <scope>, 
        "organization_usage": <organization_usage>, 
        "allow_any_organization": <allow_any_organization> 
      }
      """
    * configure headers = { Authorization: 'Bearer ' + karate.properties['RATE_LIMIT_TOKEN'] }
    When method PATCH
    Then status 429
    And match responseHeaders contains
      """
      { 
        'X-RateLimit-Limit': '#number', 
        'X-RateLimit-Remaining': '#number', 
        'X-RateLimit-Reset': '#number' 
      }
      """

    Examples:
      | id  | scope             | organization_usage | allow_any_organization |
      | 123 | ['read', 'write'] | 'allow'            | true                   |
