# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /clients/{client_id}/credentials/{credential_id}_delete for http method type DELETE 
# RoostTestHash=a7a0d8dd5d
# 
# 

# ********RoostGPT********
Feature: Delete Client Credential API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Delete client credential with valid client_id and credential_id
    Given path 'clients', '<client_id>', 'credentials', '<credential_id>'
    When method DELETE
    Then status 204

    Examples:
      | read('clients_client_id_credentials_credential_id_delete.csv') |

  Scenario Outline: Delete client credential with invalid client_id or credential_id
    Given path 'clients', '<client_id>', 'credentials', '<credential_id>'
    When method DELETE
    Then status 400

    Examples:
      | client_id | credential_id |
      | invalid   | cred456       |
      | abc123    | invalid       |

  Scenario: Delete client credential with invalid token
    * configure headers = { Authorization: 'Bearer invalid_token' }
    Given path 'clients', 'abc123', 'credentials', 'cred456'
    When method DELETE
    Then status 401
    And match response == '#string'

  Scenario: Delete client credential with insufficient scope
    * configure headers = { Authorization: 'Bearer insufficient_scope_token' }
    Given path 'clients', 'abc123', 'credentials', 'cred456'
    When method DELETE
    Then status 403
    And match response == '#string'

  Scenario: Delete client credential with too many requests
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    Given path 'clients', 'abc123', 'credentials', 'cred456'
    When method DELETE
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'
