# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /client-grants_get for http method type GET 
# RoostTestHash=bc34ffb9e7
# 
# 

# ********RoostGPT********
Feature: Client Grants API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Retrieve client grants with valid parameters
    Given path 'client-grants'
    And param per_page = <per_page>
    And param page = <page>
    And param include_totals = <include_totals>
    And param from = <from>
    And param take = <take>
    And param audience = <audience>
    And param client_id = <client_id>
    And param allow_any_organization = <allow_any_organization>
    When method GET
    Then status 200
    And match response == '#[?(@.client_grants)]'
    And match each response.client_grants == '#array'
    And match each response.client_grants[*].id == '#string'
    And match each response.client_grants[*].client_id == '#string'
    And match each response.client_grants[*].audience == '#string'
    And match each response.client_grants[*].scope == '#array'
    And match each response.client_grants[*].organization_usage == '#string'
    And match each response.client_grants[*].allow_any_organization == '#boolean'

    Examples:
      | read('client-grants_get.csv') |

  Scenario: Invalid token
    Given path 'client-grants'
    * configure headers = { Authorization: 'Bearer invalid_token' }
    When method GET
    Then status 401

  Scenario: Insufficient scope
    Given path 'client-grants'
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN_WITHOUT_SCOPE'] }
    When method GET
    Then status 403

  Scenario: Too many requests
    Given path 'client-grants'
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    * repeat 100
    When method GET
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'
