# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /connections/{id}/scim-configuration/tokens_get for http method type GET 
# RoostTestHash=50c581d48f
# 
# 

# ********RoostGPT********
Feature: SCIM Tokens API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Retrieve SCIM Tokens for a Connection
    Given path 'connections', '<id>', 'scim-configuration', 'tokens'
    When method GET
    Then status 200
    And match response == '#[]'
    And match each response == '#object'
    And match each response.token_id == '#string'
    And match each response.scopes == '#[]'
    And match each response.scopes[*] == '#string'
    And match each response.created_at == '#string'
    And match each response.valid_until == '#string'
    And match each response.last_used_at == '#string'

    Examples:
      | read('connections_id_scim-configuration_tokens_get.csv') |

  Scenario Outline: Invalid Path Parameter
    Given path 'connections', '<id>', 'scim-configuration', 'tokens'
    When method GET
    Then status 400

    Examples:
      | id        |
      |           |
      | invalidId |

  Scenario Outline: Connection Does Not Exist
    Given path 'connections', '<id>', 'scim-configuration', 'tokens'
    When method GET
    Then status 404

    Examples:
      | id            |
      | nonExistentId |
