# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /connections/{id}/scim-configuration/default-mapping_get for http method type GET 
# RoostTestHash=60b6d9c06f
# 
# 

# ********RoostGPT********
Feature: Retrieve Default SCIM Mapping for a Connection

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Get default SCIM mapping with valid connection ID
    Given path 'connections', <id>, 'scim-configuration', 'default-mapping'
    When method GET
    Then status 200
    And match response == '#object'
    And match response.mapping == '#array'
    And match response.mapping[*].auth0 == '#string'
    And match response.mapping[*].scim == '#string'

    Examples:
      | read('connections_id_scim-configuration_default-mapping_get.csv') |

  Scenario Outline: Get default SCIM mapping with invalid connection ID
    Given path 'connections', <id>, 'scim-configuration', 'default-mapping'
    When method GET
    Then status 404

    Examples:
      | id       |
      | invalid1 |
      | invalid2 |

  Scenario Outline: Get default SCIM mapping with malformed connection ID
    Given path 'connections', <id>, 'scim-configuration', 'default-mapping'
    When method GET
    Then status 400

    Examples:
      | id         |
      | malformed! |
      |      123@# |
