# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /connections/{id}/scim-configuration_post for http method type POST 
# RoostTestHash=0ad3e02d10
# 
# 

# ********RoostGPT********
Feature: SCIM Configuration API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Create SCIM Configuration with Valid Payload
    Given path 'connections', '<id>', 'scim-configuration'
    And request
      """
      { 
        "user_id_attribute": '<user_id_attribute>', 
        "mapping": <mapping> 
      }
      """
    When method POST
    Then status 201
    And match response ==
      """
      { 
        connection_id: '#string', 
        connection_name: '#string', 
        strategy: '#string', 
        tenant_name: '#string', 
        user_id_attribute: '#string', 
        mapping: '#[]', 
        created_at: '#string', 
        updated_on: '#string' 
      }
      """
    And match response.mapping[*].auth0 == '#string'
    And match response.mapping[*].scim == '#string'

    Examples:
      | read('connections_id_scim-configuration_post.csv') |

  Scenario Outline: Create SCIM Configuration with Invalid Payload
    Given path 'connections', '<id>', 'scim-configuration'
    And request
      """
      { 
        "user_id_attribute": '<user_id_attribute>', 
        "mapping": <mapping> 
      }
      """
    When method POST
    Then status 400

    Examples:
      | id   | user_id_attribute | mapping                                    |
      | 1234 |                   | [{ "auth0": "email", "scim": "userName" }] |
      | 1234 | userId            | [{ "auth0": "", "scim": "userName" }]      |

  Scenario Outline: Create SCIM Configuration for Non-Existent Connection
    Given path 'connections', '<id>', 'scim-configuration'
    And request
      """
      { 
        "user_id_attribute": 'userId', 
        "mapping": [{ "auth0": "email", "scim": "userName" }] 
      }
      """
    When method POST
    Then status 404

    Examples:
      | id   |
      | 9999 |
