# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /connections/{id}/scim-configuration_delete for http method type DELETE 
# RoostTestHash=9844260d96
# 
# 

# ********RoostGPT********
Feature: Delete SCIM Configuration for a Connection

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Delete SCIM Configuration with valid connection ID
    Given path 'connections', '<id>', 'scim-configuration'
    When method DELETE
    Then status 204

    Examples:
      | read('connections_id_scim-configuration_delete.csv') |

  Scenario Outline: Delete SCIM Configuration with invalid connection ID
    Given path 'connections', '<id>', 'scim-configuration'
    When method DELETE
    Then status 404
    And match response == {}

    Examples:
      | id           |
      | invalid-id-1 |
      | invalid-id-2 |

  Scenario: Delete SCIM Configuration with missing connection ID
    Given path 'connections', '', 'scim-configuration'
    When method DELETE
    Then status 400
    And match response == {}
