# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /connections/{id}_get for http method type GET 
# RoostTestHash=b5e646e82e
# 
# 

# ********RoostGPT********
Feature: Test the /connections/{id} endpoint

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Retrieve connection details with valid ID
    Given path 'connections', '<id>'
    And param fields = '<fields>'
    And param include_fields = '<include_fields>'
    When method GET
    Then status 200
    And match response == '#object'
    And match response.name == '#string'
    And match response.display_name == '#string'
    And match response.options == '#object'
    And match response.id == '#string'
    And match response.strategy == '#string'
    And match response.realms == '#array'
    And match response.enabled_clients == '#array'
    And match response.is_domain_connection == '#boolean'
    And match response.show_as_button == '#boolean'
    And match response.metadata == '#object'

    Examples:
      | read('connections_id_get.csv') |

  Scenario: Invalid request URI
    Given path 'connections', 'invalid_id'
    When method GET
    Then status 400

  Scenario: Invalid token
    * configure headers = { Authorization: 'Bearer invalid_token' }
    Given path 'connections', 'con_0000000000000001'
    When method GET
    Then status 401

  Scenario: Insufficient scope
    * configure headers = { Authorization: 'Bearer insufficient_scope_token' }
    Given path 'connections', 'con_0000000000000001'
    When method GET
    Then status 403

  Scenario: Connection does not exist
    Given path 'connections', 'non_existent_id'
    When method GET
    Then status 404

  Scenario: Too many requests
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    Given path 'connections', 'con_0000000000000001'
    When method GET
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'
