# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /connections/{id}/users_delete for http method type DELETE 
# RoostTestHash=0be75def36
# 
# 

# ********RoostGPT********
Feature: Delete a connection user

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Delete a user from a connection
    Given path 'connections', '<id>', 'users'
    And param email = '<email>'
    When method DELETE
    Then status <status>
    And match response == <responseSchema>
    And match responseHeaders contains { 'Content-Type': '#string' }

    Examples:
      | id        | email              | status | responseSchema |
      | 'conn123' | 'user@example.com' | 204    | {}             |
      | 'conn123' | 'invalid@example'  | 400    | {}             |
      | 'conn123' | 'user@example.com' | 401    | {}             |
      | 'conn123' | 'user@example.com' | 403    | {}             |
      | 'conn123' | 'user@example.com' | 429    | {}             |

  Scenario: Validate response headers for rate limiting
    Given path 'connections', 'conn123', 'users'
    And param email = 'user@example.com'
    When method DELETE
    Then status 429
    And match responseHeaders contains { 
      'X-RateLimit-Limit': '#number', 
      'X-RateLimit-Remaining': '#number', 
      'X-RateLimit-Reset': '#number' 
    }
