# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /connections/{id}/clients_get for http method type GET 
# RoostTestHash=ea09a0d741
# 
# 

# ********RoostGPT********
Feature: Retrieve Enabled Clients for a Connection

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Get enabled clients for a connection with valid parameters
    Given path 'connections', '<id>', 'clients'
    And param take = <take>
    And param from = '<from>'
    When method GET
    Then status 200
    And match response.clients == '#[] clients'
    And match response.clients[*].client_id == '#[] string'
    And match response.next == '#string?'

    Examples:
      | read('connections_id_clients_get.csv') |

  Scenario: Get enabled clients for a connection with invalid token
    Given path 'connections', 'conn123', 'clients'
    * configure headers = { Authorization: 'Bearer invalid_token' }
    When method GET
    Then status 401

  Scenario: Get enabled clients for a connection with insufficient scope
    Given path 'connections', 'conn123', 'clients'
    * configure headers = { Authorization: 'Bearer insufficient_scope_token' }
    When method GET
    Then status 403

  Scenario: Get enabled clients for a non-existent connection
    Given path 'connections', 'nonexistent', 'clients'
    When method GET
    Then status 404

  Scenario: Get enabled clients for a connection with too many requests
    Given path 'connections', 'conn123', 'clients'
    When method GET
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'

  Scenario Outline: Get enabled clients for a connection with invalid query parameters
    Given path 'connections', '<id>', 'clients'
    And param take = <take>
    And param from = '<from>'
    When method GET
    Then status 400

    Examples:
      | id      | take | from |
      | conn123 |   -1 | ''   |
      | conn456 |    0 | abc  |
