# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /connections/{id}/scim-configuration_get for http method type GET 
# RoostTestHash=8bc6009d9d
# 
# 

# ********RoostGPT********
Feature: SCIM Configuration API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Retrieve SCIM Configuration with Valid ID
    Given path 'connections', '<id>', 'scim-configuration'
    When method GET
    Then status 200
    And match response == '#object'
    And match response.connection_id == '#string'
    And match response.connection_name == '#string'
    And match response.strategy == '#string'
    And match response.tenant_name == '#string'
    And match response.user_id_attribute == '#string'
    And match response.mapping == '#[]'
    And match response.mapping[*].auth0 == '#string'
    And match response.mapping[*].scim == '#string'
    And match response.created_at == '#string'
    And match response.updated_on == '#string'

    Examples:
      | read('connections_id_scim-configuration_get.csv') |

  Scenario Outline: Retrieve SCIM Configuration with Invalid ID
    Given path 'connections', '<id>', 'scim-configuration'
    When method GET
    Then status 404

    Examples:
      | id    |
      | abcde |
      | fghij |

  Scenario: Retrieve SCIM Configuration with Missing ID
    Given path 'connections', '', 'scim-configuration'
    When method GET
    Then status 400
