# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /connections_post for http method type POST 
# RoostTestHash=d0e3737b9d
# 
# 

# ********RoostGPT********
Feature: Connections API Testing

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Create a new connection with valid payload
    Given path 'connections'
    And request """ 
    { 
      "name": "<name>",
      "strategy": "<strategy>",
      "options": {
        "validation": {
          "username": {
            "min": <min>,
            "max": <max>
          }
        }
      }
    }
    """
    When method POST
    Then status 201
    And match response.name == '#string'
    And match response.display_name == '#string'
    And match response.options == '#object'
    And match response.id == '#string'
    And match response.strategy == '#string'
    And match response.realms == '#[] string'
    And match response.enabled_clients == '#[] string'
    And match response.is_domain_connection == '#boolean'
    And match response.show_as_button == '#boolean'
    And match response.metadata == '#object'

    Examples:
      | name          | strategy     | min | max |
      | test-conn-001 | auth0        | 5   | 15  |
      | test-conn-002 | google-oauth2| 3   | 10  |

  Scenario: Create a connection with missing required fields
    Given path 'connections'
    And request """ 
    { 
      "strategy": "auth0" 
    }
    """
    When method POST
    Then status 400

  Scenario: Create a connection with invalid token
    * configure headers = { Authorization: 'Bearer invalid_token' }
    Given path 'connections'
    And request """ 
    { 
      "name": "test-conn-003",
      "strategy": "auth0"
    }
    """
    When method POST
    Then status 401

  Scenario: Create a connection with insufficient scope
    * configure headers = { Authorization: 'Bearer insufficient_scope_token' }
    Given path 'connections'
    And request """ 
    { 
      "name": "test-conn-004",
      "strategy": "auth0"
    }
    """
    When method POST
    Then status 403

  Scenario: Create a connection with duplicate name
    Given path 'connections'
    And request """ 
    { 
      "name": "test-conn-001",
      "strategy": "auth0"
    }
    """
    When method POST
    Then status 409

  Scenario: Rate limit exceeded
    Given path 'connections'
    And request """ 
    { 
      "name": "test-conn-005",
      "strategy": "auth0"
    }
    """
    When method POST
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'
