# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /connections/{id}/scim-configuration/tokens_post for http method type POST 
# RoostTestHash=7f26298eba
# 
# 

# ********RoostGPT********
Feature: SCIM Token Management API

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Create SCIM Token with Valid Inputs
    Given path 'connections', '<id>', 'scim-configuration', 'tokens'
    And request
      """
      { 
        "scopes": <scopes>, 
        "token_lifetime": <token_lifetime> 
      }
      """
    When method POST
    Then status 201
    And match response == '#object'
    And match response.token_id == '#string'
    And match response.token == '#string'
    And match response.scopes == '#array'
    And match response.scopes[*] == '#string'
    And match response.created_at == '#string'
    And match response.valid_until == '#string'

    Examples:
      | read('connections_id_scim-configuration_tokens_post.csv') |

  Scenario Outline: Create SCIM Token with Invalid ID
    Given path 'connections', '<id>', 'scim-configuration', 'tokens'
    And request
      """
      { 
        "scopes": <scopes>, 
        "token_lifetime": <token_lifetime> 
      }
      """
    When method POST
    Then status 404

    Examples:
      | id    | scopes            | token_lifetime |
      | "999" | ["read", "write"] |           3600 |

  Scenario Outline: Create SCIM Token with Invalid Token Lifetime
    Given path 'connections', '<id>', 'scim-configuration', 'tokens'
    And request
      """
      { 
        "scopes": <scopes>, 
        "token_lifetime": <token_lifetime> 
      }
      """
    When method POST
    Then status 400

    Examples:
      | id    | scopes            | token_lifetime |
      | "123" | ["read", "write"] |            800 |

  Scenario Outline: Create SCIM Token Exceeding Limit
    Given path 'connections', '<id>', 'scim-configuration', 'tokens'
    And request
      """
      { 
        "scopes": <scopes>, 
        "token_lifetime": <token_lifetime> 
      }
      """
    When method POST
    Then status 409

    Examples:
      | id    | scopes            | token_lifetime |
      | "123" | ["read", "write"] |           3600 |
