# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /connections/{id}/clients_patch for http method type PATCH 
# RoostTestHash=1347276111
# 
# 

# ********RoostGPT********
Feature: Update enabled clients for a connection

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Update clients with valid data
    Given path 'connections', '<id>', 'clients'
    And request [{ "client_id": '<client_id>', "status": <status> }]
    When method PATCH
    Then status 204

    Examples:
      | read('connections_id_clients_patch.csv') |

  Scenario Outline: Invalid request URI
    Given path 'connections', '<id>', 'clients'
    And request [{ "client_id": '<client_id>', "status": <status> }]
    When method PATCH
    Then status 400
    And match response == '#string'

    Examples:
      | id      | client_id | status |
      | invalid | client1   | true   |

  Scenario Outline: Invalid token
    * configure headers = { Authorization: 'Bearer ' + 'invalid_token' }
    Given path 'connections', '<id>', 'clients'
    And request [{ "client_id": '<client_id>', "status": <status> }]
    When method PATCH
    Then status 401
    And match response == '#string'

    Examples:
      | id      | client_id | status |
      | conn123 | client1   | true   |

  Scenario Outline: Insufficient scope
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    Given path 'connections', '<id>', 'clients'
    And request [{ "client_id": '<client_id>', "status": <status> }]
    When method PATCH
    Then status 403
    And match response == '#string'

    Examples:
      | id      | client_id | status |
      | conn123 | client1   | true   |

  Scenario Outline: Connection does not exist
    Given path 'connections', '<id>', 'clients'
    And request [{ "client_id": '<client_id>', "status": <status> }]
    When method PATCH
    Then status 404
    And match response == '#string'

    Examples:
      | id          | client_id | status |
      | nonexistent | client1   | true   |

  Scenario Outline: Too many requests
    Given path 'connections', '<id>', 'clients'
    And request [{ "client_id": '<client_id>', "status": <status> }]
    When method PATCH
    Then status 429
    And match responseHeaders contains { 'X-RateLimit-Limit': '#number', 'X-RateLimit-Remaining': '#number', 'X-RateLimit-Reset': '#number' }

    Examples:
      | id      | client_id | status |
      | conn123 | client1   | true   |
