# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /connections/{id}_patch for http method type PATCH 
# RoostTestHash=defbcbe357
# 
# 

# ********RoostGPT********
Feature: Update Connection API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Update connection with valid payload
    Given path 'connections', <id>
    And request
      """
      { 
        "display_name": <display_name>, 
        "options": <options> 
      }
      """
    When method PATCH
    Then status 200
    And match response == '#object'
    And match response.name == '#string'
    And match response.display_name == '#string'
    And match response.options == '#object'
    And match response.id == '#string'
    And match response.strategy == '#string'
    And match response.realms == '#[] string'
    And match response.enabled_clients == '#[] string'
    And match response.is_domain_connection == '#boolean'
    And match response.show_as_button == '#boolean'
    And match response.metadata == '#object'

    Examples:
      | read('connections_id_patch.csv') |

  Scenario Outline: Update connection with invalid token
    Given path 'connections', <id>
    And request
      """
      { 
        "display_name": <display_name>, 
        "options": <options> 
      }
      """
    * configure headers = { Authorization: 'Bearer invalid_token' }
    When method PATCH
    Then status 401
    And match response == '#object'
    And match response.error == '#string'

    Examples:
      | id                  | display_name | options                                                   |
      | 'con_0000000000001' | 'New Name'   | { "validation": { "username": { "min": 3, "max": 10 } } } |

  Scenario Outline: Update connection with insufficient scope
    Given path 'connections', <id>
    And request
      """
      { 
        "display_name": <display_name>, 
        "options": <options> 
      }
      """
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN_WITHOUT_SCOPE'] }
    When method PATCH
    Then status 403
    And match response == '#object'
    And match response.error == '#string'

    Examples:
      | id                  | display_name | options                                                   |
      | 'con_0000000000001' | 'New Name'   | { "validation": { "username": { "min": 3, "max": 10 } } } |

  Scenario Outline: Update non-existent connection
    Given path 'connections', <id>
    And request
      """
      { 
        "display_name": <display_name>, 
        "options": <options> 
      }
      """
    When method PATCH
    Then status 404
    And match response == '#object'
    And match response.error == '#string'

    Examples:
      | id                 | display_name | options                                                   |
      | 'con_non_existent' | 'New Name'   | { "validation": { "username": { "min": 3, "max": 10 } } } |

  Scenario Outline: Update connection with invalid payload
    Given path 'connections', <id>
    And request
      """
      { 
        "display_name": <display_name>, 
        "options": <options> 
      }
      """
    When method PATCH
    Then status 400
    And match response == '#object'
    And match response.error == '#string'

    Examples:
      | id                  | display_name | options                                                    |
      | 'con_0000000000001' | 'New Name'   | { "validation": { "username": { "min": -1, "max": 10 } } } |

  Scenario Outline: Update connection with rate limit exceeded
    Given path 'connections', <id>
    And request
      """
      { 
        "display_name": <display_name>, 
        "options": <options> 
      }
      """
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN_RATE_LIMIT'] }
    When method PATCH
    Then status 429
    And match response == '#object'
    And match response.error == '#string'

    Examples:
      | id                  | display_name | options                                                   |
      | 'con_0000000000001' | 'New Name'   | { "validation": { "username": { "min": 3, "max": 10 } } } |
