# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /connections/{id}/scim-configuration/tokens/{tokenId}_delete for http method type DELETE 
# RoostTestHash=2f10b14c87
# 
# 

# ********RoostGPT********
Feature: Delete a connection's SCIM token

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Delete SCIM token with valid connection id and token id
    Given path 'connections', '<id>', 'scim-configuration', 'tokens', '<tokenId>'
    When method DELETE
    Then status 204

    Examples:
      | read('connections_id_scim-configuration_tokens_tokenId_delete.csv') |

  Scenario Outline: Attempt to delete SCIM token with invalid path parameters
    Given path 'connections', '<id>', 'scim-configuration', 'tokens', '<tokenId>'
    When method DELETE
    Then status 400

    Examples:
      | id      | tokenId  |
      | invalid | token456 |

  Scenario Outline: Attempt to delete SCIM token for non-existent connection
    Given path 'connections', '<id>', 'scim-configuration', 'tokens', '<tokenId>'
    When method DELETE
    Then status 404

    Examples:
      | id          | tokenId  |
      | nonexistent | token456 |
