# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /connections/{id}/status_get for http method type GET 
# RoostTestHash=44f7fc6347
# 
# 

# ********RoostGPT********
Feature: Connection Status API

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Check connection status with valid ID
    Given path 'connections', '<id>', 'status'
    When method GET
    Then status 200
    And match response == '#object'
    And match response.status == '#string'
    And match response.details == '#string'

    Examples:
      | read('connections_id_status_get.csv') |

  Scenario Outline: Check connection status with invalid ID
    Given path 'connections', '<id>', 'status'
    When method GET
    Then status 404
    And match response == '#object'
    And match response.error == '#string'
    And match response.message == '#string'

    Examples:
      | id         |
      | invalid-id |

  Scenario: Check connection status with missing authorization
    * configure headers = {}
    Given path 'connections', 'valid-id', 'status'
    When method GET
    Then status 401
    And match response == '#object'
    And match response.error == '#string'
    And match response.message == '#string'

  Scenario: Check connection status with insufficient scope
    * configure headers = { Authorization: 'Bearer ' + karate.properties['INSUFFICIENT_SCOPE_TOKEN'] }
    Given path 'connections', 'valid-id', 'status'
    When method GET
    Then status 403
    And match response == '#object'
    And match response.error == '#string'
    And match response.message == '#string'

  Scenario: Check connection status with too many requests
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    Given path 'connections', 'valid-id', 'status'
    When method GET
    Then status 429
    And match response == '#object'
    And match response.error == '#string'
    And match response.message == '#string'
    And match response.headers['X-RateLimit-Limit'] == '#number'
    And match response.headers['X-RateLimit-Remaining'] == '#number'
    And match response.headers['X-RateLimit-Reset'] == '#number'
