# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /connections_get for http method type GET 
# RoostTestHash=925e69c121
# 
# 

# ********RoostGPT********
Feature: Connections API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Get all connections with valid parameters
    Given path 'connections'
    And param per_page = <per_page>
    And param page = <page>
    And param include_totals = <include_totals>
    And param from = <from>
    And param take = <take>
    And param strategy = <strategy>
    And param name = <name>
    And param fields = <fields>
    And param include_fields = <include_fields>
    When method GET
    Then status 200
    And match response == '#array'
    And match response[*].name == '#string'
    And match response[*].display_name == '#string'
    And match response[*].options == '#object'
    And match response[*].id == '#string'
    And match response[*].strategy == '#string'
    And match response[*].realms == '#array'
    And match response[*].realms[*] == '#string'
    And match response[*].is_domain_connection == '#boolean'
    And match response[*].show_as_button == '#boolean'
    And match response[*].metadata == '#object'

    Examples:
      | read('connections_get.csv') |

  Scenario: Get all connections with invalid token
    Given path 'connections'
    And configure headers = { Authorization: 'Bearer invalid_token' }
    When method GET
    Then status 401

  Scenario: Get all connections with insufficient scope
    Given path 'connections'
    And configure headers = { Authorization: 'Bearer insufficient_scope_token' }
    When method GET
    Then status 403

  Scenario: Get all connections with too many requests
    Given path 'connections'
    And configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    When method GET
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'

  Scenario: Get all connections with invalid query
    Given path 'connections'
    And param per_page = 'invalid'
    When method GET
    Then status 400
