# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /connections/{id}/scim-configuration_patch for http method type PATCH 
# RoostTestHash=8225a5b090
# 
# 

# ********RoostGPT********
Feature: Patch a connection's SCIM configuration

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Update SCIM configuration with valid payload
    Given path 'connections', <id>, 'scim-configuration'
    And request
      """
      { 
        "user_id_attribute": "<user_id_attribute>", 
        "mapping": <mapping> 
      }
      """
    When method PATCH
    Then status 200
    And match response == '#object'
    And match response.connection_id == '<id>'
    And match response.connection_name == '#string'
    And match response.strategy == '#string'
    And match response.tenant_name == '#string'
    And match response.user_id_attribute == '<user_id_attribute>'
    And match response.mapping == '#array'
    And match response.mapping[*].auth0 == '#string'
    And match response.mapping[*].scim == '#string'
    And match response.created_at == '#string'
    And match response.updated_on == '#string'

    Examples:
      | read('connections_id_scim-configuration_patch.csv') |

  Scenario Outline: Update SCIM configuration with invalid mapping
    Given path 'connections', <id>, 'scim-configuration'
    And request
      """
      { 
        "user_id_attribute": "<user_id_attribute>", 
        "mapping": <mapping> 
      }
      """
    When method PATCH
    Then status 400

    Examples:
      | id  | user_id_attribute | mapping                       |
      | 123 | user_id           | [{ "auth0": "", "scim": "" }] |

  Scenario Outline: Update SCIM configuration for non-existent connection
    Given path 'connections', <id>, 'scim-configuration'
    And request
      """
      { 
        "user_id_attribute": "<user_id_attribute>", 
        "mapping": <mapping> 
      }
      """
    When method PATCH
    Then status 404

    Examples:
      | id  | user_id_attribute | mapping                                                                                |
      | 999 | user_id           | [{ "auth0": "email", "scim": "userName" }, { "auth0": "name", "scim": "displayName" }] |
