# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /custom-domains_post for http method type POST 
# RoostTestHash=4049273b33
# 
# 

# ********RoostGPT********
Feature: Custom Domains API

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Create a new custom domain with valid input
    Given path '/custom-domains'
    And request
      """
      { 
        "domain": "<domain>", 
        "type": "<type>", 
        "verification_method": "<verification_method>", 
        "tls_policy": "<tls_policy>", 
        "custom_client_ip_header": "<custom_client_ip_header>" 
      }
      """
    When method POST
    Then status 201
    And match response.custom_domain_id == '#string'
    And match response.domain == '<domain>'
    And match response.primary == '#boolean'
    And match response.status == '#string'
    And match response.type == '<type>'
    And match response.verification.methods == '#array'
    And match response.verification.methods[0].name == '#string'
    And match response.verification.methods[0].record == '#string'
    And match response.verification.methods[0].domain == '#string'
    And match response.custom_client_ip_header == '#string?'
    And match response.tls_policy == '#string'

    Examples:
      | read('custom-domains_post.csv') |

  Scenario: Create a new custom domain with invalid token
    Given path '/custom-domains'
    And request
      """
      { 
        "domain": "invalid.mycompany.com", 
        "type": "auth0_managed_certs", 
        "verification_method": "txt", 
        "tls_policy": "recommended", 
        "custom_client_ip_header": "true-client-ip" 
      }
      """
    * configure headers = { Authorization: 'Bearer invalid_token' }
    When method POST
    Then status 401

  Scenario: Create a new custom domain with insufficient scope
    Given path '/custom-domains'
    And request
      """
      { 
        "domain": "scope.mycompany.com", 
        "type": "auth0_managed_certs", 
        "verification_method": "txt", 
        "tls_policy": "recommended", 
        "custom_client_ip_header": "true-client-ip" 
      }
      """
    * configure headers = { Authorization: 'Bearer ' + karate.properties['INSUFFICIENT_SCOPE_TOKEN'] }
    When method POST
    Then status 403

  Scenario: Create a new custom domain that already exists
    Given path '/custom-domains'
    And request
      """
      { 
        "domain": "existing.mycompany.com", 
        "type": "auth0_managed_certs", 
        "verification_method": "txt", 
        "tls_policy": "recommended", 
        "custom_client_ip_header": "true-client-ip" 
      }
      """
    When method POST
    Then status 409

  Scenario: Create a new custom domain with too many requests
    Given path '/custom-domains'
    And request
      """
      { 
        "domain": "rate.mycompany.com", 
        "type": "auth0_managed_certs", 
        "verification_method": "txt", 
        "tls_policy": "recommended", 
        "custom_client_ip_header": "true-client-ip" 
      }
      """
    When method POST
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'
