# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /custom-domains/{id}/verify_post for http method type POST 
# RoostTestHash=f6987c4f34
# 
# 

# ********RoostGPT********
Feature: Verify Custom Domain API

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Verify custom domain with valid ID
    Given path '/custom-domains/<id>/verify'
    When method POST
    Then status <status_code>
    And match response.custom_domain_id == '#string'
    And match response.domain == '#string'
    And match response.primary == '#boolean'
    And match response.status == '#string'
    And match response.status in ['disabled', 'pending', 'pending_verification', 'ready']
    And match response.type == '#string'
    And match response.type in ['auth0_managed_certs', 'self_managed_certs']
    And match response.cname_api_key == '#string'
    And match response.origin_domain_name == '#string'
    And match response.verification.methods == '#[]'
    And match response.verification.methods[0].name == '#string'
    And match response.verification.methods[0].name in ['cname', 'txt']
    And match response.verification.methods[0].record == '#string'
    And match response.verification.methods[0].domain == '#string'
    And match response.custom_client_ip_header == '#string?'
    And match response.tls_policy == '#string'

    Examples:
      | id                  | status_code |
      | cd_0000000000000001 |         200 |

  Scenario Outline: Verify custom domain with invalid ID
    Given path '/custom-domains/<id>/verify'
    When method POST
    Then status <status_code>

    Examples:
      | id         | status_code |
      | invalid_id |         404 |

  Scenario Outline: Verify custom domain with insufficient scope
    Given path '/custom-domains/<id>/verify'
    When method POST
    Then status <status_code>

    Examples:
      | id                  | status_code |
      | cd_0000000000000001 |         403 |

  Scenario Outline: Verify custom domain with invalid token
    * configure headers = { Authorization: 'Bearer invalid_token' }
    Given path '/custom-domains/<id>/verify'
    When method POST
    Then status <status_code>

    Examples:
      | id                  | status_code |
      | cd_0000000000000001 |         401 |

  Scenario Outline: Verify custom domain with too many requests
    Given path '/custom-domains/<id>/verify'
    When method POST
    Then status <status_code>
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'

    Examples:
      | id                  | status_code |
      | cd_0000000000000001 |         429 |
