# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /custom-domains/{id}_get for http method type GET 
# RoostTestHash=70b508ed07
# 
# 

# ********RoostGPT********
Feature: Custom Domain Configuration API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Retrieve Custom Domain Configuration - Valid ID
    Given path 'custom-domains', '<id>'
    When method GET
    Then status 200
    And match response == '#object'
    And match response.custom_domain_id == '#string'
    And match response.domain == '#string'
    And match response.primary == '#boolean'
    And match response.status == '#string'
    And response.status in ['disabled', 'pending', 'pending_verification', 'ready']
    And match response.type == '#string'
    And response.type in ['auth0_managed_certs', 'self_managed_certs']
    And match response.origin_domain_name == '#string'
    And match response.verification == '#object'
    And match response.verification.methods == '#[]'
    And match response.verification.methods[0].name == '#string'
    And response.verification.methods[0].name in ['cname', 'txt']
    And match response.verification.methods[0].record == '#string'
    And match response.verification.methods[0].domain == '#string'
    And match response.custom_client_ip_header == '#string?'
    And match response.tls_policy == '#string'

    Examples:
      | read('custom-domains_id_get.csv') |

  Scenario Outline: Retrieve Custom Domain Configuration - Invalid ID
    Given path 'custom-domains', '<id>'
    When method GET
    Then status 404

    Examples:
      | id         |
      | invalid_id |

  Scenario: Retrieve Custom Domain Configuration - Invalid Token
    * configure headers = { Authorization: 'Bearer invalid_token' }
    Given path 'custom-domains', 'cd_0000000000000001'
    When method GET
    Then status 401

  Scenario: Retrieve Custom Domain Configuration - Insufficient Scope
    * configure headers = { Authorization: 'Bearer insufficient_scope_token' }
    Given path 'custom-domains', 'cd_0000000000000001'
    When method GET
    Then status 403

  Scenario: Retrieve Custom Domain Configuration - Too Many Requests
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    Given path 'custom-domains', 'cd_0000000000000001'
    When method GET
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'
