# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /custom-domains_get for http method type GET 
# RoostTestHash=5364879c73
# 
# 

# ********RoostGPT********
Feature: Custom Domains API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario: Retrieve custom domains successfully
    Given path 'custom-domains'
    When method GET
    Then status 200
    And match response == '#[] customDomains'
    And match each response == '#object'
    And match each response.custom_domain_id == '#string'
    And match each response.domain == '#string'
    And match each response.primary == '#boolean'
    And match each response.status == '#string'
    And match each response.status in ['disabled', 'pending', 'pending_verification', 'ready']
    And match each response.type == '#string'
    And match each response.type in ['auth0_managed_certs', 'self_managed_certs']
    And match each response.origin_domain_name == '#string'
    And match each response.verification == '#object'
    And match each response.verification.methods == '#[]'
    And match each response.verification.methods[*].name == '#string'
    And match each response.verification.methods[*].name in ['cname', 'txt']
    And match each response.verification.methods[*].record == '#string'
    And match each response.verification.methods[*].domain == '#string'
    And match each response.custom_client_ip_header == '#string?'
    And match each response.tls_policy == '#string'

  Scenario: Invalid token
    Given path 'custom-domains'
    And configure headers = { Authorization: 'Bearer invalid_token' }
    When method GET
    Then status 401

  Scenario: Insufficient scope
    Given path 'custom-domains'
    And configure headers = { Authorization: 'Bearer insufficient_scope_token' }
    When method GET
    Then status 403

  Scenario: Too many requests
    Given path 'custom-domains'
    And configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    And def rateLimitHeaders = { 'X-RateLimit-Limit': 100, 'X-RateLimit-Remaining': 0, 'X-RateLimit-Reset': 60 }
    And configure headers = rateLimitHeaders
    When method GET
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == 100
    And match responseHeaders['X-RateLimit-Remaining'] == 0
    And match responseHeaders['X-RateLimit-Reset'] == 60
