# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /custom-domains/{id}_patch for http method type PATCH 
# RoostTestHash=1b40a07192
# 
# 

# ********RoostGPT********
Feature: Update Custom Domain Configuration

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Update custom domain with valid payload
    Given path '/custom-domains/<id>'
    And request """ 
    { 
      "custom_client_ip_header": "<custom_client_ip_header>", 
      "tls_policy": "<tls_policy>" 
    }
    """
    When method PATCH
    Then status 200
    And match response.custom_domain_id == '#string'
    And match response.domain == '#string'
    And match response.primary == '#boolean'
    And match response.status == '#string'
    And match response.type == '#string'
    And match response.verification.methods == '#array'
    And match response.verification.methods[*].name == '#string'
    And match response.verification.methods[*].record == '#string'
    And match response.verification.methods[*].domain == '#string'
    And match response.custom_client_ip_header == '#string'
    And match response.tls_policy == '#string'

    Examples:
      | id  | custom_client_ip_header | tls_policy  |
      | 123 | cf-connecting-ip        | recommended |
      | 456 | x-forwarded-for         | recommended |

  Scenario: Invalid request body - TLS policy on self-managed domains
    Given path '/custom-domains/789'
    And request """
    { 
      "tls_policy": "invalid_policy" 
    }
    """
    When method PATCH
    Then status 400

  Scenario: Invalid token
    * configure headers = { Authorization: 'Bearer invalid_token' }
    Given path '/custom-domains/123'
    And request """
    { 
      "custom_client_ip_header": "cf-connecting-ip" 
    }
    """
    When method PATCH
    Then status 401

  Scenario: Insufficient scope
    * configure headers = { Authorization: 'Bearer insufficient_scope_token' }
    Given path '/custom-domains/123'
    And request """
    { 
      "custom_client_ip_header": "cf-connecting-ip" 
    }
    """
    When method PATCH
    Then status 403

  Scenario: Too many requests
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    Given path '/custom-domains/123'
    And request """
    { 
      "custom_client_ip_header": "cf-connecting-ip" 
    }
    """
    When method PATCH
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'
