# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /device-credentials_post for http method type POST 
# RoostTestHash=1b6af17e75
# 
# 

# ********RoostGPT********
Feature: Device Credentials API

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Create device public key credential with valid input
    Given path 'device-credentials'
    And request
      """
      { 
        device_name: '<device_name>', 
        type: '<type>', 
        value: '<value>', 
        device_id: '<device_id>', 
        client_id: '<client_id>' 
      }
      """
    When method POST
    Then status 201
    And match response == '#object'
    And match response.id == '#string'

    Examples:
      | read('device-credentials_post.csv') |

  Scenario Outline: Create device public key credential with missing required fields
    Given path 'device-credentials'
    And request
      """
      { 
        device_name: '<device_name>', 
        type: '<type>', 
        value: '<value>', 
        device_id: '<device_id>' 
      }
      """
    When method POST
    Then status 400

    Examples:
      | device_name | type       | value        | device_id                            |
      |             | public_key | dGVzdFZhbHVl | 123e4567-e89b-12d3-a456-426614174000 |
      | Device1     |            | dGVzdFZhbHVl | 123e4567-e89b-12d3-a456-426614174000 |
      | Device1     | public_key |              | 123e4567-e89b-12d3-a456-426614174000 |
      | Device1     | public_key | dGVzdFZhbHVl |                                      |

  Scenario: Create device public key credential with invalid token
    Given path 'device-credentials'
    * configure headers = { Authorization: 'Bearer invalid_token' }
    And request
      """
      { 
        device_name: 'Device1', 
        type: 'public_key', 
        value: 'dGVzdFZhbHVl', 
        device_id: '123e4567-e89b-12d3-a456-426614174000', 
        client_id: 'client_123' 
      }
      """
    When method POST
    Then status 401

  Scenario: Create device public key credential with insufficient scope
    Given path 'device-credentials'
    * configure headers = { Authorization: 'Bearer ' + karate.properties['INSUFFICIENT_SCOPE_TOKEN'] }
    And request
      """
      { 
        device_name: 'Device1', 
        type: 'public_key', 
        value: 'dGVzdFZhbHVl', 
        device_id: '123e4567-e89b-12d3-a456-426614174000', 
        client_id: 'client_123' 
      }
      """
    When method POST
    Then status 403

  Scenario: Create device public key credential when a public key already exists
    Given path 'device-credentials'
    And request
      """
      { 
        device_name: 'Device1', 
        type: 'public_key', 
        value: 'dGVzdFZhbHVl', 
        device_id: '123e4567-e89b-12d3-a456-426614174000', 
        client_id: 'client_123' 
      }
      """
    When method POST
    Then status 409

  Scenario: Create device public key credential with too many requests
    Given path 'device-credentials'
    And request
      """
      { 
        device_name: 'Device1', 
        type: 'public_key', 
        value: 'dGVzdFZhbHVl', 
        device_id: '123e4567-e89b-12d3-a456-426614174000', 
        client_id: 'client_123' 
      }
      """
    When method POST
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'
