# ********RoostGPT********

# Test generated by RoostGPT for test xcally-vidaoo using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /device-credentials_get for http method type GET 
# RoostTestHash=4d4975e576
# 
# 

# ********RoostGPT********
Feature: Device Credentials API

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Retrieve device credentials with valid parameters
    Given path 'device-credentials'
    And param page = <page>
    And param per_page = <per_page>
    And param include_totals = <include_totals>
    And param fields = '<fields>'
    And param include_fields = <include_fields>
    And param user_id = '<user_id>'
    And param client_id = '<client_id>'
    And param type = '<type>'
    When method GET
    Then status 200
    And match response == '#object'
    And match response.device_credentials == '#array'
    And match response.device_credentials[*].id == '#string'
    And match response.device_credentials[*].device_name == '#string'
    And match response.device_credentials[*].device_id == '#string'
    And match response.device_credentials[*].type == '#string'
    And match response.device_credentials[*].user_id == '#string'
    And match response.device_credentials[*].client_id == '#string'
    And match response.start == '#number'
    And match response.limit == '#number'
    And match response.total == '#number'

    Examples:
      | read('device-credentials_get.csv') |

  Scenario: Invalid request query string
    Given path 'device-credentials'
    And param page = -1
    When method GET
    Then status 400

  Scenario: Invalid token
    * configure headers = { Authorization: 'Bearer invalid_token' }
    Given path 'device-credentials'
    When method GET
    Then status 401

  Scenario: Insufficient scope
    * configure headers = { Authorization: 'Bearer ' + karate.properties['INSUFFICIENT_SCOPE_TOKEN'] }
    Given path 'device-credentials'
    When method GET
    Then status 403

  Scenario: Too many requests
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }
    Given path 'device-credentials'
    When method GET
    Then status 429
    And match responseHeaders['X-RateLimit-Limit'] == '#number'
    And match responseHeaders['X-RateLimit-Remaining'] == '#number'
    And match responseHeaders['X-RateLimit-Reset'] == '#number'
