# ********RoostGPT********

# Test generated by RoostGPT for test xcally-karate using AI Type Claude AI and AI Model claude-sonnet-4-20250514
# 
# Feature file generated for /auth/local/reset/{token}_post for http method type POST 
# RoostTestHash=6688bb3a38
# 
# 

# ********RoostGPT********
Feature: Reset user password

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * def basicAuth = karate.properties['BASIC_AUTH']
    * header Authorization = basicAuth
    * header Accept = application/json
    * header Content-Type = application/json

  Scenario Outline: Reset user password with valid token and password
    Given path '/auth/local/reset/<token>'
    And request { password: '<password>' }
    When method POST
    Then status 201

    Examples:
      | read('auth_local_reset_token_post.csv') |

  Scenario Outline: Reset user password with invalid token
    Given path '/auth/local/reset/<token>'
    And request { password: '<password>' }
    When method POST
    Then assert responseStatus != 200

    Examples:
      | token           | password          |
      | invalid_token   | newPassword123    |
      | expired_token   | strongPassword456 |
      | malformed_token | myNewSecurePass   |

  Scenario Outline: Reset user password with missing password field
    Given path '/auth/local/reset/<token>'
    And request {}
    When method POST
    Then assert responseStatus != 200

    Examples:
      | token                 |
      | valid_reset_token_123 |
      | another_valid_token   |

  Scenario Outline: Reset user password with empty password
    Given path '/auth/local/reset/<token>'
    And request { password: '<password>' }
    When method POST
    Then assert responseStatus != 200

    Examples:
      | token                 | password |
      | valid_reset_token_123 |          |
      | another_valid_token   |          |

  Scenario Outline: Reset user password with null password
    Given path '/auth/local/reset/<token>'
    And request { password: null }
    When method POST
    Then assert responseStatus != 200

    Examples:
      | token                 |
      | valid_reset_token_123 |
      | another_valid_token   |

  Scenario Outline: Reset user password - Internal server error
    Given path '/auth/local/reset/<token>'
    And request { password: '<password>' }
    When method POST
    Then status 500
    And match response.code == '#number'
    And match response.code == 500
    And match response.message == '#string'
    And match response.stack == '##string'
    And match response.details == '##object'

    Examples:
      | token               | password          |
      | server_error_token  | newPassword123    |
      | error_trigger_token | strongPassword456 |

  Scenario Outline: Reset user password with additional invalid fields
    Given path '/auth/local/reset/<token>'
    And request { password: '<password>', invalidField: 'invalidValue' }
    When method POST
    Then status 201

    Examples:
      | read('auth_local_reset_token_post.csv') |

  Scenario Outline: Reset user password with special characters in password
    Given path '/auth/local/reset/<token>'
    And request { password: '<password>' }
    When method POST
    Then status 201

    Examples:
      | read('auth_local_reset_token_post.csv') |

  Scenario Outline: Reset user password with very long password
    Given path '/auth/local/reset/<token>'
    And request { password: '<password>' }
    When method POST
    Then status 201

    Examples:
      | read('auth_local_reset_token_post.csv') |

  Scenario Outline: Reset user password with numeric password
    Given path '/auth/local/reset/<token>'
    And request { password: '<password>' }
    When method POST
    Then status 201

    Examples:
      | read('auth_local_reset_token_post.csv') |
