# ********RoostGPT********

# Test generated by RoostGPT for test xcally-karate using AI Type Claude AI and AI Model claude-sonnet-4-20250514
# 
# Feature file generated for /auth/local_post for http method type POST 
# RoostTestHash=e8552a370b
# 
# 

# ********RoostGPT********
Feature: Authentication Local Login API

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * header Accept = 'application/json'
    * header Content-Type = 'application/json'

  Scenario Outline: Local login with valid credentials
    Given path '/auth/local'
    And request { "name": "<name>", "password": "<password>" }
    When method POST
    Then status 201
    And match response.id == '#number'
    And match response.statusCall == '#string'
    And match response.token == '#string'

    Examples:
      | read('auth_local_post.csv') |

  Scenario Outline: Local login with invalid credentials - Unauthorized
    Given path '/auth/local'
    And request { "name": "<name>", "password": "<password>" }
    When method POST
    Then status 401
    And match response.code == 401
    And match response.message == '#string'
    And match response.stack == '##string'
    And match response.details == '##object'

    Examples:
      | name      | password    |
      | wronguser | wrongpass   |
      | testuser  | wrongpass   |
      | wronguser | testpass123 |

  Scenario Outline: Local login with missing required fields
    Given path '/auth/local'
    And request <requestBody>
    When method POST
    Then assert responseStatus != 200

    Examples:
      | requestBody                   |
      | { "name": "testuser" }        |
      | { "password": "testpass123" } |
      | {}                            |

  Scenario Outline: Local login with invalid data types
    Given path '/auth/local'
    And request { "name": <name>, "password": <password> }
    When method POST
    Then assert responseStatus != 200

    Examples:
      | name   | password |
      |    123 | "pass"   |
      | "user" |      456 |
      | null   | "pass"   |
      | "user" | null     |

  Scenario: Local login with empty string values
    Given path '/auth/local'
    And request { "name": "", "password": "" }
    When method POST
    Then assert responseStatus != 200

  Scenario: Local login causing internal server error
    Given path '/auth/local'
    And request { "name": "serverErrorUser", "password": "serverErrorPass" }
    When method POST
    Then status 500
    And match response.code == 500
    And match response.message == '#string'
    And match response.stack == '##string'
    And match response.details == '##object'

  Scenario: Local login with malformed JSON
    Given path '/auth/local'
    And request '{"name": "testuser", "password": }'
    When method POST
    Then assert responseStatus != 200

  Scenario: Local login with additional properties
    Given path '/auth/local'
    And request { "name": "testuser", "password": "testpass123", "extraField": "extraValue" }
    When method POST
    Then status 201
    And match response.id == '#number'
    And match response.statusCall == '#string'
    And match response.token == '#string'

  Scenario Outline: Local login with boundary values
    Given path '/auth/local'
    And request { "name": "<name>", "password": "<password>" }
    When method POST
    Then status 201
    And match response.id == '#number'
    And match response.statusCall == '#string'
    And match response.token == '#string'

    Examples:
      | read('auth_local_post.csv') |
