# ********RoostGPT********

# Test generated by RoostGPT for test xcally-karate using AI Type Claude AI and AI Model claude-sonnet-4-20250514
# 
# Feature file generated for /auth/local/reset/{token}_post for http method type POST 
# RoostTestHash=6688bb3a38
# 
# 

# ********RoostGPT********
Feature: Reset user password

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * configure headers = { Accept: 'application/json', Content-Type: 'application/json' }

  Scenario Outline: Reset user password with valid token and password
    Given path '/auth/local/reset/<token>'
    And request
      """
      {
        "password": "<password>"
      }
      """
    When method POST
    Then status 201

    Examples:
      | read('auth_local_reset_token_post.csv') |

  Scenario Outline: Reset user password with invalid token
    Given path '/auth/local/reset/<token>'
    And request
      """
      {
        "password": "<password>"
      }
      """
    When method POST
    Then assert responseStatus != 200

    Examples:
      | token           | password            |
      | 'invalid-token' | 'newPassword123!'   |
      | 'expired-token' | 'SecurePass456@'    |
      | ''              | 'MyNewPassword789#' |

  Scenario Outline: Reset user password with missing password field
    Given path '/auth/local/reset/<token>'
    And request
      """
      {
      }
      """
    When method POST
    Then assert responseStatus != 200

    Examples:
      | token                   |
      | 'valid-reset-token-123' |
      | 'another-valid-token'   |

  Scenario Outline: Reset user password with empty password
    Given path '/auth/local/reset/<token>'
    And request
      """
      {
        "password": ""
      }
      """
    When method POST
    Then assert responseStatus != 200

    Examples:
      | token                   |
      | 'valid-reset-token-123' |
      | 'another-valid-token'   |

  Scenario Outline: Reset user password with null password
    Given path '/auth/local/reset/<token>'
    And request
      """
      {
        "password": null
      }
      """
    When method POST
    Then assert responseStatus != 200

    Examples:
      | token                   |
      | 'valid-reset-token-123' |
      | 'another-valid-token'   |

  Scenario Outline: Reset user password - Internal server error
    Given path '/auth/local/reset/<token>'
    And request
      """
      {
        "password": "<password>"
      }
      """
    When method POST
    Then status 500
    And match response.code == 500
    And match response.message == '#string'
    And match response.stack == '##string'
    And match response.details == '##object'

    Examples:
      | token                  | password          |
      | 'server-error-token'   | 'newPassword123!' |
      | 'error-inducing-token' | 'SecurePass456@'  |

  Scenario Outline: Reset user password with various password formats
    Given path '/auth/local/reset/<token>'
    And request
      """
      {
        "password": "<password>"
      }
      """
    When method POST
    Then status 201

    Examples:
      | read('auth_local_reset_token_post.csv') |

  Scenario Outline: Reset user password with special characters in token
    Given path '/auth/local/reset/<token>'
    And request
      """
      {
        "password": "<password>"
      }
      """
    When method POST
    Then status 201

    Examples:
      | read('auth_local_reset_token_post.csv') |

  Scenario: Reset user password with malformed JSON request
    Given path '/auth/local/reset/valid-token'
    And request '{"password": "newPassword123!"'
    When method POST
    Then assert responseStatus != 200

  Scenario: Reset user password with additional unexpected fields
    Given path '/auth/local/reset/valid-token'
    And request
      """
      {
        "password": "newPassword123!",
        "unexpectedField": "unexpectedValue",
        "anotherField": 123
      }
      """
    When method POST
    Then status 201
