# ********RoostGPT********

# Test generated by RoostGPT for test xcally-karate using AI Type Claude AI and AI Model claude-sonnet-4-20250514
# 
# Feature file generated for /auth/local/forgot_post for http method type POST 
# RoostTestHash=57df9e5c0a
# 
# 

# ********RoostGPT********
Feature: Password Reset Token Creation

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * configure headers = { Accept: 'application/json', Content-Type: 'application/json' }

  Scenario Outline: Create password reset token with valid email
    Given path '/auth/local/forgot'
    And request
      """
      {
        "email": "<email>"
      }
      """
    When method POST
    Then status 201

    Examples:
      | read('auth_local_forgot_post.csv') |

  Scenario: Create password reset token with missing email field
    Given path '/auth/local/forgot'
    And request
      """
      {
      }
      """
    When method POST
    Then assert responseStatus != 200

  Scenario: Create password reset token with null email
    Given path '/auth/local/forgot'
    And request
      """
      {
        "email": null
      }
      """
    When method POST
    Then assert responseStatus != 200

  Scenario: Create password reset token with empty email
    Given path '/auth/local/forgot'
    And request
      """
      {
        "email": ""
      }
      """
    When method POST
    Then assert responseStatus != 200

  Scenario: Create password reset token with invalid email format
    Given path '/auth/local/forgot'
    And request
      """
      {
        "email": "invalid-email"
      }
      """
    When method POST
    Then assert responseStatus != 200

  Scenario: Handle internal server error response
    Given path '/auth/local/forgot'
    And request
      """
      {
        "email": "test@example.com"
      }
      """
    When method POST
    And status 500
    Then match response.code == 500
    And match response.message == '#string'
    And match response.stack == '##string'
    And match response.details == '##object'

  Scenario: Create password reset token with additional properties
    Given path '/auth/local/forgot'
    And request
      """
      {
        "email": "user@test.com",
        "extraField": "extraValue"
      }
      """
    When method POST
    Then status 201

  Scenario: Create password reset token with special characters in email
    Given path '/auth/local/forgot'
    And request
      """
      {
        "email": "user+tag@example-domain.co.uk"
      }
      """
    When method POST
    Then status 201

  Scenario: Create password reset token with long email address
    Given path '/auth/local/forgot'
    And request
      """
      {
        "email": "very.long.email.address.with.multiple.dots@very-long-domain-name.example.com"
      }
      """
    When method POST
    Then status 201

  Scenario: Create password reset token with malformed JSON
    Given path '/auth/local/forgot'
    And request '{"email": "test@example.com"'
    When method POST
    Then assert responseStatus != 200

  Scenario: Create password reset token with wrong content type
    Given path '/auth/local/forgot'
    And header Content-Type = 'text/plain'
    And request 'email=test@example.com'
    When method POST
    Then assert responseStatus != 200
