# ********RoostGPT********

# Test generated by RoostGPT for test karate-dry-run-check using AI Type Azure Open AI and AI Model gpt-4o
# 
# Feature file generated for /employees_get for http method type GET 
# RoostTestHash=ec231a756b
# 
# 

# ********RoostGPT********
Feature: Employee API - Search Employees

  Background:
    * def baseURL = karate.properties['EMPLOYEE_SERVICE_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure report = true
    * header Accept = 'application/json'

  Scenario Outline: Search Employees with valid and invalid searchString query parameter
    Given path 'employees'
    And param searchString = <searchString>
    When method GET
    Then match responseStatus == <statusCode>
    And match response == <responseBody>

    Examples:
      | searchString | statusCode | responseBody                                                                                    |
      | 'John'       |        200 | """[ { "id": "##string", "jobTitle": "##string", "email": "##string", "name": "##string" } ]""" |
      | null         |        200 | """[ { "id": "##string", "jobTitle": "##string", "email": "##string", "name": "##string" } ]""" |
      | ''           |        200 | """[ { "id": "##string", "jobTitle": "##string", "email": "##string", "name": "##string" } ]""" |
      | ['12345']    |        400 | """null"""                                                                                      |

  Scenario: Validate response schema and data types for 200 status code
    Given path 'employees'
    And param searchString = 'John'
    When method GET
    Then match responseStatus == 200
    And match response == '#[] #object'
    And match each response[*].id == '#? _ != null && typeof _ == "string"'
    And match each response[*].jobTitle == '#string'
    And match each response[*].name == '#string'
    And match each response[*].email == '#string'

  Scenario: Make request with missing required fields and validate error response for 400 status code
    Given path 'employees'
    And param searchString = ['12345']
    When method GET
    Then match responseStatus == 400
    And match response == null
