# ********RoostGPT********

# Test generated by RoostGPT for test apiFulfillment using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /listener/productOrderCreateEvent_post for http method type POST 
# RoostTestHash=5d5b9532f3
# 
# 

# ********RoostGPT********
Feature: Product Order Create Event By Client API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { 'Authorization': '#(authToken)' }

  Scenario Outline: Successful Product Order Create Event
    Given path '/listener/productOrderCreateEvent'
    And request
      """
      {
        "notification": {
          "date": "<date>",
          "order": {
            "associatedDocument": "<associatedDocument>",
            "correlationOrder": <correlationOrder>,
            "id": "<id>"
          }
        }
      }
      """
    When method POST
    Then status 204
    And match responseHeaders['Content-Type'][0] contains 'application/json'

    Examples:
      | read('listener_productOrderCreateEvent_post.csv') |

  Scenario: Missing Required Fields
    Given path '/listener/productOrderCreateEvent'
    And request
      """
      {
        "notification": {
          "date": "2021-06-05T20:23:29-03:00"
        }
      }
      """
    When method POST
    Then status 400
    And match response.error contains 'Missing required fields'

  Scenario: Invalid Date Format
    Given path '/listener/productOrderCreateEvent'
    And request
      """
      {
        "notification": {
          "date": "2021-06-05",
          "order": {
            "associatedDocument": "VTT001",
            "correlationOrder": 10,
            "id": "20230315000001"
          }
        }
      }
      """
    When method POST
    Then status 400
    And match response.error contains 'Invalid date format'

  Scenario: Unauthorized Request
    Given path '/listener/productOrderCreateEvent'
    And request
      """
      {
        "notification": {
          "date": "2021-06-05T20:23:29-03:00",
          "order": {
            "associatedDocument": "VTT001",
            "correlationOrder": 10,
            "id": "20230315000001"
          }
        }
      }
      """
    When method POST
    Then status 401
    And match response.error contains 'Unauthorized'

  Scenario: Internal Server Error
    Given path '/listener/productOrderCreateEvent'
    And request
      """
      {
        "notification": {
          "date": "2021-06-05T20:23:29-03:00",
          "order": {
            "associatedDocument": "VTT001",
            "correlationOrder": 10,
            "id": "20230315000001"
          }
        }
      }
      """
    When method POST
    Then status 500
    And match response.error contains 'Internal Server Error'
