# ********RoostGPT********

# Test generated by RoostGPT for test apiFulfillment using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /listener/productOrderStateChangeEvent_post for http method type POST 
# RoostTestHash=a9bfb68d42
# 
# 

# ********RoostGPT********
Feature: Test /listener/productOrderStateChangeEvent API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { Authorization: #(karate.properties['AUTH_TOKEN']) }

  Scenario Outline: Test State Change Event By Client API
    Given path '/listener/productOrderStateChangeEvent'
    And request
      """
      {
        "notification": {
          "customer": {
            "subscriberId": "<subscriberId>"
          },
          "date": "<date>",
          "order": {
            "associatedDocument": "<associatedDocument>",
            "code": "<code>",
            "correlationOrder": "<correlationOrder>",
            "description": "<description>",
            "id": "<id>",
            "lostEquipment": "<lostEquipment>",
            "resource": {
              "fiberPath": {
                "items": <items>
              },
              "gponAccess": "<gponAccess>"
            },
            "type": "<type>"
          }
        }
      }
      """
    When method POST
    Then status <expectedStatus>
    And match response == <expectedResponse>

    Examples:
      | read('listener_productOrderStateChangeEvent_post.csv') |

  Scenario: Test Bad Request
    Given path '/listener/productOrderStateChangeEvent'
    And request {}
    When method POST
    Then status 400
    And match response == "BadRequest"

  Scenario: Test Unauthorized
    Given path '/listener/productOrderStateChangeEvent'
    And request {}
    When method POST
    Then status 401
    And match response == "Unauthorized"

  Scenario: Test Server Error
    Given path '/listener/productOrderStateChangeEvent'
    And request {}
    When method POST
    Then status 500
    And match response == "ServerError"

  Scenario: Test Unavailable
    Given path '/listener/productOrderStateChangeEvent'
    And request {}
    When method POST
    Then status 503
    And match response == "Unavailable"

  Scenario: Test Timeout
    Given path '/listener/productOrderStateChangeEvent'
    And request {}
    When method POST
    Then status 504
    And match response == "Timeout"
