# ********RoostGPT********

# Test generated by RoostGPT for test apiFulfillment using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /listener/productOrderInformationRequiredEvent_post for http method type POST 
# RoostTestHash=ce4c08f30f
# 
# 

# ********RoostGPT********
Feature: Product Order Information Required Event API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']

  Scenario Outline: Successful notification of product order information required event
    Given path '/listener/productOrderInformationRequiredEvent'
    And header Authorization = authToken
    And request
      """
      {
        "notification": {
          "order": {
            "associatedDocument": "<associatedDocument>",
            "correlationOrder": <correlationOrder>,
            "id": "<id>",
            "issue": {
              "action": "<action>",
              "code": <code>,
              "description": "<description>",
              "fieldActivity": <fieldActivity>,
              "observation": "<observation>",
              "reason": "<reason>",
              "task": "<task>",
              "type": "<type>",
              "updateDate": "<updateDate>"
            }
          }
        }
      }
      """
    When method POST
    Then status 204
    And match header Content-Type == 'application/json'

    Examples:
      | read('listener_productOrderInformationRequiredEvent_post.csv') |

  Scenario: Invalid request body
    Given path '/listener/productOrderInformationRequiredEvent'
    And header Authorization = authToken
    And request {}
    When method POST
    Then status 400
    And match header Content-Type == 'application/json'

  Scenario: Unauthorized request
    Given path '/listener/productOrderInformationRequiredEvent'
    And request {}
    When method POST
    Then status 401
    And match header Content-Type == 'application/json'

  Scenario: Server error
    Given path '/listener/productOrderInformationRequiredEvent'
    And header Authorization = authToken
    And request {}
    When method POST
    Then status 500
    And match header Content-Type == 'application/json'
