# ********RoostGPT********

# Test generated by RoostGPT for test apiFulfillment using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /productOrder/{order.Id}_patch for http method type PATCH 
# RoostTestHash=9e8fcf3d77
# 
# 

# ********RoostGPT********
Feature: Update Product Order By Id

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { Authorization: '#(karate.properties.AUTH_TOKEN)' }

  Scenario Outline: Patch Product Order By Id - <name>
    Given path '/productOrder/<order.Id>'
    And request
      """
      <requestBody>
      """
    When method PATCH
    Then status <expectedStatus>
    And match response == <expectedResponse>
    And match responseHeaders['Content-Type'][0] == 'application/json'

    Examples:
      | read('productOrder_order.Id_patch.csv') |
